-- Finalized canonical reporting layer v1
-- Production-safe additive migration.
-- IMPORTANT:
-- 1) Does not touch legacy tables or existing legacy data.
-- 2) Does not modify 003_collector_canonical.sql.
-- 3) Creates only canonical_* v1 tables if they do not already exist.
-- 4) In environments where 003 already created canonical_* tables, this file
--    is intentionally non-destructive and will no-op for those tables.

CREATE TABLE IF NOT EXISTS canonical_source_platforms (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    source_key VARCHAR(64) NOT NULL,
    display_name VARCHAR(128) NOT NULL,
    source_type ENUM('ads', 'analytics', 'programmatic', 'social', 'search', 'other') NOT NULL DEFAULT 'ads',
    default_fact_scope ENUM('campaign', 'delivery_entity') NOT NULL DEFAULT 'delivery_entity',
    default_timezone VARCHAR(64) DEFAULT NULL,
    default_currency VARCHAR(8) DEFAULT NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uniq_canonical_source_platforms_source_key (source_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Grain: 1 row per supported source platform';

CREATE TABLE IF NOT EXISTS canonical_source_accounts (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    source_key VARCHAR(64) NOT NULL,
    platform_account_id VARCHAR(128) NOT NULL,
    external_account_ref VARCHAR(255) DEFAULT NULL,
    account_name VARCHAR(255) DEFAULT NULL,
    advertiser_name VARCHAR(255) DEFAULT NULL,
    account_status VARCHAR(64) DEFAULT NULL,
    currency_code VARCHAR(8) DEFAULT NULL,
    timezone_name VARCHAR(64) DEFAULT NULL,
    first_seen_at DATETIME DEFAULT NULL,
    last_seen_at DATETIME DEFAULT NULL,
    raw_payload JSON DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uniq_canonical_source_accounts (source_key, platform_account_id),
    KEY idx_canonical_source_accounts_source (source_key),
    KEY idx_canonical_source_accounts_status (account_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Grain: 1 row per source account/cabinet/advertiser';

CREATE TABLE IF NOT EXISTS canonical_source_campaigns (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    source_key VARCHAR(64) NOT NULL,
    platform_account_id VARCHAR(128) NOT NULL,
    platform_campaign_id VARCHAR(128) NOT NULL,
    campaign_name VARCHAR(500) DEFAULT NULL,
    campaign_status VARCHAR(64) DEFAULT NULL,
    objective VARCHAR(128) DEFAULT NULL,
    buy_type VARCHAR(64) DEFAULT NULL,
    start_date DATE DEFAULT NULL,
    end_date DATE DEFAULT NULL,
    daily_budget DECIMAL(18,6) DEFAULT NULL,
    total_budget DECIMAL(18,6) DEFAULT NULL,
    currency_code VARCHAR(8) DEFAULT NULL,
    first_seen_at DATETIME DEFAULT NULL,
    last_seen_at DATETIME DEFAULT NULL,
    raw_payload JSON DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uniq_canonical_source_campaigns (source_key, platform_account_id, platform_campaign_id),
    KEY idx_canonical_source_campaigns_source_campaign (source_key, platform_campaign_id),
    KEY idx_canonical_source_campaigns_account (source_key, platform_account_id),
    KEY idx_canonical_source_campaigns_status (campaign_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Grain: 1 row per source campaign';

CREATE TABLE IF NOT EXISTS canonical_source_delivery_entities (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    source_key VARCHAR(64) NOT NULL,
    platform_account_id VARCHAR(128) NOT NULL,
    platform_campaign_id VARCHAR(128) NOT NULL,
    delivery_entity_type ENUM('campaign', 'ad_group', 'ad', 'banner', 'placement', 'post', 'other') NOT NULL DEFAULT 'other',
    platform_delivery_entity_id VARCHAR(128) NOT NULL,
    parent_delivery_entity_id VARCHAR(128) DEFAULT NULL,
    delivery_entity_name VARCHAR(500) DEFAULT NULL,
    delivery_status VARCHAR(64) DEFAULT NULL,
    first_seen_at DATETIME DEFAULT NULL,
    last_seen_at DATETIME DEFAULT NULL,
    raw_payload JSON DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uniq_canonical_source_delivery_entities (source_key, platform_account_id, delivery_entity_type, platform_delivery_entity_id),
    KEY idx_canonical_source_delivery_entities_campaign (source_key, platform_campaign_id),
    KEY idx_canonical_source_delivery_entities_parent (source_key, parent_delivery_entity_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Grain: 1 row per serving/reporting delivery object';

CREATE TABLE IF NOT EXISTS canonical_source_creatives (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    source_key VARCHAR(64) NOT NULL,
    platform_account_id VARCHAR(128) NOT NULL,
    platform_campaign_id VARCHAR(128) NOT NULL,
    platform_delivery_entity_id VARCHAR(128) DEFAULT NULL,
    platform_creative_id VARCHAR(128) NOT NULL,
    creative_name VARCHAR(500) DEFAULT NULL,
    creative_status VARCHAR(64) DEFAULT NULL,
    creative_type VARCHAR(128) DEFAULT NULL,
    creative_format VARCHAR(128) DEFAULT NULL,
    destination_url TEXT DEFAULT NULL,
    final_url TEXT DEFAULT NULL,
    content_ref VARCHAR(255) DEFAULT NULL,
    preview_url TEXT DEFAULT NULL,
    post_id VARCHAR(128) DEFAULT NULL,
    first_seen_at DATETIME DEFAULT NULL,
    last_seen_at DATETIME DEFAULT NULL,
    raw_payload JSON DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uniq_canonical_source_creatives (source_key, platform_account_id, platform_creative_id),
    KEY idx_canonical_source_creatives_campaign (source_key, platform_campaign_id),
    KEY idx_canonical_source_creatives_delivery (source_key, platform_delivery_entity_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Grain: 1 row per creative asset/post/creative object';

CREATE TABLE IF NOT EXISTS canonical_collector_runs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    source_key VARCHAR(64) NOT NULL,
    run_type ENUM('manual', 'cron', 'backfill', 'reconcile', 'preview') NOT NULL DEFAULT 'manual',
    run_mode VARCHAR(64) DEFAULT NULL,
    job_key VARCHAR(128) DEFAULT NULL,
    correlation_id VARCHAR(128) DEFAULT NULL,
    date_from DATE DEFAULT NULL,
    date_to DATE DEFAULT NULL,
    status ENUM('running', 'success', 'partial', 'failed') NOT NULL DEFAULT 'running',
    rows_read BIGINT NOT NULL DEFAULT 0,
    rows_written BIGINT NOT NULL DEFAULT 0,
    rows_updated BIGINT NOT NULL DEFAULT 0,
    error_count BIGINT NOT NULL DEFAULT 0,
    error_summary TEXT DEFAULT NULL,
    started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at DATETIME DEFAULT NULL,
    duration_ms BIGINT DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_canonical_collector_runs_source_started (source_key, started_at),
    KEY idx_canonical_collector_runs_status (status),
    KEY idx_canonical_collector_runs_job_key (job_key),
    KEY idx_canonical_collector_runs_correlation (correlation_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Grain: 1 row per collector run';

CREATE TABLE IF NOT EXISTS canonical_collector_run_events (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    run_id BIGINT UNSIGNED NOT NULL,
    level ENUM('info', 'warning', 'error') NOT NULL DEFAULT 'info',
    event_type VARCHAR(128) DEFAULT NULL,
    message TEXT NOT NULL,
    event_payload JSON DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_canonical_collector_run_events_run (run_id),
    KEY idx_canonical_collector_run_events_level (level),
    CONSTRAINT fk_canonical_collector_run_events_run
        FOREIGN KEY (run_id) REFERENCES canonical_collector_runs(id)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Grain: 1 row per collector run event';

CREATE TABLE IF NOT EXISTS canonical_fact_ads_daily (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    source_key VARCHAR(64) NOT NULL,
    platform_account_id VARCHAR(128) NOT NULL,
    platform_campaign_id VARCHAR(128) NOT NULL,
    fact_scope ENUM('campaign', 'delivery_entity') NOT NULL DEFAULT 'delivery_entity',
    native_grain ENUM('campaign', 'ad_group', 'ad', 'banner', 'placement', 'creative', 'post', 'other') NOT NULL DEFAULT 'other',
    breakdown_scope VARCHAR(32) NOT NULL DEFAULT 'default',
    platform_delivery_entity_id VARCHAR(128) NOT NULL DEFAULT '__campaign__',
    platform_creative_id VARCHAR(128) NOT NULL DEFAULT '',
    report_date DATE NOT NULL,
    spend DECIMAL(18,6) DEFAULT NULL,
    impressions BIGINT DEFAULT NULL,
    clicks BIGINT DEFAULT NULL,
    views BIGINT DEFAULT NULL,
    conversions BIGINT DEFAULT NULL,
    conversion_value DECIMAL(18,6) DEFAULT NULL,
    reach BIGINT DEFAULT NULL,
    frequency DECIMAL(18,6) DEFAULT NULL,
    ctr DECIMAL(18,6) DEFAULT NULL,
    cpm DECIMAL(18,6) DEFAULT NULL,
    cpc DECIMAL(18,6) DEFAULT NULL,
    cpv DECIMAL(18,6) DEFAULT NULL,
    cpa DECIMAL(18,6) DEFAULT NULL,
    video_views_25 BIGINT DEFAULT NULL,
    video_views_50 BIGINT DEFAULT NULL,
    video_views_75 BIGINT DEFAULT NULL,
    video_views_100 BIGINT DEFAULT NULL,
    link_clicks BIGINT DEFAULT NULL,
    likes BIGINT DEFAULT NULL,
    comments BIGINT DEFAULT NULL,
    shares BIGINT DEFAULT NULL,
    reactions BIGINT DEFAULT NULL,
    follows BIGINT DEFAULT NULL,
    currency_code VARCHAR(8) DEFAULT NULL,
    ingestion_run_id BIGINT UNSIGNED DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uniq_canonical_fact_ads_daily (
        source_key,
        report_date,
        platform_account_id,
        platform_campaign_id,
        fact_scope,
        native_grain,
        breakdown_scope,
        platform_delivery_entity_id,
        platform_creative_id
    ),
    KEY idx_canonical_fact_ads_daily_source_date (source_key, report_date),
    KEY idx_canonical_fact_ads_daily_account_date (source_key, platform_account_id, report_date),
    KEY idx_canonical_fact_ads_daily_campaign_date (source_key, platform_campaign_id, report_date),
    KEY idx_canonical_fact_ads_daily_delivery_date (source_key, platform_delivery_entity_id, report_date),
    KEY idx_canonical_fact_ads_daily_creative_date (source_key, platform_creative_id, report_date),
    KEY idx_canonical_fact_ads_daily_run (ingestion_run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Grain: 1 day x 1 source account x 1 campaign x 1 delivery entity x 1 breakdown scope';

CREATE TABLE IF NOT EXISTS canonical_fact_site_analytics_daily (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    source_key VARCHAR(64) NOT NULL,
    analytics_account_id VARCHAR(128) NOT NULL,
    report_date DATE NOT NULL,
    analytics_scope ENUM('traffic', 'goal', 'page', 'params', 'returned', 'other') NOT NULL DEFAULT 'traffic',
    scope_hash CHAR(64) NOT NULL,
    utm_source VARCHAR(255) DEFAULT NULL,
    utm_medium VARCHAR(255) DEFAULT NULL,
    utm_campaign VARCHAR(255) DEFAULT NULL,
    utm_content VARCHAR(255) DEFAULT NULL,
    utm_term VARCHAR(255) DEFAULT NULL,
    goal_id VARCHAR(128) DEFAULT NULL,
    goal_name VARCHAR(255) DEFAULT NULL,
    page_url TEXT DEFAULT NULL,
    page_title VARCHAR(500) DEFAULT NULL,
    region_city VARCHAR(255) DEFAULT NULL,
    traffic_source VARCHAR(255) DEFAULT NULL,
    visits BIGINT DEFAULT NULL,
    users BIGINT DEFAULT NULL,
    new_users BIGINT DEFAULT NULL,
    pageviews BIGINT DEFAULT NULL,
    goal_reaches BIGINT DEFAULT NULL,
    page_depth DECIMAL(18,6) DEFAULT NULL,
    bounce_rate DECIMAL(18,6) DEFAULT NULL,
    avg_visit_duration_seconds DECIMAL(18,6) DEFAULT NULL,
    ingestion_run_id BIGINT UNSIGNED DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uniq_canonical_fact_site_analytics_daily (
        source_key,
        analytics_account_id,
        report_date,
        analytics_scope,
        scope_hash
    ),
    KEY idx_canonical_fact_site_analytics_daily_source_date (source_key, report_date),
    KEY idx_canonical_fact_site_analytics_daily_account_date (analytics_account_id, report_date),
    KEY idx_canonical_fact_site_analytics_daily_run (ingestion_run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Grain: 1 day x 1 analytics account x 1 analytics slice';

CREATE TABLE IF NOT EXISTS canonical_fact_user_behavior_daily (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    source_key VARCHAR(64) NOT NULL,
    analytics_account_id VARCHAR(128) NOT NULL DEFAULT '',
    report_date DATE NOT NULL,
    scope_hash CHAR(64) NOT NULL,
    user_id TEXT NOT NULL,
    traffic_source_id VARCHAR(64) DEFAULT NULL,
    traffic_source VARCHAR(255) DEFAULT NULL,
    start_url TEXT DEFAULT NULL,
    end_url TEXT DEFAULT NULL,
    visits BIGINT DEFAULT NULL,
    users BIGINT DEFAULT NULL,
    new_users BIGINT DEFAULT NULL,
    page_depth DECIMAL(18,6) DEFAULT NULL,
    bounce_rate DECIMAL(18,6) DEFAULT NULL,
    avg_visit_duration_seconds DECIMAL(18,6) DEFAULT NULL,
    up_to_day_user_recency_percentage DECIMAL(18,6) DEFAULT NULL,
    up_to_week_user_recency_percentage DECIMAL(18,6) DEFAULT NULL,
    up_to_month_user_recency_percentage DECIMAL(18,6) DEFAULT NULL,
    ingestion_run_id BIGINT UNSIGNED DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uniq_canonical_fact_user_behavior_daily (
        source_key,
        analytics_account_id,
        report_date,
        scope_hash
    ),
    KEY idx_canonical_fact_user_behavior_daily_source_date (source_key, report_date),
    KEY idx_canonical_fact_user_behavior_daily_account_date (analytics_account_id, report_date),
    KEY idx_canonical_fact_user_behavior_daily_user_date (user_id(128), report_date),
    KEY idx_canonical_fact_user_behavior_daily_run (ingestion_run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Grain: 1 day x 1 analytics account x 1 user x traffic source x start URL x end URL';

CREATE TABLE IF NOT EXISTS canonical_parity_daily (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    source_key VARCHAR(64) NOT NULL,
    report_date DATE NOT NULL,
    platform_account_id VARCHAR(128) NOT NULL DEFAULT '',
    platform_campaign_id VARCHAR(128) NOT NULL DEFAULT '',
    fact_scope ENUM('campaign', 'delivery_entity') NOT NULL DEFAULT 'campaign',
    delivery_entity_id VARCHAR(128) NOT NULL DEFAULT '',
    creative_id VARCHAR(128) NOT NULL DEFAULT '',
    metric_name VARCHAR(64) NOT NULL,
    old_value DECIMAL(24,6) DEFAULT NULL,
    new_value DECIMAL(24,6) DEFAULT NULL,
    delta_abs DECIMAL(24,6) DEFAULT NULL,
    delta_pct DECIMAL(24,6) DEFAULT NULL,
    tolerance_abs DECIMAL(24,6) DEFAULT NULL,
    tolerance_pct DECIMAL(24,6) DEFAULT NULL,
    status ENUM('ok', 'warning', 'mismatch', 'missing_old', 'missing_new') NOT NULL DEFAULT 'ok',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uniq_canonical_parity_daily (
        source_key,
        report_date,
        platform_account_id,
        platform_campaign_id,
        fact_scope,
        delivery_entity_id,
        creative_id,
        metric_name
    ),
    KEY idx_canonical_parity_daily_source_date (source_key, report_date),
    KEY idx_canonical_parity_daily_account_date (source_key, platform_account_id, report_date),
    KEY idx_canonical_parity_daily_status (status),
    KEY idx_canonical_parity_daily_metric (metric_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Grain: 1 source/date/account/campaign/entity/metric parity comparison';

INSERT INTO canonical_source_platforms (
    source_key,
    display_name,
    source_type,
    default_fact_scope,
    default_timezone,
    default_currency,
    is_active
) VALUES
    ('linkedin', 'LinkedIn Ads', 'ads', 'delivery_entity', 'Europe/Vienna', 'EUR', 1),
    ('reddit', 'Reddit Ads', 'ads', 'delivery_entity', 'UTC', 'EUR', 1),
    ('yandex_direct', 'Yandex Direct', 'search', 'delivery_entity', 'Europe/Moscow', 'RUB', 1),
    ('hybrid', 'Hybrid', 'programmatic', 'delivery_entity', 'Europe/Moscow', 'RUB', 1),
    ('getintent', 'GetIntent', 'programmatic', 'delivery_entity', 'Europe/Moscow', 'RUB', 1),
    ('vk_ads_v2', 'VK Ads v2', 'ads', 'delivery_entity', 'Europe/Moscow', 'RUB', 1),
    ('yandex_metrika', 'Yandex Metrika', 'analytics', 'campaign', 'Europe/Moscow', 'RUB', 1)
ON DUPLICATE KEY UPDATE
    display_name = VALUES(display_name),
    source_type = VALUES(source_type),
    default_fact_scope = VALUES(default_fact_scope),
    default_timezone = VALUES(default_timezone),
    default_currency = VALUES(default_currency),
    is_active = VALUES(is_active),
    updated_at = CURRENT_TIMESTAMP;
