CREATE TABLE IF NOT EXISTS yandex_direct_keyword_performance_daily (
  report_date DATE NOT NULL,
  client_login VARCHAR(255) NOT NULL,
  account_id VARCHAR(255) NOT NULL DEFAULT '',
  campaign_id VARCHAR(64) NOT NULL,
  campaign_name VARCHAR(500),
  ad_group_id VARCHAR(64) NOT NULL DEFAULT '',
  ad_group_name VARCHAR(500),
  criterion_id VARCHAR(96) NOT NULL,
  criterion_text VARCHAR(2048),
  criterion_type VARCHAR(64),
  currency_code VARCHAR(8) NOT NULL DEFAULT 'RUB',
  cost DECIMAL(18,6) DEFAULT 0,
  impressions BIGINT DEFAULT 0,
  clicks BIGINT DEFAULT 0,
  conversions DECIMAL(18,6) DEFAULT 0,
  ctr DECIMAL(18,6) DEFAULT NULL,
  avg_cpc DECIMAL(18,6) DEFAULT NULL,
  conversion_rate DECIMAL(18,6) DEFAULT NULL,
  raw_payload JSON DEFAULT NULL,
  ingestion_run_id BIGINT UNSIGNED DEFAULT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (report_date, client_login, campaign_id, ad_group_id, criterion_id),
  KEY idx_yd_keyword_perf_campaign_date (campaign_id, report_date),
  KEY idx_yd_keyword_perf_client_date (client_login, report_date),
  KEY idx_yd_keyword_perf_type_date (criterion_type, report_date),
  KEY idx_yd_keyword_perf_run (ingestion_run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
