CREATE TABLE IF NOT EXISTS yandex_direct_control_settings (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  dashboard_id BIGINT UNSIGNED NOT NULL,
  client_login VARCHAR(255) NOT NULL,
  account_id VARCHAR(255) NOT NULL DEFAULT '',
  campaign_id VARCHAR(64) NOT NULL,
  control_enabled TINYINT(1) NOT NULL DEFAULT 0,
  campaign_mutations_enabled TINYINT(1) NOT NULL DEFAULT 0,
  bid_mutations_enabled TINYINT(1) NOT NULL DEFAULT 0,
  apply_enabled TINYINT(1) NOT NULL DEFAULT 0,
  auto_collect_enabled TINYINT(1) NOT NULL DEFAULT 1,
  lookback_days INT NOT NULL DEFAULT 14,
  max_apply_per_run INT NOT NULL DEFAULT 10,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_yandex_direct_control_scope (dashboard_id, client_login, campaign_id),
  KEY idx_yandex_direct_control_dashboard (dashboard_id),
  KEY idx_yandex_direct_control_login_campaign (client_login, campaign_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS yandex_direct_mutation_log (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  dashboard_id BIGINT UNSIGNED NOT NULL,
  client_login VARCHAR(255) NOT NULL,
  account_id VARCHAR(255) NOT NULL DEFAULT '',
  campaign_id VARCHAR(64) NOT NULL,
  mutation_type VARCHAR(64) NOT NULL,
  entity_type VARCHAR(64) NOT NULL,
  entity_id VARCHAR(255) NOT NULL,
  payload_json JSON DEFAULT NULL,
  operation_type VARCHAR(64) NOT NULL DEFAULT 'planned',
  approval_ref VARCHAR(128) DEFAULT NULL,
  request_payload JSON DEFAULT NULL,
  response_payload JSON DEFAULT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'planned',
  error_message TEXT DEFAULT NULL,
  review_note TEXT DEFAULT NULL,
  reviewed_by VARCHAR(255) DEFAULT NULL,
  reviewed_at TIMESTAMP NULL DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  applied_at DATETIME DEFAULT NULL,
  PRIMARY KEY (id),
  KEY idx_yandex_direct_mutation_scope (dashboard_id, client_login, campaign_id),
  KEY idx_yandex_direct_mutation_status (status),
  KEY idx_yandex_direct_mutation_type (mutation_type),
  KEY idx_yandex_direct_mutation_entity (entity_type, entity_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
