CREATE TABLE IF NOT EXISTS seo_webmaster_queries_weekly (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  analytics_account_id VARCHAR(128) NOT NULL,
  host_id VARCHAR(255) NOT NULL,
  week_key VARCHAR(8) NOT NULL,
  week_from DATE NOT NULL,
  week_to DATE NOT NULL,
  device_type VARCHAR(32) NOT NULL DEFAULT 'ALL',
  query_id VARCHAR(255) NOT NULL,
  query_text TEXT NOT NULL,
  impressions BIGINT NOT NULL DEFAULT 0,
  clicks BIGINT NOT NULL DEFAULT 0,
  ctr DECIMAL(18,6) DEFAULT NULL,
  average_position DECIMAL(18,6) DEFAULT NULL,
  raw_payload JSON DEFAULT NULL,
  ingestion_run_id BIGINT DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_seo_webmaster_queries_weekly (analytics_account_id, week_key, device_type, query_id),
  KEY idx_seo_webmaster_queries_weekly_week (analytics_account_id, week_key),
  KEY idx_seo_webmaster_queries_weekly_query (analytics_account_id, query_id),
  KEY idx_seo_webmaster_queries_weekly_run (ingestion_run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Yandex Webmaster query facts; grain: account x week x device x query';

CREATE TABLE IF NOT EXISTS seo_webmaster_pages_weekly (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  analytics_account_id VARCHAR(128) NOT NULL,
  host_id VARCHAR(255) NOT NULL,
  week_key VARCHAR(8) NOT NULL,
  week_from DATE NOT NULL,
  week_to DATE NOT NULL,
  device_type VARCHAR(32) NOT NULL DEFAULT 'ALL',
  page_url TEXT NOT NULL,
  page_hash CHAR(64) NOT NULL,
  impressions BIGINT NOT NULL DEFAULT 0,
  clicks BIGINT NOT NULL DEFAULT 0,
  ctr DECIMAL(18,6) DEFAULT NULL,
  average_position DECIMAL(18,6) DEFAULT NULL,
  raw_payload JSON DEFAULT NULL,
  ingestion_run_id BIGINT DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_seo_webmaster_pages_weekly (analytics_account_id, week_key, device_type, page_hash),
  KEY idx_seo_webmaster_pages_weekly_week (analytics_account_id, week_key),
  KEY idx_seo_webmaster_pages_weekly_run (ingestion_run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Yandex Webmaster URL facts; grain: account x week x device x URL';

CREATE TABLE IF NOT EXISTS seo_ai_visibility_weekly (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  analytics_account_id VARCHAR(128) NOT NULL,
  source_key VARCHAR(64) NOT NULL DEFAULT 'seo_os',
  week_key VARCHAR(8) NOT NULL,
  cluster_id VARCHAR(128) NOT NULL,
  query_text TEXT NOT NULL,
  engine VARCHAR(64) NOT NULL,
  region_id VARCHAR(64) NOT NULL DEFAULT '225',
  language_code VARCHAR(16) NOT NULL DEFAULT 'ru',
  device_type VARCHAR(32) NOT NULL DEFAULT 'desktop',
  mentioned TINYINT(1) NOT NULL DEFAULT 0,
  mention_count INT NOT NULL DEFAULT 0,
  citation_count INT NOT NULL DEFAULT 0,
  cited_urls_json JSON DEFAULT NULL,
  checked_at DATETIME DEFAULT NULL,
  run_id VARCHAR(128) DEFAULT NULL,
  raw_payload JSON DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_seo_ai_visibility_weekly (analytics_account_id, week_key, cluster_id, engine, region_id, language_code, device_type),
  KEY idx_seo_ai_visibility_weekly_week (analytics_account_id, week_key),
  KEY idx_seo_ai_visibility_weekly_run (run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI visibility facts exported by SEO OS; grain: account x week x cluster x AI engine';
