CREATE TABLE IF NOT EXISTS canonical_fact_gsc_search_appearance_daily (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  source_key VARCHAR(64) NOT NULL DEFAULT 'google_search_console',
  analytics_account_id BIGINT NOT NULL,
  report_date DATE NOT NULL,
  search_type VARCHAR(32) NOT NULL DEFAULT 'web',
  search_appearance VARCHAR(128) NOT NULL,
  page TEXT NOT NULL,
  country VARCHAR(16) NOT NULL DEFAULT '',
  device VARCHAR(32) NOT NULL DEFAULT '',
  feature_hash CHAR(64) NOT NULL,
  impressions INT UNSIGNED NOT NULL DEFAULT 0,
  clicks INT UNSIGNED NOT NULL DEFAULT 0,
  ctr DECIMAL(12,8) NULL,
  position DECIMAL(10,4) NULL,
  raw_payload JSON NULL,
  ingestion_run_id BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_gsc_search_appearance_daily (analytics_account_id, report_date, search_type, feature_hash),
  KEY idx_gsc_search_appearance_account_date (analytics_account_id, report_date),
  KEY idx_gsc_search_appearance_type (search_type, search_appearance),
  KEY idx_gsc_search_appearance_run (ingestion_run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS canonical_fact_gsc_search_type_daily (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  source_key VARCHAR(64) NOT NULL DEFAULT 'google_search_console',
  analytics_account_id BIGINT NOT NULL,
  report_date DATE NOT NULL,
  search_type VARCHAR(32) NOT NULL,
  page TEXT NOT NULL,
  country VARCHAR(16) NOT NULL DEFAULT '',
  device VARCHAR(32) NOT NULL DEFAULT '',
  type_hash CHAR(64) NOT NULL,
  impressions INT UNSIGNED NOT NULL DEFAULT 0,
  clicks INT UNSIGNED NOT NULL DEFAULT 0,
  ctr DECIMAL(12,8) NULL,
  position DECIMAL(10,4) NULL,
  raw_payload JSON NULL,
  ingestion_run_id BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_gsc_search_type_daily (analytics_account_id, report_date, search_type, type_hash),
  KEY idx_gsc_search_type_account_date (analytics_account_id, report_date),
  KEY idx_gsc_search_type (search_type),
  KEY idx_gsc_search_type_run (ingestion_run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
