import type { DashboardData } from "../../../../src/lib/types";
export function abbottFixture(): DashboardData {
  return {
    dashboard: {
      client_name: "Abbott",
      dashboard_name: "Private analytics",
      type: "abbott_bi",
      period: { from: "2026-07-01", to: "2026-07-15" },
      currency: "RUB",
      language: "ru",
      show_spend: false,
      filter_scope: "both",
      section_order: [],
    },
    kpi_config: [],
    kpi: {
      total_impressions: 0,
      total_clicks: 0,
      total_spend: 0,
      total_conversions: 0,
      avg_ctr: 0,
      avg_cpm: 0,
      prev_impressions: 0,
      prev_clicks: 0,
      prev_spend: 0,
      prev_conversions: 0,
      prev_ctr: 0,
      prev_cpm: 0,
    },
    platforms: [],
    timeseries: [],
    plan_vs_fact: [],
    abbott_bi: {
      counters: ["90602537"],
      users_summary: [
        {
          user_id: "raw-user-42",
          has_user_id: true,
          traffic_segment: null,
          traffic_source: "Direct",
          direction: "Cardiology",
          visits: 3,
          users: 1,
          new_users: 0,
          page_depth: 2,
          avg_duration: 90,
          bounce_rate: 0,
        },
      ],
      users_summary_without_admins: [],
      admin_user_filter: { available: true },
      traffic_summary: [
        {
          user_id: "",
          has_user_id: false,
          traffic_segment: null,
          traffic_source: "Organic",
          direction: null,
          visits: 50,
          users: 40,
          new_users: 30,
          page_depth: 1.5,
          avg_duration: 75,
          bounce_rate: 20,
        },
      ],
      user_actions: [
        {
          user_id: "raw-user-42",
          has_user_id: true,
          traffic_source: "Direct",
          utm_source: "newsletter",
          direction: "Cardiology",
          start_url: "https://example.test/start?token=private#section",
          end_url: "https://example.test/end?doctor=private#footer",
          visits: 1,
          page_depth: 2,
          avg_duration: 90,
          is_admin_user: true,
        },
      ],
      page_stats: [
        {
          page_title: "Material",
          url: "https://example.test/material?utm_source=secret#chapter",
          direction: "Cardiology",
          material_type: "Article",
          access: "Public",
          pageviews: 10,
          users: 8,
          bitrix_pageviews: 5,
          bitrix_sessions: 4,
          bitrix_users: 3,
          bitrix_logged_in_sessions: 2,
          bitrix_anonymous_sessions: 2,
          bitrix_avg_session_duration: 60,
        },
      ],
      bitrix_pages: [
        {
          url: "https://example.test/bitrix?sid=private#top",
          path: "/bitrix?sid=private#top",
          direction: "Cardiology",
          material_type: "Article",
          access: "Public",
          pageviews: 5,
          sessions: 4,
          users: 3,
          guests: 1,
          logged_in_hits: 4,
          anonymous_hits: 1,
          logged_in_sessions: 3,
          anonymous_sessions: 1,
          entry_sessions: 2,
          exit_sessions: 2,
          avg_session_duration: 60,
          top_utm_source: "email",
          top_utm_medium: "newsletter",
          top_utm_campaign: "launch",
        },
      ],
      bitrix_summary: null,
      bitrix_period_active: true,
      session_journeys: {
        report_date: "2026-07-15",
        schema: null,
        summary: {
          sessions_in_day: 1,
          sessions_exported: 1,
          sessions_with_user_id: 1,
          sessions_with_content_path: 1,
          hits_total: 2,
          hits_clean: 2,
          events_available: true,
        },
        rows: [
          {
            session_id: 777,
            user_id: "raw-user-42",
            has_user_id: true,
            entry_url_day: "https://example.test/entry?sid=private#start",
            exit_url_day: "https://example.test/exit?sid=private#end",
            entry_url_session: "/entry?sid=private#start",
            exit_url_session: "/exit?sid=private#end",
            hits_total: 2,
            hits_clean: 2,
            hits_content: 2,
            steps_content: 2,
            events_count: 1,
            duration_seconds: 60,
            content_path: [
              "https://example.test/entry?sid=private#start",
              "https://example.test/exit?sid=private#end",
            ],
            content_path_summary:
              "https://example.test/entry?sid=private#start -> https://example.test/exit?sid=private#end",
            all_path_summary: "/entry?sid=private#start -> /exit?sid=private#end",
            events_available: true,
          },
        ],
      },
      external_events: [
        {
          title: "Conference",
          direction: "Cardiology",
          registration_url: "https://events.test/register?email=private#form",
          access: "Public",
        },
      ],
      external_clicks: [
        {
          title: "Conference",
          direction: "Cardiology",
          external_url: "https://events.test/register?email=private#form",
          outbound_clicks: 7,
        },
      ],
      time_buckets: {
        overall: [{ bucket_id: "lt_1m", label: "< 1 minute", users: 10 }],
        materials: [{ bucket_id: "lt_1m", label: "< 1 minute", users: 6 }],
        by_page: [
          {
            url: "https://example.test/material?doctor=private#time",
            buckets: [{ bucket_id: "lt_1m", label: "< 1 minute", users: 6 }],
          },
        ],
      },
      returning: [
        {
          url: "https://example.test/material?doctor=private#returning",
          direction: "Cardiology",
          visits: 10,
          returning_1_day: 2,
          returning_2_7_days: 3,
          returning_8_31_days: 1,
        },
      ],
      return_frequency: {
        available: true,
        period_local: true,
        identified_visitors: 2,
        unidentified_visits: 1,
        groups: [{
          group_id: "two_to_three",
          label: "2–3 раза",
          visitors: 2,
          share: 100,
          visits: 5,
        }],
        user_directions: [{
          direction: "Cardiology",
          frequency_group: "two_to_three",
          visitors: 2,
          repeat_visits: 3,
        }],
        return_pages: [{
          url: "https://example.test/return?doctor=private#landing",
          direction: "Cardiology",
          frequency_group: "two_to_three",
          returning_visitors: 2,
          repeat_visits: 3,
        }],
      },
      general_materials: [
        {
          material_name: "Material",
          url: "https://example.test/material?doctor=private#general",
          pageviews: 10,
          users: 8,
        },
      ],
    },
  };
}
