import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import path from'node:path';import vm from'node:vm';import{execFileSync}from'node:child_process';
const api=()=>import('./runtime-release-remote.mjs');
const base=body=>'server { listen 80; server_name dashboards.adreports.ru alias.example; return 301 https://$host$request_uri; }\nserver { listen 443 ssl; server_name alias.example dashboards.adreports.ru; '+body+' }\n';
const zone='limit_req_zone $binary_remote_addr zone=perip:10m rate=10r/s;\n';
test('inactive HTTP rate shapes preserve baseline even when not valid in selected TLS',async()=>{const m=await api();for(const inactive of ['if ($host) { limit_req zone=missing; }','limit_req_zone $binary_remote_addr zone=inactive:10m rate=1r/s;']){const text=base('').replace('return 301',inactive+' return 301');assert.doesNotThrow(()=>m.validateAbbottNginxText(text));}assert.throws(()=>m.validateAbbottNginxText(base('limit_req zone=missing;')));assert.throws(()=>m.validateAbbottNginxText(base(zone)));});
test('bounded literal rate zones and declared selected limit_req are accepted',async()=>{const m=await api();for(const declaration of [zone,'limit_req_zone $server_name rate=30r/m zone=perserver:64k;\n','limit_req_zone literal_key zone=perserver:65536 rate=1r/s;\n']){const name=declaration.includes('perip:')?'perip':'perserver';for(const options of ['', ' burst=1',' burst=100 nodelay',' burst=100 delay=10',' delay=1',' nodelay'])for(const scope of ['server','location']){const limit='limit_req zone='+name+options+';',body=scope==='server'?limit+' location / { proxy_pass http://127.0.0.1:3001; }':'location / { '+limit+' proxy_pass http://127.0.0.1:3001; }';assert.doesNotThrow(()=>m.validateAbbottNginxText(declaration+base(body)));assert.deepEqual(m.classifyAbbottNginxFirstRejection(declaration+base(body)),{rejection:'none'});}}});
test('rate zone grammar rejects missing duplicate malformed routing and block inputs',async()=>{const m=await api();const bad=[
 'limit_req_zone $binary_remote_addr zone=perip:10m rate=10r/s { return 404; }',
 'limit_req_zone zone=perip:10m rate=10r/s;', 'limit_req_zone "" zone=perip:10m rate=10r/s;',
 'limit_req_zone $binary_remote_addr zone=perip:10m;', 'limit_req_zone $binary_remote_addr rate=10r/s;',
 'limit_req_zone key zone=perip:10m zone=other:10m rate=1r/s;', 'limit_req_zone key zone=perip:10m rate=1r/s rate=2r/m;',
 ...['0','-1','1k','65535','2g','999999999999999999999m','10.5m','$size'].map(size=>'limit_req_zone key zone=perip:'+size+' rate=1r/s;'),
 ...['0r/s','-1r/s','1.5r/s','1r/h','1R/S','1000001r/s','$rate'].map(rate=>'limit_req_zone key zone=perip:10m rate='+rate+';'),
 ...['$name','../name','name/path','name?key=x','0name','x'.repeat(65)].map(name=>'limit_req_zone key zone='+name+':10m rate=1r/s;'),
 ...['/dashboard/18','https://private.invalid','%2fapi','key value','$x${y}','3004','ABBOTT'].map(key=>'limit_req_zone "'+key+'" zone=perip:10m rate=1r/s;'),
 'limit_req_zone key zone=perip:10m rate=1r/s sync;', 'limit_req_zone key zone=perip:10m rate=1r/s unknown;', zone+zone,
 ];for(const declaration of bad)assert.throws(()=>m.validateAbbottNginxText(declaration+base('location / { proxy_pass http://127.0.0.1:3001; }')));});
test('limit_req permits only declared literal zone and bounded nonconflicting options',async()=>{const m=await api();for(const args of ['', 'zone=unknown','zone=$name','zone=perip zone=perip','zone=perip burst=0','zone=perip burst=-1','zone=perip burst=1.5','zone=perip burst=$n','zone=perip burst=1000001','zone=perip burst=1 burst=2','zone=perip delay=0','zone=perip delay=-1','zone=perip delay=1.5','zone=perip delay=$n','zone=perip delay=1000001','zone=perip delay=1 delay=2','zone=perip delay=1 nodelay','zone=perip nodelay nodelay','zone=perip nodelay=1','zone=perip unknown','zone=/dashboard/18','zone=perip burst=3004x'])assert.throws(()=>m.validateAbbottNginxText(zone+base('location / { limit_req '+args+'; }')));assert.throws(()=>m.validateAbbottNginxText(zone+base('limit_req zone=perip { return 404; }')));});
test('rate limit context and other top-level directives remain refused',async()=>{const m=await api();for(const text of [base(zone),base('location / { '+zone+' }'),zone+'limit_req zone=perip;'+base(''),zone+base('location / { location /nested { limit_req zone=perip; } }'),zone+'include /private;'+base(''),zone+'map $x $y { default x; }'+base('')])assert.throws(()=>m.validateAbbottNginxText(text));});
test('rate grammar numeric key and declaration bounds are explicit',async()=>{const m=await api();const valid=['limit_req_zone key zone=one:64K rate=1000000r/s;','limit_req_zone $remote_addr zone=one:1024M rate=1r/m;','limit_req_zone '+'x'.repeat(128)+' zone=one:1m rate=1r/s;'];for(const declaration of valid)assert.doesNotThrow(()=>m.validateAbbottNginxText(declaration+base('limit_req zone=one burst=1000000 delay=1000000;')));for(const declaration of [valid[0].replace('64K','1025M'),valid[2].replace('x'.repeat(128),'x'.repeat(129)),Array.from({length:65},(_,i)=>'limit_req_zone key zone=zone'+i+':64k rate=1r/s;').join('')])assert.throws(()=>m.validateAbbottNginxText(declaration+base('')));});
test('same-zone applications cannot repeat in one context but inheritance and distinct zones remain valid',async()=>{const m=await api();for(const body of ['limit_req zone=perip; limit_req zone=perip;','location / { limit_req zone=perip burst=5; limit_req zone=perip burst=10; }'])assert.throws(()=>m.validateAbbottNginxText(zone+base(body)));for(const body of ['limit_req zone=perip; location / { limit_req zone=perip; }','location / { limit_req zone=perip; } location /status { limit_req zone=perip; }','limit_req zone=perip; limit_req zone=perhost;'])assert.doesNotThrow(()=>m.validateAbbottNginxText(zone+'limit_req_zone $server_name zone=perhost:10m rate=1r/s;'+base(body)));});
test('exact one-GiB byte size matches suffix boundary and next byte refuses',async()=>{const m=await api();assert.doesNotThrow(()=>m.validateAbbottNginxText('limit_req_zone key zone=one:1073741824 rate=1r/s;'+base('')));assert.throws(()=>m.validateAbbottNginxText('limit_req_zone key zone=one:1073741825 rate=1r/s;'+base('')));});
test('first deployment rejection reports top-level fixed context names before TLS selection',async()=>{const m=await api();assert.equal(typeof m.classifyAbbottNginxFirstRejection,'function');for(const name of ['upstream','map','geo','split_clients','log_format','proxy_cache_path','limit_req_zone','limit_conn_zone','private_token'])for(const ending of [';',' { secret_child private_value; }']){const text=name+' private_value'+ending+base('sendfile on;');assert.deepEqual(m.classifyAbbottNginxFirstRejection(text),{rejection:'top_'+(name==='private_token'?'other':name)});assert.throws(()=>m.validateAbbottNginxText(text));}});
test('top upstream server leaf is not a nested TLS authority block',async()=>{const m=await api();assert.deepEqual(m.classifyAbbottNginxFirstRejection('upstream private_name { server 127.0.0.1:3001; }'+base('')),{rejection:'top_upstream'});assert.deepEqual(m.classifyAbbottNginxFirstRejection('upstream private_name { server { listen 443 ssl; } }'+base('')),{reason:'parser_ambiguity'});});
test('first rejection never continues past selected unsupported node or returns partial inventory',async()=>{const m=await api();assert.equal(typeof m.classifyAbbottNginxFirstRejection,'function');for(const [body,code]of [['sendfile on; root /secret;','selected_sendfile'],['private_token value;','selected_other'],['location / { proxy_redirect off; }','selected_proxy_redirect'],['map private { hidden value; }','selected_map']]){const result=m.classifyAbbottNginxFirstRejection(base(body+' location ~ /later { root /secret; }'));assert.deepEqual(result,{rejection:code});assert.doesNotMatch(JSON.stringify(result),/private|secret|later|root/);}assert.deepEqual(m.classifyAbbottNginxFirstRejection(base('location / { proxy_pass http://127.0.0.1:3001; }')),{rejection:'none'});});
test('first rejection retains syntax and TLS ambiguity instead of inventing directive names',async()=>{const m=await api();assert.equal(typeof m.classifyAbbottNginxFirstRejection,'function');for(const text of ['upstream x {',base('sendfile on;')+'server { listen 443; server_name dashboards.adreports.ru; }',base('location ~ /x { root /secret; }'),'upstream x { server { listen 443 ssl; } }'+base(''),'server value;'+base('')])assert.deepEqual(m.classifyAbbottNginxFirstRejection(text),{reason:'parser_ambiguity'});});
test('unknown directive is successful analysis, ambiguity is a separate closed refusal',async()=>{const m=await api();assert.deepEqual(m.diagnoseAbbottNginxText(base('private_secret value;')),['other']);for(const text of [base('sendfile on; location ~ /x { root /secret; }'),base('sendfile on;')+'}',base('sendfile on;')+'server { listen 443; server_name dashboards.adreports.ru; }'])assert.deepEqual(m.diagnoseAbbottNginxText(text),{reason:'parser_ambiguity'});});
test('known opaque block names are diagnosed but never traversed or accepted by deploy',async()=>{const m=await api();for(const body of ['if ($secret) { secret_nested value; }','types { private_nested secret; }','location / { limit_except GET { private_nested secret; } }']){const name=body.startsWith('location')?'limit_except':body.split(' ')[0];assert.deepEqual(m.diagnoseAbbottNginxText(base(body)),[name]);assert.throws(()=>m.validateAbbottNginxText(base(body)));assert.deepEqual(m.diagnoseAbbottNginxText(base(body+' location ~ /x { root /secret; }')),{reason:'parser_ambiguity'});}assert.deepEqual(m.diagnoseAbbottNginxText(base('private_block { sendfile on; }')),['other']);});
test('batch diagnosis uses shared selected TLS parser and fixed sorted unique names only',async()=>{
 const m=await api();assert.equal(typeof m.diagnoseAbbottNginxText,'function');
 const text=base('sendfile on; tcp_nopush on; location / { proxy_hide_header "private-token"; proxy_redirect off; sendfile off; private_token "https://private.invalid/secret"; }');
 assert.deepEqual(m.diagnoseAbbottNginxText(text),['other','proxy_hide_header','proxy_redirect','sendfile','tcp_nopush']);
 assert.deepEqual(m.diagnoseAbbottNginxText(base('location / { proxy_pass http://127.0.0.1:3001; }')),[]);
 assert.deepEqual(m.diagnoseAbbottNginxText(base('location / { proxy_pass http://127.0.0.1:3001; }').replace('return 301','sendfile on; return 301')),[]);
});
test('batch diagnosis fails closed with no partial result for ambiguous TLS or unproven nesting',async()=>{
 const m=await api();assert.equal(typeof m.diagnoseAbbottNginxText,'function');
 for(const text of [base('sendfile on; location ~* /private { root /secret; }'),base('sendfile on; location / { server { listen 443 ssl; } }'),base('sendfile on;')+'server { listen 443; server_name dashboards.adreports.ru; }',base('sendfile on;')+'}',base('sendfile on;').replace('443 ssl','80')])assert.deepEqual(m.diagnoseAbbottNginxText(text),{reason:'parser_ambiguity'});
});
test('batch diagnostic ignores names in arguments and comments and keeps strict acceptance unchanged',async()=>{
 const m=await api();assert.equal(typeof m.validateAbbottNginxText,'function');
 const text=base('private_token "sendfile root https://private.invalid/secret"; # proxy_redirect private\nlocation / { proxy_pass http://127.0.0.1:3001; }');
 assert.deepEqual(m.diagnoseAbbottNginxText(text),['other']);assert.throws(()=>m.validateAbbottNginxText(text));
 assert.throws(()=>m.validateAbbottNginxText(base('sendfile on;')));
 assert.doesNotThrow(()=>m.validateAbbottNginxText(base('location / { proxy_pass http://127.0.0.1:3001; }')));
 assert.doesNotMatch(JSON.stringify(m.diagnoseAbbottNginxText(text)),/private|secret|https/);
});
test('fixed reader only opens stable nofollow config, clears bounded buffers and refuses drift',async()=>{
 const m=await import('./abbott-nginx-readonly.mjs').catch(()=>({}));assert.equal(typeof m.readAbbottNginxNames,'function');
 const file='/etc/nginx/conf.d/dashboard-next.conf',content=Buffer.from(base('sendfile on;')),buffers=[],opened=[];let closed=0;
 const stat=p=>({dev:1,ino:2,uid:0,gid:0,nlink:1,mode:p===file?0o100644:0o40755,size:p===file?content.length:0,mtimeMs:1,ctimeMs:1,isFile:()=>p===file,isDirectory:()=>p!==file,isSymbolicLink:()=>false});
 const io={constants:fs.constants,lstatSync:stat,realpathSync:p=>p,openSync(p,flags){assert.equal(p,file);assert.equal(flags,fs.constants.O_RDONLY|fs.constants.O_NOFOLLOW);opened.push(p);return 3;},fstatSync:()=>stat(file),readSync(fd,b,o,l,p){buffers.push(b);return content.copy(b,o,p,p+l);},closeSync(){closed++;}};
 assert.deepEqual(m.readAbbottNginxNames({io,hostname:()=> 'ybjqbzojln',getuid:()=>0}),{rejection:'selected_sendfile'});assert.equal(closed,1);assert.equal(opened.length,1);assert.ok(buffers.every(b=>b.every(v=>v===0)));
 for(const mode of ['owner','symlink','mode','size','drift','host']){let calls=0;const mutated={...io,lstatSync(p){const s=stat(p);if(p===file){if(mode==='owner')s.uid=1;if(mode==='symlink')s.isSymbolicLink=()=>true;if(mode==='mode')s.mode=0o100666;if(mode==='size')s.size=1048577;if(mode==='drift'&&++calls>1)s.ino++;}return s;}};assert.deepEqual(m.readAbbottNginxNames({io:mutated,hostname:()=>mode==='host'?'private-token':'ybjqbzojln',getuid:()=>0}),{reason:mode==='host'?'remote_authority':'metadata'});}
 const invalidUtf8={...io,readSync(fd,b,o,l,p){const n=io.readSync(fd,b,o,l,p);if(p===0)b[0]=255;return n;}};assert.deepEqual(m.readAbbottNginxNames({io:invalidUtf8,hostname:()=> 'ybjqbzojln',getuid:()=>0}),{reason:'utf8'});
 assert.deepEqual(m.readAbbottNginxNames({io:{...io,closeSync(){throw Error('private-secret');}},hostname:()=> 'ybjqbzojln',getuid:()=>0}),{reason:'cleanup'});
});
test('differential strict deployment acceptance stays identical to reviewed b273294 parser',async()=>{
 const m=await api(),source=execFileSync('/usr/bin/git',['show','b27329424965540b8b6338d9dff682078db5d55f:scripts/runtime-release-remote.mjs'],{cwd:new URL('..',import.meta.url),env:{PATH:'/usr/bin:/bin'},encoding:'utf8',stdio:['ignore','pipe','pipe']}),start=source.indexOf('  function nginxSanity(text){'),end=source.indexOf('  function listenerTable()',start);assert.ok(start>0&&end>start);
 const originalNotes=[],original=vm.runInNewContext(source.slice(start,end)+'\nnginxSanity',{path,nginxReason:code=>originalNotes.push(code),fail(){throw Error('REFUSED');}}),accept=(fn,text)=>{try{fn(text);return true;}catch{return false;}};
 const bodies=['location / { proxy_pass http://127.0.0.1:3001; }','sendfile on;','include /private;','location ~ /x { return 404; }','if ($x) { return 404; }','server { listen 443 ssl; }','location / { add_header Location /x; }','location / { proxy_pass http://$private; }','set $x private;'];
 for(const id of ['18','018','0x12','0b10010','1.8e1','+18','abbott','AbBoTt','19','%31%38',' 18 ','18/../19'])for(const directive of ['location = /dashboard/ID { return 404; }','location /api/dashboard/ID { return 404; }','location = /status { proxy_pass http://127.0.0.1:3001/dashboard/ID; }'])bodies.push(directive.replace('ID',id));
 let comparisons=0;for(const body of bodies)for(const variant of [base(body),base(body).replace('443 ssl','443'),base(body)+'server { listen 443; server_name dashboards.adreports.ru; }',base(body)+'# private-token\n',base(body)+'}',base(body).replace('alias.example dashboards.adreports.ru','dashboards.adreports.ru alias.example')]){const actualNotes=[];originalNotes.length=0;assert.equal(accept(text=>m.validateAbbottNginxText(text,code=>actualNotes.push(code)),variant),accept(original,variant));assert.deepEqual(actualNotes,originalNotes);comparisons++;}assert.equal(comparisons,270);for(const name of ['upstream','map','geo','split_clients','log_format','proxy_cache_path','limit_req_zone','limit_conn_zone','private_token']){const text=name+' private_value { hidden value; }'+base('sendfile on;'),actualNotes=[];originalNotes.length=0;assert.equal(accept(text=>m.validateAbbottNginxText(text,code=>actualNotes.push(code)),text),accept(original,text));assert.deepEqual(actualNotes,originalNotes);}
 const declarations=[zone,zone.replace('10r/s','30r/m'),zone.replace('10m','65536'),zone+'limit_req_zone $server_name zone=perhost:10m rate=1r/s;'];let safeDeltas=0;for(const declaration of declarations)for(const body of ['', 'limit_req zone=perip;', 'location / { limit_req zone=perip burst=1 nodelay; }','location / { limit_req zone=perip burst=5 delay=1; }']){const text=declaration+base(body);assert.equal(accept(original,text),false);assert.equal(accept(m.validateAbbottNginxText,text),true);safeDeltas++;}assert.equal(safeDeltas,16);
 const inactiveBodies=['limit_req zone=missing;','limit_req zone=$private burst=-1;','limit_req_zone $binary_remote_addr zone=inactive:10m rate=1r/s;','limit_req_zone key zone=inactive:1k rate=bad;','limit_req zone=missing { return 404; }','limit_req_zone key { hidden value; }','if ($host) { limit_req zone=missing; }','location /nested { limit_req zone=missing; }'];let inactiveCases=0;for(const body of inactiveBodies)for(const text of [base('').replace('return 301',body+' return 301'),base('').replace('return 301','if ($host) { '+body+' } return 301'),base('').replace('return 301','location /inactive { '+body+' } return 301'),base('')+'server { listen 80; server_name unrelated.example; '+body+' }',base('')+'server { listen 443 ssl; server_name unrelated.example; '+body+' }',base('')+'server { listen 443 ssl; server_name unrelated.example; location / { '+body+' } }']){const actualNotes=[];originalNotes.length=0;assert.equal(accept(text=>m.validateAbbottNginxText(text,code=>actualNotes.push(code)),text),accept(original,text));assert.deepEqual(actualNotes,originalNotes);inactiveCases++;}assert.equal(inactiveCases,48);
});

test('any unsupported block name is enum mapped without inspecting contents',async()=>{const m=await api();for(const [directive,expected] of [['map',['map']],['sendfile',['sendfile']],['private_block',['other']]])for(const location of [false,true]){const block=directive+' "private-token" { root /private; secret_child "https://secret.invalid/token"; }',body=location?'location / { '+block+' }':block;const result=m.diagnoseAbbottNginxText(base(body));assert.deepEqual(result,expected);assert.doesNotMatch(JSON.stringify(result),/private|secret|https|root/);assert.throws(()=>m.validateAbbottNginxText(base(body)));}});
test('later structural ambiguity discards arbitrary block inventory and authority blocks remain refused',async()=>{const m=await api();for(const tail of ['location ~ /x { return 404; }','location / { server { listen 443 ssl; } }','location / { location /nested { return 404; } }','location / { proxy_pass http://127.0.0.1:3004; }','}']){const text=base('private_block { secret value; } sendfile { hidden value; } '+tail);assert.deepEqual(m.diagnoseAbbottNginxText(text),{reason:'parser_ambiguity'});}assert.deepEqual(m.diagnoseAbbottNginxText(base('server { listen 443 ssl; }')),{reason:'parser_ambiguity'});assert.deepEqual(m.diagnoseAbbottNginxText(base('sendfile on;').replace('return 301','private_block { hidden value; } return 301')),{reason:'parser_ambiguity'});});

test('explicit zero delay is invalid even though omitted delay defaults to zero',async()=>{const m=await api();assert.throws(()=>m.validateAbbottNginxText(zone+base('limit_req zone=perip delay=0;')));assert.doesNotThrow(()=>m.validateAbbottNginxText(zone+base('limit_req zone=perip;')));});
