import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import os from'node:os';import path from'node:path';
const api=()=>import('./abbott-deploy-evidence.mjs').catch(()=>({}));
async function fixture(fn){const m=await api();assert.equal(typeof m.createDeployEvidence,'function');const temp=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'abbott-evidence-test-'))),root=path.join(temp,'evidence');const fixed=m.DEPLOY_EVIDENCE_DIRECTORY;const map=x=>typeof x==='string'&&x.startsWith(fixed)?root+x.slice(fixed.length):x;
 const filesystem=new Proxy(fs,{get(target,k){if(k==='realpathSync')return p=>{const real=fs.realpathSync(map(p));return real===root?fixed:real;};if(typeof target[k]==='function')return(...args)=>target[k](...args.map(map));return target[k];}});
 try{await fn(m,filesystem,root);}finally{fs.rmSync(temp,{recursive:true,force:true});}
}
const row={pid:12345,start:'Tue Sep 15 05:12:00 2026',exit:false,exitVerified:false,stage:'identity_proof'};
test('private evidence atomically records identity only then copies no-PID summary before removal',()=>fixture((m,f,root)=>{const e=m.createDeployEvidence(f);e.record(row);assert.equal(fs.statSync(root).mode&0o7777,0o700);assert.equal(fs.statSync(root+'/identity.json').mode&0o7777,0o600);assert.deepEqual(JSON.parse(fs.readFileSync(root+'/identity.json')),row);e.record({...row,exit:true,exitVerified:true,stage:'complete'});assert.deepEqual(e.finish(),{identityCaptured:true,exitObserved:true,exitVerified:true});assert.equal(fs.existsSync(root),false);}));
test('evidence rejects arbitrary keys, secret-bearing start/stage, metadata drift and links without replacing prior file',()=>fixture((m,f,root)=>{const e=m.createDeployEvidence(f);e.record(row);const prior=fs.readFileSync(root+'/identity.json');for(const bad of[{...row,secret:'private'},{...row,start:'private token'},{...row,stage:'private'}])assert.throws(()=>e.record(bad),/^Error: ABBOTT_DEPLOY_EVIDENCE_REFUSED$/);assert.ok(fs.readFileSync(root+'/identity.json').equals(prior));fs.linkSync(root+'/identity.json',root+'/other');assert.throws(()=>e.record(row),/^Error: ABBOTT_DEPLOY_EVIDENCE_REFUSED$/);fs.unlinkSync(root+'/other');fs.chmodSync(root+'/identity.json',0o644);assert.throws(()=>e.finish(),/^Error: ABBOTT_DEPLOY_EVIDENCE_REFUSED$/);}));
test('preexisting directory or symlink refuses before any evidence publication',()=>fixture((m,f,root)=>{fs.mkdirSync(root);assert.throws(()=>m.createDeployEvidence(f),/^Error: ABBOTT_DEPLOY_EVIDENCE_REFUSED$/);fs.rmdirSync(root);fs.symlinkSync(path.dirname(root),root);assert.throws(()=>m.createDeployEvidence(f),/^Error: ABBOTT_DEPLOY_EVIDENCE_REFUSED$/);}));
test('interrupted atomic write leaves prior evidence unchanged and removes only its owned temporary file',()=>fixture((m,f,root)=>{let interrupted=false;const platform=new Proxy(f,{get(target,k){if(k==='writeFileSync')return(...args)=>{if(interrupted)throw Error('private disk failure');return target[k](...args);};return target[k];}});const e=m.createDeployEvidence(platform);e.record(row);const before=fs.readFileSync(root+'/identity.json');interrupted=true;assert.throws(()=>e.record({...row,exit:true}),/^Error: ABBOTT_DEPLOY_EVIDENCE_REFUSED$/);assert.ok(before.equals(fs.readFileSync(root+'/identity.json')));assert.equal(fs.existsSync(root+'/identity.json.next'),false);assert.equal(e.finish().exitVerified,false);}));
