import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import path from'node:path';import vm from'node:vm';import{execFileSync}from'node:child_process';
const api=()=>import('./runtime-release-remote.mjs');
const base=body=>'server { listen 80; server_name dashboards.adreports.ru alias.example; return 301 https://$host$request_uri; }\nserver { listen 443 ssl; server_name alias.example dashboards.adreports.ru; '+body+' }\n';
test('first deployment rejection reports top-level fixed context names before TLS selection',async()=>{const m=await api();assert.equal(typeof m.classifyAbbottNginxFirstRejection,'function');for(const name of ['upstream','map','geo','split_clients','log_format','proxy_cache_path','limit_req_zone','limit_conn_zone','private_token'])for(const ending of [';',' { secret_child private_value; }']){const text=name+' private_value'+ending+base('sendfile on;');assert.deepEqual(m.classifyAbbottNginxFirstRejection(text),{rejection:'top_'+(name==='private_token'?'other':name)});assert.throws(()=>m.validateAbbottNginxText(text));}});
test('top upstream server leaf is not a nested TLS authority block',async()=>{const m=await api();assert.deepEqual(m.classifyAbbottNginxFirstRejection('upstream private_name { server 127.0.0.1:3001; }'+base('')),{rejection:'top_upstream'});assert.deepEqual(m.classifyAbbottNginxFirstRejection('upstream private_name { server { listen 443 ssl; } }'+base('')),{reason:'parser_ambiguity'});});
test('first rejection never continues past selected unsupported node or returns partial inventory',async()=>{const m=await api();assert.equal(typeof m.classifyAbbottNginxFirstRejection,'function');for(const [body,code]of [['sendfile on; root /secret;','selected_sendfile'],['private_token value;','selected_other'],['location / { proxy_redirect off; }','selected_proxy_redirect'],['map private { hidden value; }','selected_map']]){const result=m.classifyAbbottNginxFirstRejection(base(body+' location ~ /later { root /secret; }'));assert.deepEqual(result,{rejection:code});assert.doesNotMatch(JSON.stringify(result),/private|secret|later|root/);}assert.deepEqual(m.classifyAbbottNginxFirstRejection(base('location / { proxy_pass http://127.0.0.1:3001; }')),{rejection:'none'});});
test('first rejection retains syntax and TLS ambiguity instead of inventing directive names',async()=>{const m=await api();assert.equal(typeof m.classifyAbbottNginxFirstRejection,'function');for(const text of ['upstream x {',base('sendfile on;')+'server { listen 443; server_name dashboards.adreports.ru; }',base('location ~ /x { root /secret; }'),'upstream x { server { listen 443 ssl; } }'+base(''),'server value;'+base('')])assert.deepEqual(m.classifyAbbottNginxFirstRejection(text),{reason:'parser_ambiguity'});});
test('unknown directive is successful analysis, ambiguity is a separate closed refusal',async()=>{const m=await api();assert.deepEqual(m.diagnoseAbbottNginxText(base('private_secret value;')),['other']);for(const text of [base('sendfile on; location ~ /x { root /secret; }'),base('sendfile on;')+'}',base('sendfile on;')+'server { listen 443; server_name dashboards.adreports.ru; }'])assert.deepEqual(m.diagnoseAbbottNginxText(text),{reason:'parser_ambiguity'});});
test('known opaque block names are diagnosed but never traversed or accepted by deploy',async()=>{const m=await api();for(const body of ['if ($secret) { secret_nested value; }','types { private_nested secret; }','location / { limit_except GET { private_nested secret; } }']){const name=body.startsWith('location')?'limit_except':body.split(' ')[0];assert.deepEqual(m.diagnoseAbbottNginxText(base(body)),[name]);assert.throws(()=>m.validateAbbottNginxText(base(body)));assert.deepEqual(m.diagnoseAbbottNginxText(base(body+' location ~ /x { root /secret; }')),{reason:'parser_ambiguity'});}assert.deepEqual(m.diagnoseAbbottNginxText(base('private_block { sendfile on; }')),['other']);});
test('batch diagnosis uses shared selected TLS parser and fixed sorted unique names only',async()=>{
 const m=await api();assert.equal(typeof m.diagnoseAbbottNginxText,'function');
 const text=base('sendfile on; tcp_nopush on; location / { proxy_hide_header "private-token"; proxy_redirect off; sendfile off; private_token "https://private.invalid/secret"; }');
 assert.deepEqual(m.diagnoseAbbottNginxText(text),['other','proxy_hide_header','proxy_redirect','sendfile','tcp_nopush']);
 assert.deepEqual(m.diagnoseAbbottNginxText(base('location / { proxy_pass http://127.0.0.1:3001; }')),[]);
 assert.deepEqual(m.diagnoseAbbottNginxText(base('location / { proxy_pass http://127.0.0.1:3001; }').replace('return 301','sendfile on; return 301')),[]);
});
test('batch diagnosis fails closed with no partial result for ambiguous TLS or unproven nesting',async()=>{
 const m=await api();assert.equal(typeof m.diagnoseAbbottNginxText,'function');
 for(const text of [base('sendfile on; location ~* /private { root /secret; }'),base('sendfile on; location / { server { listen 443 ssl; } }'),base('sendfile on;')+'server { listen 443; server_name dashboards.adreports.ru; }',base('sendfile on;')+'}',base('sendfile on;').replace('443 ssl','80')])assert.deepEqual(m.diagnoseAbbottNginxText(text),{reason:'parser_ambiguity'});
});
test('batch diagnostic ignores names in arguments and comments and keeps strict acceptance unchanged',async()=>{
 const m=await api();assert.equal(typeof m.validateAbbottNginxText,'function');
 const text=base('private_token "sendfile root https://private.invalid/secret"; # proxy_redirect private\nlocation / { proxy_pass http://127.0.0.1:3001; }');
 assert.deepEqual(m.diagnoseAbbottNginxText(text),['other']);assert.throws(()=>m.validateAbbottNginxText(text));
 assert.throws(()=>m.validateAbbottNginxText(base('sendfile on;')));
 assert.doesNotThrow(()=>m.validateAbbottNginxText(base('location / { proxy_pass http://127.0.0.1:3001; }')));
 assert.doesNotMatch(JSON.stringify(m.diagnoseAbbottNginxText(text)),/private|secret|https/);
});
test('fixed reader only opens stable nofollow config, clears bounded buffers and refuses drift',async()=>{
 const m=await import('./abbott-nginx-readonly.mjs').catch(()=>({}));assert.equal(typeof m.readAbbottNginxNames,'function');
 const file='/etc/nginx/conf.d/dashboard-next.conf',content=Buffer.from(base('sendfile on;')),buffers=[],opened=[];let closed=0;
 const stat=p=>({dev:1,ino:2,uid:0,gid:0,nlink:1,mode:p===file?0o100644:0o40755,size:p===file?content.length:0,mtimeMs:1,ctimeMs:1,isFile:()=>p===file,isDirectory:()=>p!==file,isSymbolicLink:()=>false});
 const io={constants:fs.constants,lstatSync:stat,realpathSync:p=>p,openSync(p,flags){assert.equal(p,file);assert.equal(flags,fs.constants.O_RDONLY|fs.constants.O_NOFOLLOW);opened.push(p);return 3;},fstatSync:()=>stat(file),readSync(fd,b,o,l,p){buffers.push(b);return content.copy(b,o,p,p+l);},closeSync(){closed++;}};
 assert.deepEqual(m.readAbbottNginxNames({io,hostname:()=> 'ybjqbzojln',getuid:()=>0}),{rejection:'selected_sendfile'});assert.equal(closed,1);assert.equal(opened.length,1);assert.ok(buffers.every(b=>b.every(v=>v===0)));
 for(const mode of ['owner','symlink','mode','size','drift','host']){let calls=0;const mutated={...io,lstatSync(p){const s=stat(p);if(p===file){if(mode==='owner')s.uid=1;if(mode==='symlink')s.isSymbolicLink=()=>true;if(mode==='mode')s.mode=0o100666;if(mode==='size')s.size=1048577;if(mode==='drift'&&++calls>1)s.ino++;}return s;}};assert.deepEqual(m.readAbbottNginxNames({io:mutated,hostname:()=>mode==='host'?'private-token':'ybjqbzojln',getuid:()=>0}),{reason:mode==='host'?'remote_authority':'metadata'});}
 const invalidUtf8={...io,readSync(fd,b,o,l,p){const n=io.readSync(fd,b,o,l,p);if(p===0)b[0]=255;return n;}};assert.deepEqual(m.readAbbottNginxNames({io:invalidUtf8,hostname:()=> 'ybjqbzojln',getuid:()=>0}),{reason:'utf8'});
 assert.deepEqual(m.readAbbottNginxNames({io:{...io,closeSync(){throw Error('private-secret');}},hostname:()=> 'ybjqbzojln',getuid:()=>0}),{reason:'cleanup'});
});
test('differential strict deployment acceptance stays identical to reviewed b273294 parser',async()=>{
 const m=await api(),source=execFileSync('/usr/bin/git',['show','b27329424965540b8b6338d9dff682078db5d55f:scripts/runtime-release-remote.mjs'],{cwd:new URL('..',import.meta.url),env:{PATH:'/usr/bin:/bin'},encoding:'utf8',stdio:['ignore','pipe','pipe']}),start=source.indexOf('  function nginxSanity(text){'),end=source.indexOf('  function listenerTable()',start);assert.ok(start>0&&end>start);
 const originalNotes=[],original=vm.runInNewContext(source.slice(start,end)+'\nnginxSanity',{path,nginxReason:code=>originalNotes.push(code),fail(){throw Error('REFUSED');}}),accept=(fn,text)=>{try{fn(text);return true;}catch{return false;}};
 const bodies=['location / { proxy_pass http://127.0.0.1:3001; }','sendfile on;','include /private;','location ~ /x { return 404; }','if ($x) { return 404; }','server { listen 443 ssl; }','location / { add_header Location /x; }','location / { proxy_pass http://$private; }','set $x private;'];
 for(const id of ['18','018','0x12','0b10010','1.8e1','+18','abbott','AbBoTt','19','%31%38',' 18 ','18/../19'])for(const directive of ['location = /dashboard/ID { return 404; }','location /api/dashboard/ID { return 404; }','location = /status { proxy_pass http://127.0.0.1:3001/dashboard/ID; }'])bodies.push(directive.replace('ID',id));
 let comparisons=0;for(const body of bodies)for(const variant of [base(body),base(body).replace('443 ssl','443'),base(body)+'server { listen 443; server_name dashboards.adreports.ru; }',base(body)+'# private-token\n',base(body)+'}',base(body).replace('alias.example dashboards.adreports.ru','dashboards.adreports.ru alias.example')]){const actualNotes=[];originalNotes.length=0;assert.equal(accept(text=>m.validateAbbottNginxText(text,code=>actualNotes.push(code)),variant),accept(original,variant));assert.deepEqual(actualNotes,originalNotes);comparisons++;}assert.equal(comparisons,270);for(const name of ['upstream','map','geo','split_clients','log_format','proxy_cache_path','limit_req_zone','limit_conn_zone','private_token']){const text=name+' private_value { hidden value; }'+base('sendfile on;'),actualNotes=[];originalNotes.length=0;assert.equal(accept(text=>m.validateAbbottNginxText(text,code=>actualNotes.push(code)),text),accept(original,text));assert.deepEqual(actualNotes,originalNotes);}
});

test('any unsupported block name is enum mapped without inspecting contents',async()=>{const m=await api();for(const [directive,expected] of [['map',['map']],['sendfile',['sendfile']],['private_block',['other']]])for(const location of [false,true]){const block=directive+' "private-token" { root /private; secret_child "https://secret.invalid/token"; }',body=location?'location / { '+block+' }':block;const result=m.diagnoseAbbottNginxText(base(body));assert.deepEqual(result,expected);assert.doesNotMatch(JSON.stringify(result),/private|secret|https|root/);assert.throws(()=>m.validateAbbottNginxText(base(body)));}});
test('later structural ambiguity discards arbitrary block inventory and authority blocks remain refused',async()=>{const m=await api();for(const tail of ['location ~ /x { return 404; }','location / { server { listen 443 ssl; } }','location / { location /nested { return 404; } }','location / { proxy_pass http://127.0.0.1:3004; }','}']){const text=base('private_block { secret value; } sendfile { hidden value; } '+tail);assert.deepEqual(m.diagnoseAbbottNginxText(text),{reason:'parser_ambiguity'});}assert.deepEqual(m.diagnoseAbbottNginxText(base('server { listen 443 ssl; }')),{reason:'parser_ambiguity'});assert.deepEqual(m.diagnoseAbbottNginxText(base('sendfile on;').replace('return 301','private_block { hidden value; } return 301')),{reason:'parser_ambiguity'});});
