import test from'node:test';import assert from'node:assert/strict';import{EventEmitter}from'node:events';import{PassThrough}from'node:stream';import{spawn}from'node:child_process';import{createHash}from'node:crypto';
const api=()=>import('./abbott-recovery-transport.mjs').catch(()=>({}));
test('startup warnings remain fatal; fragmented or oversized stderr produces only closed categories',async()=>{const m=await api();for(const mode of['warning','fragmented','oversized']){const f=fixture(false),sent=[];f.child.stdin.on('data',b=>sent.push(b));const result=m.runRecoveryTransport(Buffer.from('private'),{platform:f.platform});if(mode==='fragmented'){f.child.stderr.write('(node:123) Experi');f.child.stderr.write('mentalWarning: private token\n');}else f.child.stderr.write('Warning: private token\n');if(mode==='oversized')f.child.stderr.write('private'.repeat(2000));f.child.stdout.write('ABBOTT_RECOVERY_READY\n');f.child.stdout.write('ABBOTT_RECOVERY_ACK RESTORED complete none\n');f.close();const r=await result;assert.equal(r.remoteAcknowledged,false);assert.equal(sent.length,0);assert.deepEqual(r.diagnostic,{stage:'remote_startup',reason:mode==='oversized'?'unknown':mode==='fragmented'?'node_warning':'ssh_warning'});assert.doesNotMatch(JSON.stringify(r.diagnostic),/private|token|123/);}});
test('READY cannot release a frame after identity replacement or abort',async()=>{const m=await api();for(const mode of['replacement','abort']){const f=fixture(false),abort=new AbortController(),sent=[];f.child.stdin.on('data',b=>sent.push(b));const result=m.runRecoveryTransport(Buffer.from('private'),{platform:f.platform,signal:abort.signal});if(mode==='replacement')f.replace();else abort.abort();f.child.stdout.write('ABBOTT_RECOVERY_READY\n');f.close();assert.equal((await result).remoteAcknowledged,false);assert.equal(sent.length,0);}});
test('no source or RUN before exact READY and identity; fragmented READY releases one frame only',async()=>{const m=await api(),f=fixture(false),input=[];f.child.stdin.on('data',b=>input.push(b.toString()));const result=m.runRecoveryTransport(Buffer.from('fixture'),{platform:f.platform});assert.equal(input.length,0);f.child.stdout.write('ABBOTT_RECOVERY_');assert.equal(input.length,0);f.child.stdout.write('READY\n');assert.match(input.join(''),/^ABBOTT_RECOVERY_SOURCE /);assert.equal(input.join('').split('RUN\n').length-1,1);f.child.stdout.write('ABBOTT_RECOVERY_ACK RESTORED complete none\n');f.close();assert.equal((await result).remoteAcknowledged,true);});
test('missing forged duplicate READY or startup stderr never sends RUN and cannot acknowledge success',async()=>{const m=await api();for(const mode of['missing','forged','stderr','duplicate']){const f=fixture(false),input=[];f.child.stdin.on('data',b=>input.push(b.toString()));const result=m.runRecoveryTransport(Buffer.from('fixture'),{platform:f.platform});if(mode==='forged')f.child.stdout.write('private READY token\n');if(mode==='stderr')f.child.stderr.write('private warning');if(mode==='duplicate')f.child.stdout.write('ABBOTT_RECOVERY_READY\nABBOTT_RECOVERY_READY\n');else f.child.stdout.write('ABBOTT_RECOVERY_ACK RESTORED complete none\n');f.close();assert.equal((await result).remoteAcknowledged,false);assert.equal(input.join('').includes('RUN\n'),false,mode);}});
test('transport failures distinguish safe stages without copying arbitrary exception fields',async()=>{
 const m=await api();for(const mode of['spawn','identity','source','run','stderr','frame','missing','timeout','nonzero']){
  const f=fixture(),expected={spawn:['local_spawn','failed'],identity:['identity_proof','unavailable'],source:['source_write','failed'],run:['run_write','failed'],stderr:['remote_startup','unknown'],frame:['ack_framing','malformed'],missing:['ack_framing','missing'],timeout:['timeout','deadline'],nonzero:['ssh_close','nonzero']}[mode];
  if(mode==='spawn')f.platform.spawn=()=>{throw Error('private password host /path 123');};
  if(mode==='identity')f.platform.identity=()=>{throw Error('private');};
  const write=f.child.stdin.write.bind(f.child.stdin);if(['source','run'].includes(mode))f.child.stdin.write=(b,...rest)=>{if(mode==='source'&&Buffer.isBuffer(b)||mode==='run'&&b==='RUN\n')throw Error('private');return write(b,...rest);};
  const result=m.runRecoveryTransport(Buffer.from('fixture'),{platform:f.platform});
  if(mode==='stderr')f.child.stderr.write('secret private token');if(mode==='frame')f.child.stdout.write('secret forged stage=source_write');
  if(mode==='timeout'){f.timers[0]();f.timers[1]();}else if(mode==='nonzero'){f.platform.identity=()=>null;f.child.emit('close',1,null);}else if(mode!=='spawn')f.close();
  const r=await result;assert.deepEqual(r.diagnostic,{stage:expected[0],reason:expected[1]},mode);assert.doesNotMatch(JSON.stringify(r.diagnostic),/private|secret|token|123/);
 }
});
test('identity evidence is captured before first source write and failure keeps cleanup active',async()=>{
 const m=await api(),f=fixture(),events=[];const write=f.child.stdin.write.bind(f.child.stdin);f.child.stdin.write=(b,...rest)=>{assert.ok(events.some(x=>x.pid===90001&&x.start==='owned-start'));return write(b,...rest);};
 const result=m.runRecoveryTransport(Buffer.from('fixture'),{platform:f.platform,onEvidence:e=>events.push(e)});assert.ok(events.some(x=>x.pid===90001&&x.start===null));f.close();const r=await result;assert.equal(events.at(-1).exitVerified,true);assert.equal(events.at(-1).exit,true);assert.equal(r.sshExitVerified,true);
 const g=fixture();const failure=m.runRecoveryTransport(Buffer.from('fixture'),{platform:g.platform,onEvidence(){throw Error('private');}});assert.equal(g.child.stdin.writableEnded,true);assert.equal(g.cleared.length,0);g.close();assert.deepEqual((await failure).diagnostic,{stage:'local_evidence',reason:'failed'});
});
function fixture(automaticReady=true){const child=new EventEmitter();Object.assign(child,{pid:90001,exitCode:null,signalCode:null,stdin:new PassThrough(),stdout:new PassThrough(),stderr:new PassThrough()});const calls=[],timers=[],cleared=[];let live=true,sentReady=false;
  const platform={spawn(binary,args,options){calls.push({binary,args,options});return child;},identity:()=>{if(automaticReady&&!sentReady&&live){sentReady=true;child.stdout.write('ABBOTT_RECOVERY_READY\n');}return live?'owned-start':null;},kill(pid,signal){calls.push({pid,signal});if(signal==='SIGKILL'){live=false;child.signalCode=signal;child.emit('close',null,signal);}},setTimeout(fn){timers.push(fn);return fn;},clearTimeout(t){cleared.push(t);}};
  return{child,calls,timers,cleared,platform,close(){live=false;child.exitCode=0;child.emit('close',0,null);},replace(){platform.identity=()=> 'other-start';}};
}
test('fixed recovery transport retains control stdin, sends abort, accepts only exact ack and verifies SSH exit',async()=>{const m=await api();assert.equal(typeof m.runRecoveryTransport,'function');const f=fixture(),abort=new AbortController(),input=[];f.child.stdin.on('data',b=>input.push(b.toString()));const result=m.runRecoveryTransport(Buffer.from('export async function run(){}'),{signal:abort.signal,platform:f.platform});abort.abort();f.child.stdout.write('ABBOTT_RECOVERY_ACK REVIEW_REQUIRED remote_recovery review_required\n');f.close();assert.deepEqual(await result,{status:'ABBOTT_RECOVERY_REVIEW_REQUIRED',remoteAcknowledged:true,sshExitVerified:true,pid:90001,start:'owned-start',diagnostic:{stage:'remote_recovery',reason:'review_required'}});assert.match(input.join(''),/^ABBOTT_RECOVERY_SOURCE \d+ [a-f0-9]{64}\n/);assert.match(input.join(''),/RUN\nABORT\n$/);assert.equal(f.child.stdin.writableEnded,false);assert.equal(f.calls[0].binary,'/usr/bin/ssh');assert.ok(f.calls[0].args.includes('ProxyCommand=none'));assert.ok(f.calls[0].args.includes('IdentityAgent=none'));assert.ok(f.calls[0].args.includes('/Users/nafanya/.ssh/beget_ed25519'));});
test('forged oversized secret stderr or late stdout never become acknowledged output',async()=>{const m=await api();for(const mode of['forged','oversized','stderr','late']){const f=fixture(),result=m.runRecoveryTransport(Buffer.from('fixture'),{platform:f.platform});if(mode==='forged')f.child.stdout.write('private token=secret');if(mode==='oversized')f.child.stdout.write('secret'.repeat(300));if(mode==='stderr')f.child.stderr.write('private headers body token');if(mode==='late'){f.child.stdout.write('ABBOTT_RECOVERY_ACK RESTORED complete none\n');f.child.stdout.write('secret');}f.close();const r=await result;assert.equal(r.remoteAcknowledged,false);assert.equal(r.status,'ABBOTT_RECOVERY_UNACKNOWLEDGED');assert.doesNotMatch(JSON.stringify(r),/secret|headers|token/);}});
test('hung SSH receives bounded identity-checked TERM/KILL; missing ack is never cleanup success',async()=>{const m=await api(),f=fixture(),result=m.runRecoveryTransport(Buffer.from('fixture'),{platform:f.platform});f.timers[0]();f.timers[1]();const r=await result;assert.equal(r.status,'ABBOTT_RECOVERY_UNACKNOWLEDGED');assert.equal(r.sshExitVerified,true);assert.deepEqual(f.calls.filter(c=>c.signal),[{pid:90001,signal:'SIGTERM'},{pid:90001,signal:'SIGKILL'}]);});
test('PID replacement refuses termination and observes the full cleanup budget before reporting unverified exit',async()=>{const m=await api(),f=fixture();let settled=false;const result=m.runRecoveryTransport(Buffer.from('fixture'),{platform:f.platform}).then(r=>{settled=true;return r;});f.replace();f.timers[0]();await Promise.resolve();assert.equal(settled,false);assert.equal(f.cleared.length,0);f.timers[1]();f.timers[2]();const r=await result;assert.equal(r.sshExitVerified,false);assert.equal(r.remoteAcknowledged,false);assert.equal(f.calls.filter(c=>c.signal).length,0);assert.equal(f.cleared.length,0);});
for(const mode of['timeout','error','unavailable'])test(`initial identity ${mode} retains listeners/deadlines, sends only EOF and reaps late close`,async()=>{
  const m=await api(),f=fixture(),identity=f.platform.identity;let calls=0,settled=false;const sent=[];f.child.stdin.on('data',b=>sent.push(Buffer.from(b)));
  f.platform.identity=()=>{calls++;if(calls===1){assert.ok(f.child.listenerCount('close'));assert.ok(f.child.stdout.listenerCount('data'));assert.ok(f.child.stderr.listenerCount('data'));assert.ok(f.timers.length>=3);if(mode==='unavailable')return null;throw Object.assign(Error('private identity failure'),{code:mode==='timeout'?'ETIMEDOUT':'EIO'});}return identity();};
  const result=m.runRecoveryTransport(Buffer.from('private source'),{platform:f.platform}).then(r=>{settled=true;return r;});await Promise.resolve();assert.equal(settled,false);assert.equal(f.child.stdin.writableEnded,true);assert.equal(Buffer.concat(sent).length,0);assert.equal(f.cleared.length,0);
  f.child.stderr.write('private child stderr');f.child.stdout.write('private child stdout');f.close();const r=await result;assert.equal(r.status,'ABBOTT_RECOVERY_UNACKNOWLEDGED');assert.equal(r.sshExitVerified,true);assert.doesNotMatch(JSON.stringify(r),/private/);assert.ok(f.cleared.length>=3);
});
test('post-spawn shared setup throw retains bounded cleanup and does not transmit source',async()=>{const m=await api(),f=fixture(),sent=[];f.child.stdin.on('data',b=>sent.push(b));const signal={aborted:false,addEventListener(){throw Error('private setup');},removeEventListener(){}};let settled=false;const result=m.runRecoveryTransport(Buffer.from('private source'),{platform:f.platform,signal}).then(r=>{settled=true;return r;});await Promise.resolve();assert.equal(settled,false);assert.ok(f.timers.length>=3);assert.equal(f.cleared.length,0);assert.equal(sent.length,0);assert.equal(f.child.stdin.writableEnded,true);f.close();assert.equal((await result).sshExitVerified,true);});
test('failed initial proof can recover ownership for cleanup only, never resume dispatch',async()=>{const m=await api(),f=fixture(),identity=f.platform.identity;let calls=0;f.platform.identity=()=>++calls===1?null:identity();const sent=[];f.child.stdin.on('data',b=>sent.push(b));const result=m.runRecoveryTransport(Buffer.from('source'),{platform:f.platform});f.timers[3]();assert.equal(sent.length,0);f.timers[0]();f.timers[1]();const r=await result;assert.equal(r.start,'owned-start');assert.equal(r.sshExitVerified,true);assert.equal(r.status,'ABBOTT_RECOVERY_UNACKNOWLEDGED');assert.equal(f.calls.filter(c=>c.signal).length,2);});
test('unknown initial identity never authorizes kill, and late close still reaps after bounded unverified result',async()=>{const m=await api(),f=fixture();f.platform.identity=()=>null;const result=m.runRecoveryTransport(Buffer.from('source'),{platform:f.platform});for(const t of f.timers.slice())t();const r=await result;assert.equal(r.sshExitVerified,false);assert.equal(r.remoteAcknowledged,false);assert.equal(f.calls.filter(c=>c.signal).length,0);assert.equal(f.cleared.length,0);assert.ok(f.child.listenerCount('close'));f.close();assert.ok(f.cleared.length>=3);});
test('exit event prevents rebinding an unproved reused PID during cleanup retry',async()=>{const m=await api(),f=fixture();f.platform.identity=()=>null;const result=m.runRecoveryTransport(Buffer.from('source'),{platform:f.platform});f.child.exitCode=0;f.child.emit('exit',0,null);f.replace();for(const t of f.timers.slice())t();const r=await result;assert.equal(r.sshExitVerified,false);assert.equal(r.start,null);assert.equal(f.calls.filter(c=>c.signal).length,0);f.close();});
test('pre-aborted request never spawns SSH or serializes source',async()=>{const m=await api(),f=fixture(),abort=new AbortController();abort.abort();const r=await m.runRecoveryTransport(Buffer.from('fixture'),{signal:abort.signal,platform:f.platform});assert.equal(r.status,'ABBOTT_RECOVERY_REFUSED');assert.equal(f.calls.length,0);});
test('actual loader distinguishes startup and preflight errors without emitting their contents',async()=>{assert.equal(await loader('startup'),'ABBOTT_RECOVERY_ACK REFUSED remote_startup failed\n');assert.equal(await loader('preflight'),'ABBOTT_RECOVERY_ACK REFUSED remote_preflight refused\n');});
test('exact remote shell tokenization preserves ESM loader and framed inert source without stderr',async()=>{const m=await api(),f=fixture();const result=m.runRecoveryTransport(Buffer.from('fixture'),{platform:f.platform});const command=f.calls[0].args.at(-1);f.close();await result;assert.equal(await loader('success',command),'ABBOTT_RECOVERY_ACK RESTORED complete none\n');});
test('valid ack cannot override failing SSH exit or signal',async()=>{const m=await api();for(const [code,signal]of[[1,null],[null,'SIGTERM']]){const f=fixture(),result=m.runRecoveryTransport(Buffer.from('fixture'),{platform:f.platform});f.child.stdout.write('ABBOTT_RECOVERY_ACK RESTORED complete none\n');f.platform.identity=()=>null;f.child.emit('close',code,signal);const r=await result;assert.equal(r.status,'ABBOTT_RECOVERY_UNACKNOWLEDGED');assert.equal(r.remoteAcknowledged,false);}});
async function loader(mode,command){const {RECOVERY_LOADER}=await api();const child=spawn(command?'/bin/sh':process.execPath,command?['-c',command.replace('/usr/bin/node',process.execPath)]:['--input-type=module','-e',RECOVERY_LOADER],{env:{},stdio:['pipe','pipe','pipe','pipe']});const source=Buffer.from(mode==='success'?"export async function run(){return 'ABBOTT_RECOVERY_RESTORED'}":mode==='startup'?"throw Error('private startup token')":mode==='preflight'?"export async function run(){throw Error('private preflight token')}":"import fs from'node:fs';export async function run(signal){const stopped=new Promise(resolve=>signal.aborted?resolve():signal.addEventListener('abort',resolve,{once:true}));fs.writeSync(3,'ready');await stopped;throw Error('ABBOTT_RECOVERY_REVIEW_REQUIRED')}");const chunks=[],errors=[];child.stdout.on('data',b=>chunks.push(b));child.stderr.on('data',b=>errors.push(b));child.stdin.on('error',()=>{});child.stdio[3].once('data',()=>{if(mode==='abort')child.stdin.write('ABORT\n');if(mode==='eof')child.stdin.end();});let expired=false;const timer=setTimeout(()=>{expired=true;child.kill('SIGKILL');},3000);const closed=new Promise(resolve=>child.on('close',resolve));
  if(mode==='oversized')child.stdin.end('ABBOTT_RECOVERY_SOURCE 1048577 '+'a'.repeat(64)+'\n');
  else if(mode==='truncated')child.stdin.end('ABBOTT_RECOVERY_SOURCE 100 '+'a'.repeat(64)+'\nshort');
  else{child.stdin.write(`ABBOTT_RECOVERY_SOURCE ${source.length} ${createHash('sha256').update(source).digest('hex')}\n`);child.stdin.write(source);if(mode==='pre_abort')child.stdin.write('ABORT\n');else child.stdin.write('RUN\n');}
  await closed;clearTimeout(timer);source.fill(0);assert.equal(expired,false,'owned loader must acknowledge and exit within deadline');assert.equal(Buffer.concat(errors).length,0);let gone=false;try{process.kill(child.pid,0);}catch(e){gone=e.code==='ESRCH';}assert.ok(gone);const output=Buffer.concat(chunks).toString();assert.ok(output.startsWith('ABBOTT_RECOVERY_READY\n'));return output.slice('ABBOTT_RECOVERY_READY\n'.length);
}
test('actual loader accepts strict source frame; EOF/abort acknowledge only after terminal cleanup',async()=>{assert.equal(await loader('success'),'ABBOTT_RECOVERY_ACK RESTORED complete none\n');for(const mode of['abort','eof'])assert.equal(await loader(mode),'ABBOTT_RECOVERY_ACK REVIEW_REQUIRED remote_recovery review_required\n');for(const mode of['pre_abort','oversized','truncated'])assert.equal(await loader(mode),'ABBOTT_RECOVERY_ACK REFUSED ack_framing malformed\n');});
