import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import path from'node:path';import vm from'node:vm';import{execFileSync}from'node:child_process';
const api=()=>import('./runtime-release-remote.mjs');
const base=body=>'server { listen 80; server_name dashboards.adreports.ru alias.example; return 301 https://$host$request_uri; }\nserver { listen 443 ssl; server_name alias.example dashboards.adreports.ru; '+body+' }\n';
const zone='limit_req_zone $binary_remote_addr zone=perip:10m rate=10r/s;\n';
const fixedIncludes=['/etc/nginx/snippets/coopervision-market-path.conf','/etc/nginx/snippets/reportingdash-public-coopervision-market-intelligence-c.conf'];
const fixedMain=()=>base(fixedIncludes.map(p=>'include '+p+';').join(''));
const goodFragments=()=>new Map([[fixedIncludes[0],'location /coopervision { proxy_pass http://127.0.0.1:3001; }'],[fixedIncludes[1],'location = /market { proxy_pass http://127.0.0.1:3002; }']]);
test('deploy validates the exact pair of fixed includes in place only when present',async()=>{const m=await api();let reads=0;const resolve=()=>{reads++;return goodFragments();};assert.doesNotThrow(()=>m.validateAbbottNginxText(fixedMain(),()=>{},resolve));assert.equal(reads,1);assert.doesNotThrow(()=>m.validateAbbottNginxText(base('location / { return 404; }'),()=>{},resolve));assert.equal(reads,1);assert.doesNotThrow(()=>m.validateAbbottNginxText(base([...fixedIncludes].reverse().map(p=>'include '+p+';').join('')),()=>{},resolve));});
test('fixed include references fail before reads for missing duplicate extra or ambiguous forms',async()=>{const m=await api();for(const body of ['include '+fixedIncludes[0]+';',fixedIncludes.map(p=>'include '+p+';').join('')+'include '+fixedIncludes[0]+';','include /etc/nginx/other; include '+fixedIncludes[1]+';','include '+fixedIncludes[0].replace('market','mar\\ket')+'; include '+fixedIncludes[1]+';']){let reads=0;assert.throws(()=>m.validateAbbottNginxText(base(body),()=>{},()=>{reads++;return goodFragments();}));assert.equal(reads,0);}});
test('fixed fragments refuse nested authority includes unsupported routing and syntax',async()=>{const m=await api();for(const text of ['include /etc/nginx/other;','server { listen 443 ssl; }','listen 443 ssl;','server_name private;','location ~ /x { return 404; }','set $p private;','location /x { proxy_pass http://$p; }','location /x { proxy_pass http://127.0.0.1:3004; }','location /x { proxy_pass http://127.0.0.1:3005; }','location /dashboard/18 { return 404; }','location /dashboard/abbott { return 404; }','if ($host) { return 404; }','location /x {','location /x { root /private; }']){const fragments=goodFragments();fragments.set(fixedIncludes[0],text);const notes=[];assert.throws(()=>m.validateAbbottNginxText(fixedMain(),r=>notes.push(r),()=>fragments));assert.ok(['include_route','include_syntax',...includeReasons].includes(notes.at(-1)));assert.doesNotMatch(JSON.stringify(notes),/private|http|\/etc/);}});
test('inventory listener count and repeated literal endpoints refuse safely',async()=>{const m=await api();for(const tail of ['listen 443 ssl;','listen [::]:443 ssl; listen [::]:443 ssl;',Array.from({length:8},(_,i)=>'listen 192.0.2.'+(i+1)+':443 ssl;').join('')])assert.deepEqual(m.inventoryAbbottNginxIncludes(base('include /etc/nginx/a; '+tail)),{reason:'parser_ambiguity'});assert.deepEqual(m.inventoryAbbottNginxIncludes(base('include /etc/nginx/a; '+Array.from({length:7},(_,i)=>'listen 192.0.2.'+(i+1)+':443 ssl;').join(''))),{paths:['/etc/nginx/a']});});
const inventoryBadListeners=['80 443 ssl','$port 443 ssl','443 ssl ssl','443 ssl private_option','443 ssl default_server default_server','443 ssl http2 http2','443 ssl reuseport reuseport','443 ssl 80','443 ssl 127.0.0.1:443','443 ssl $private','443 ssl backlog=1','443 ssl default','443 ssl http2=on','443','0443 ssl','443-444 ssl','*:443 ssl','localhost:443 ssl','999.0.0.1:443 ssl','127.00.0.1:443 ssl','[::1]:443 ssl','443 ssl ipv6only=on'];
test('inventory listener address and options must be exact without ambiguity or partial output',async()=>{const m=await api();for(const listen of inventoryBadListeners)assert.deepEqual(m.inventoryAbbottNginxIncludes(base('include /etc/nginx/first;').replace('443 ssl',listen)),{reason:'parser_ambiguity'});for(const listen of ['80 443','$port 80','80 ssl','80 private','80 default_server default_server','80 http2'])assert.deepEqual(m.inventoryAbbottNginxIncludes(base('include /etc/nginx/first;').replace('listen 80;','listen '+listen+';')),{reason:'parser_ambiguity'});assert.deepEqual(m.inventoryAbbottNginxIncludes(base('include /etc/nginx/first; listen 80;')),{reason:'parser_ambiguity'});});
test('inventory supports bounded IPv4 IPv6 TLS listener flags and port80 siblings',async()=>{const m=await api();for(const address of ['443','127.0.0.1:443','0.0.0.0:443','192.0.2.1:443','[::]:443'])for(const options of ['ssl','ssl default_server','default_server ssl http2 reuseport','http2 ssl','reuseport ssl'])assert.deepEqual(m.inventoryAbbottNginxIncludes(base('include /etc/nginx/a;').replace('443 ssl',address+' '+options)),{paths:['/etc/nginx/a']});assert.deepEqual(m.inventoryAbbottNginxIncludes(base('include /etc/nginx/a; listen [::]:443 ssl;').replace('listen 80;','listen 0.0.0.0:80 default_server reuseport; listen [::]:80;')),{paths:['/etc/nginx/a']});});
test('inventory listener tightening leaves deploy acceptance and phase sequence unchanged',async()=>{const m=await api(),source=execFileSync('/usr/bin/git',['show','de0003ee76480d77ae6788358bd18cc1acdf2734:scripts/runtime-release-remote.mjs'],{cwd:new URL('..',import.meta.url),env:{PATH:'/usr/bin:/bin'},encoding:'utf8',stdio:['ignore','pipe','pipe']}),original=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));const run=(fn,text)=>{const notes=[];let accepted=true;try{fn(text,n=>notes.push(n));}catch{accepted=false;}return{accepted,notes};};let count=0;for(const listen of [...inventoryBadListeners,'443 ssl','[::]:443 ssl http2','127.0.0.1:443 default_server ssl reuseport'])for(const body of ['', 'include /etc/nginx/a;','location / { proxy_pass http://127.0.0.1:3001; }']){const text=base(body).replace('443 ssl',listen);assert.deepEqual(run(m.validateAbbottNginxText,text),run(original.validateAbbottNginxText,text));count++;}assert.equal(count,75);});
test('inventory TLS authority requires unambiguous literal server and listener tokens',async()=>{const m=await api();for(const text of [base('include /etc/nginx/a;').replace('alias.example dashboards.adreports.ru','alias.example dashboards.adreports\\.ru'),base('include /etc/nginx/a;').replace('443 ssl','44\\3 ssl'),base('include /etc/nginx/a;').replace('443 ssl','443 s\\sl'),base('include /etc/nginx/a;')+'server { listen 443; server_name dashboards.adreports.ru; }',base('include /etc/nginx/a;')+'server { listen 443 ssl; server_name dashboards.adreports.ru; }'])assert.deepEqual(m.inventoryAbbottNginxIncludes(text),{reason:'parser_ambiguity'});assert.deepEqual(m.inventoryAbbottNginxIncludes('upstream inert { server 127.0.0.1:9000; }'+base('include /etc/nginx/a;')),{paths:['/etc/nginx/a']});});
test('include inventory scans structural selected subtree despite unsupported semantics',async()=>{const m=await api();assert.equal(typeof m.inventoryAbbottNginxIncludes,'function');const text='map $x $y { default z; }'+base('sendfile on; location ~ /private { if ($host) { include /etc/nginx/a; } } include /etc/nginx/b;').replace('return 301','include /outside/ignored; return 301');assert.deepEqual(m.inventoryAbbottNginxIncludes(text),{paths:['/etc/nginx/a','/etc/nginx/b']});assert.throws(()=>m.validateAbbottNginxText(text));});
test('selected include inventory returns only sorted unique canonical bounded paths',async()=>{const m=await api();assert.equal(typeof m.inventoryAbbottNginxIncludes,'function');const text=base('include /etc/nginx/z.conf; location / { include "/etc/letsencrypt/a.conf"; include /etc/nginx/z.conf; }');assert.deepEqual(m.inventoryAbbottNginxIncludes(text),{paths:['/etc/letsencrypt/a.conf','/etc/nginx/z.conf']});assert.deepEqual(m.inventoryAbbottNginxIncludes(base('location / { return 404; }')),{paths:[]});const prefix='/etc/nginx/',edge=prefix+'x'.repeat(256-prefix.length);assert.deepEqual(m.inventoryAbbottNginxIncludes(base('include '+edge+';')),{paths:[edge]});assert.deepEqual(m.inventoryAbbottNginxIncludes(base(Array.from({length:8},(_,i)=>'include /etc/nginx/'+i+'.conf;').join(''))),{paths:Array.from({length:8},(_,i)=>'/etc/nginx/'+i+'.conf')});assert.throws(()=>m.validateAbbottNginxText(text));});
test('include inventory refuses ambiguity without partial paths or secret argument leakage',async()=>{const m=await api();assert.equal(typeof m.inventoryAbbottNginxIncludes,'function');for(const body of ['include /etc/nginx/*.conf;','include $private;','include /etc/nginx2/private;','include /etc/nginx/../private;','include /etc/nginx/./a;','include /etc/nginx//a;','include /etc/nginx/private?token=secret;','include relative/private;','include /outside/private;','include /etc/nginx/a private_secret;','include /etc/nginx/a { secret value; }','include /etc/nginx/proxy\\_params;','include /etc/"nginx/a";','include \u00a0 /etc/nginx/a;','include /etc/nginx/'+ 'x'.repeat(246)+';','server { listen 443 ssl; }',Array.from({length:9},(_,i)=>'include /etc/nginx/'+i+'.conf;').join('')]){const result=m.inventoryAbbottNginxIncludes(base('include /etc/nginx/first.conf; '+body));assert.deepEqual(result,{reason:'parser_ambiguity'});assert.doesNotMatch(JSON.stringify(result),/private|secret|\/etc|first/);}assert.deepEqual(m.inventoryAbbottNginxIncludes(base('include /etc/nginx/a;').replace('443 ssl','443')),{reason:'parser_ambiguity'});});
const includeCases=[['/etc/letsencrypt/options-ssl-nginx.conf','letsencrypt_options'],['/etc/nginx/snippets/ssl-params.conf','ssl_params'],['/etc/nginx/proxy_params','proxy_params'],['/etc/nginx/mime.types','mime_types'],['/etc/nginx/*.conf','other'],['$private_path','other'],['${private_path}','other'],['snippets/ssl-params.conf','other'],['/etc/nginx/proxy_params private_secret','other'],['/private/secret','other'],['/etc/nginx/../nginx/proxy_params','other'],['/etc/nginx/proxy_params/','other'],['/etc/nginx/PROXY_PARAMS','other'],['','other']];
const includeLexicalCases=includeCases.slice(0,4).flatMap(([literal,category])=>{const escaped=[literal.replace('/','\\/'),literal.replace(/[_.-]/,c=>'\\'+c)];return [[literal,category],['"'+literal+'"',category],["'"+literal+"'",category],[literal+' # private_secret\\_ignored\n',category],['"'+literal+'" # private_secret\n',category],...['\u00a0','\u2028','\u2029'].flatMap(gap=>[[gap+' '+literal,'other'],[literal+' '+gap+' ','other']]),...escaped.flatMap(v=>[[v,'other'],['"'+v+'"','other'],["'"+v+"'",'other']]),['/etc/"'+literal.slice(5)+'"','other'],['""'+literal,'other'],['"'+literal+'"""','other']];});
test('selected include lexical escapes and concatenated quotes cannot impersonate exact paths',async()=>{const m=await api();for(const [args,category]of includeLexicalCases)for(const body of ['include '+args+';','location / { include '+args+'; }']){assert.deepEqual(m.classifyAbbottNginxFirstRejection(base(body)),{rejection:'selected_include_'+category});assert.throws(()=>m.validateAbbottNginxText(base(body)));}assert.deepEqual(m.classifyAbbottNginxFirstRejection(base('include /etc/nginx/proxy\\_params;')),{rejection:'selected_include_other'});assert.deepEqual(m.classifyAbbottNginxFirstRejection(base('include "/etc/nginx/proxy\\_params";')),{rejection:'selected_include_other'});});
test('ambiguous comment adjacency and non-ASCII token boundaries cannot yield known include paths',async()=>{const m=await api();for(const [literal]of includeCases.slice(0,4))for(const body of ['include '+literal+'#private_secret\n;','include "'+literal+'"#private_secret\n;','include\u00a0'+literal+';','include '+literal+'\u00a0;'])assert.deepEqual(m.classifyAbbottNginxFirstRejection(base(body)),{rejection:'selected_include_other'});});
test('skipped ambiguous separators taint the directive even when padded by ASCII spaces',async()=>{const m=await api();for(const [literal,category]of includeCases.slice(0,4))for(const gap of ['\u00a0','\u2028','\u2029']){for(const body of ['include '+gap+' '+literal+';','include '+literal+' '+gap+' ;'])assert.deepEqual(m.classifyAbbottNginxFirstRejection(base(body)),{rejection:'selected_include_other'});assert.deepEqual(m.classifyAbbottNginxFirstRejection(base('include # private'+gap+'comment\n '+literal+';')),{rejection:'selected_include_'+category});}});
test('lexical diagnostic provenance preserves deployment acceptance and phases',async()=>{const m=await api(),source=execFileSync('/usr/bin/git',['show','be848ec8d8913b9041ddfed92830865d70cb07e7:scripts/runtime-release-remote.mjs'],{cwd:new URL('..',import.meta.url),env:{PATH:'/usr/bin:/bin'},encoding:'utf8',stdio:['ignore','pipe','pipe']}),original=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));const run=(fn,text)=>{const notes=[];let accepted=true;try{fn(text,n=>notes.push(n));}catch{accepted=false;}return{accepted,notes};};let count=0;for(const [args]of includeLexicalCases)for(const text of [base('include '+args+';'),base('location / { include '+args+'; }'),base('').replace('return 301','include '+args+'; return 301'),'include '+args+';'+base('')]){assert.deepEqual(run(m.validateAbbottNginxText,text),run(original.validateAbbottNginxText,text));count++;}assert.equal(count,320);});
test('selected include exact args map only closed categories without accepting or loading includes',async()=>{const m=await api();for(const [args,category]of includeCases)for(const body of ['include '+args+';','location / { include '+args+'; }']){const text=base(body),result=m.classifyAbbottNginxFirstRejection(text);assert.deepEqual(result,{rejection:'selected_include_'+category});assert.doesNotMatch(JSON.stringify(result),/secret|private|\/etc|\$|\.conf/);assert.throws(()=>m.validateAbbottNginxText(text));}assert.deepEqual(m.classifyAbbottNginxFirstRejection(base('include /etc/nginx/proxy_params { secret value; }')),{rejection:'selected_include_other'});assert.deepEqual(m.classifyAbbottNginxFirstRejection(base('sendfile on; include /etc/nginx/proxy_params;')),{rejection:'selected_sendfile'});});
test('include diagnostic refinement has zero strict acceptance and phase drift against c80d7c2',async()=>{const m=await api(),source=execFileSync('/usr/bin/git',['show','c80d7c2c505b892427a6ad1ffbf2143435493dc1:scripts/runtime-release-remote.mjs'],{cwd:new URL('..',import.meta.url),env:{PATH:'/usr/bin:/bin'},encoding:'utf8',stdio:['ignore','pipe','pipe']}),original=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));const run=(fn,text)=>{const notes=[];let accepted=true;try{fn(text,n=>notes.push(n));}catch{accepted=false;}return{accepted,notes};};let count=0;for(const [args]of includeCases)for(const text of [base('include '+args+';'),base('location / { include '+args+'; }'),base('').replace('return 301','include '+args+'; return 301'),'include '+args+';'+base(''),base('include '+args+' { hidden value; }'),base('include '+args+';').replace('443 ssl','443')]){assert.deepEqual(run(m.validateAbbottNginxText,text),run(original.validateAbbottNginxText,text));count++;}assert.equal(count,84);});
test('inactive HTTP rate shapes preserve baseline even when not valid in selected TLS',async()=>{const m=await api();for(const inactive of ['if ($host) { limit_req zone=missing; }','limit_req_zone $binary_remote_addr zone=inactive:10m rate=1r/s;']){const text=base('').replace('return 301',inactive+' return 301');assert.doesNotThrow(()=>m.validateAbbottNginxText(text));}assert.throws(()=>m.validateAbbottNginxText(base('limit_req zone=missing;')));assert.throws(()=>m.validateAbbottNginxText(base(zone)));});
test('bounded literal rate zones and declared selected limit_req are accepted',async()=>{const m=await api();for(const declaration of [zone,'limit_req_zone $server_name rate=30r/m zone=perserver:64k;\n','limit_req_zone literal_key zone=perserver:65536 rate=1r/s;\n']){const name=declaration.includes('perip:')?'perip':'perserver';for(const options of ['', ' burst=1',' burst=100 nodelay',' burst=100 delay=10',' delay=1',' nodelay'])for(const scope of ['server','location']){const limit='limit_req zone='+name+options+';',body=scope==='server'?limit+' location / { proxy_pass http://127.0.0.1:3001; }':'location / { '+limit+' proxy_pass http://127.0.0.1:3001; }';assert.doesNotThrow(()=>m.validateAbbottNginxText(declaration+base(body)));assert.deepEqual(m.classifyAbbottNginxFirstRejection(declaration+base(body)),{rejection:'none'});}}});
test('rate zone grammar rejects missing duplicate malformed routing and block inputs',async()=>{const m=await api();const bad=[
 'limit_req_zone $binary_remote_addr zone=perip:10m rate=10r/s { return 404; }',
 'limit_req_zone zone=perip:10m rate=10r/s;', 'limit_req_zone "" zone=perip:10m rate=10r/s;',
 'limit_req_zone $binary_remote_addr zone=perip:10m;', 'limit_req_zone $binary_remote_addr rate=10r/s;',
 'limit_req_zone key zone=perip:10m zone=other:10m rate=1r/s;', 'limit_req_zone key zone=perip:10m rate=1r/s rate=2r/m;',
 ...['0','-1','1k','65535','2g','999999999999999999999m','10.5m','$size'].map(size=>'limit_req_zone key zone=perip:'+size+' rate=1r/s;'),
 ...['0r/s','-1r/s','1.5r/s','1r/h','1R/S','1000001r/s','$rate'].map(rate=>'limit_req_zone key zone=perip:10m rate='+rate+';'),
 ...['$name','../name','name/path','name?key=x','0name','x'.repeat(65)].map(name=>'limit_req_zone key zone='+name+':10m rate=1r/s;'),
 ...['/dashboard/18','https://private.invalid','%2fapi','key value','$x${y}','3004','ABBOTT'].map(key=>'limit_req_zone "'+key+'" zone=perip:10m rate=1r/s;'),
 'limit_req_zone key zone=perip:10m rate=1r/s sync;', 'limit_req_zone key zone=perip:10m rate=1r/s unknown;', zone+zone,
 ];for(const declaration of bad)assert.throws(()=>m.validateAbbottNginxText(declaration+base('location / { proxy_pass http://127.0.0.1:3001; }')));});
test('limit_req permits only declared literal zone and bounded nonconflicting options',async()=>{const m=await api();for(const args of ['', 'zone=unknown','zone=$name','zone=perip zone=perip','zone=perip burst=0','zone=perip burst=-1','zone=perip burst=1.5','zone=perip burst=$n','zone=perip burst=1000001','zone=perip burst=1 burst=2','zone=perip delay=0','zone=perip delay=-1','zone=perip delay=1.5','zone=perip delay=$n','zone=perip delay=1000001','zone=perip delay=1 delay=2','zone=perip delay=1 nodelay','zone=perip nodelay nodelay','zone=perip nodelay=1','zone=perip unknown','zone=/dashboard/18','zone=perip burst=3004x'])assert.throws(()=>m.validateAbbottNginxText(zone+base('location / { limit_req '+args+'; }')));assert.throws(()=>m.validateAbbottNginxText(zone+base('limit_req zone=perip { return 404; }')));});
test('rate limit context and other top-level directives remain refused',async()=>{const m=await api();for(const text of [base(zone),base('location / { '+zone+' }'),zone+'limit_req zone=perip;'+base(''),zone+base('location / { location /nested { limit_req zone=perip; } }'),zone+'include /private;'+base(''),zone+'map $x $y { default x; }'+base('')])assert.throws(()=>m.validateAbbottNginxText(text));});
test('rate grammar numeric key and declaration bounds are explicit',async()=>{const m=await api();const valid=['limit_req_zone key zone=one:64K rate=1000000r/s;','limit_req_zone $remote_addr zone=one:1024M rate=1r/m;','limit_req_zone '+'x'.repeat(128)+' zone=one:1m rate=1r/s;'];for(const declaration of valid)assert.doesNotThrow(()=>m.validateAbbottNginxText(declaration+base('limit_req zone=one burst=1000000 delay=1000000;')));for(const declaration of [valid[0].replace('64K','1025M'),valid[2].replace('x'.repeat(128),'x'.repeat(129)),Array.from({length:65},(_,i)=>'limit_req_zone key zone=zone'+i+':64k rate=1r/s;').join('')])assert.throws(()=>m.validateAbbottNginxText(declaration+base('')));});
test('same-zone applications cannot repeat in one context but inheritance and distinct zones remain valid',async()=>{const m=await api();for(const body of ['limit_req zone=perip; limit_req zone=perip;','location / { limit_req zone=perip burst=5; limit_req zone=perip burst=10; }'])assert.throws(()=>m.validateAbbottNginxText(zone+base(body)));for(const body of ['limit_req zone=perip; location / { limit_req zone=perip; }','location / { limit_req zone=perip; } location /status { limit_req zone=perip; }','limit_req zone=perip; limit_req zone=perhost;'])assert.doesNotThrow(()=>m.validateAbbottNginxText(zone+'limit_req_zone $server_name zone=perhost:10m rate=1r/s;'+base(body)));});
test('exact one-GiB byte size matches suffix boundary and next byte refuses',async()=>{const m=await api();assert.doesNotThrow(()=>m.validateAbbottNginxText('limit_req_zone key zone=one:1073741824 rate=1r/s;'+base('')));assert.throws(()=>m.validateAbbottNginxText('limit_req_zone key zone=one:1073741825 rate=1r/s;'+base('')));});
test('first deployment rejection reports top-level fixed context names before TLS selection',async()=>{const m=await api();assert.equal(typeof m.classifyAbbottNginxFirstRejection,'function');for(const name of ['upstream','map','geo','split_clients','log_format','proxy_cache_path','limit_req_zone','limit_conn_zone','private_token'])for(const ending of [';',' { secret_child private_value; }']){const text=name+' private_value'+ending+base('sendfile on;');assert.deepEqual(m.classifyAbbottNginxFirstRejection(text),{rejection:'top_'+(name==='private_token'?'other':name)});assert.throws(()=>m.validateAbbottNginxText(text));}});
test('top upstream server leaf is not a nested TLS authority block',async()=>{const m=await api();assert.deepEqual(m.classifyAbbottNginxFirstRejection('upstream private_name { server 127.0.0.1:3001; }'+base('')),{rejection:'top_upstream'});assert.deepEqual(m.classifyAbbottNginxFirstRejection('upstream private_name { server { listen 443 ssl; } }'+base('')),{reason:'parser_ambiguity'});});
test('first rejection never continues past selected unsupported node or returns partial inventory',async()=>{const m=await api();assert.equal(typeof m.classifyAbbottNginxFirstRejection,'function');for(const [body,code]of [['sendfile on; root /secret;','selected_sendfile'],['private_token value;','selected_other'],['location / { proxy_redirect off; }','selected_proxy_redirect'],['map private { hidden value; }','selected_map']]){const result=m.classifyAbbottNginxFirstRejection(base(body+' location ~ /later { root /secret; }'));assert.deepEqual(result,{rejection:code});assert.doesNotMatch(JSON.stringify(result),/private|secret|later|root/);}assert.deepEqual(m.classifyAbbottNginxFirstRejection(base('location / { proxy_pass http://127.0.0.1:3001; }')),{rejection:'none'});});
test('first rejection retains syntax and TLS ambiguity instead of inventing directive names',async()=>{const m=await api();assert.equal(typeof m.classifyAbbottNginxFirstRejection,'function');for(const text of ['upstream x {',base('sendfile on;')+'server { listen 443; server_name dashboards.adreports.ru; }',base('location ~ /x { root /secret; }'),'upstream x { server { listen 443 ssl; } }'+base(''),'server value;'+base('')])assert.deepEqual(m.classifyAbbottNginxFirstRejection(text),{reason:'parser_ambiguity'});});
test('unknown directive is successful analysis, ambiguity is a separate closed refusal',async()=>{const m=await api();assert.deepEqual(m.diagnoseAbbottNginxText(base('private_secret value;')),['other']);for(const text of [base('sendfile on; location ~ /x { root /secret; }'),base('sendfile on;')+'}',base('sendfile on;')+'server { listen 443; server_name dashboards.adreports.ru; }'])assert.deepEqual(m.diagnoseAbbottNginxText(text),{reason:'parser_ambiguity'});});
test('known opaque block names are diagnosed but never traversed or accepted by deploy',async()=>{const m=await api();for(const body of ['if ($secret) { secret_nested value; }','types { private_nested secret; }','location / { limit_except GET { private_nested secret; } }']){const name=body.startsWith('location')?'limit_except':body.split(' ')[0];assert.deepEqual(m.diagnoseAbbottNginxText(base(body)),[name]);assert.throws(()=>m.validateAbbottNginxText(base(body)));assert.deepEqual(m.diagnoseAbbottNginxText(base(body+' location ~ /x { root /secret; }')),{reason:'parser_ambiguity'});}assert.deepEqual(m.diagnoseAbbottNginxText(base('private_block { sendfile on; }')),['other']);});
test('batch diagnosis uses shared selected TLS parser and fixed sorted unique names only',async()=>{
 const m=await api();assert.equal(typeof m.diagnoseAbbottNginxText,'function');
 const text=base('sendfile on; tcp_nopush on; location / { proxy_hide_header "private-token"; proxy_redirect off; sendfile off; private_token "https://private.invalid/secret"; }');
 assert.deepEqual(m.diagnoseAbbottNginxText(text),['other','proxy_hide_header','proxy_redirect','sendfile','tcp_nopush']);
 assert.deepEqual(m.diagnoseAbbottNginxText(base('location / { proxy_pass http://127.0.0.1:3001; }')),[]);
 assert.deepEqual(m.diagnoseAbbottNginxText(base('location / { proxy_pass http://127.0.0.1:3001; }').replace('return 301','sendfile on; return 301')),[]);
});
test('batch diagnosis fails closed with no partial result for ambiguous TLS or unproven nesting',async()=>{
 const m=await api();assert.equal(typeof m.diagnoseAbbottNginxText,'function');
 for(const text of [base('sendfile on; location ~* /private { root /secret; }'),base('sendfile on; location / { server { listen 443 ssl; } }'),base('sendfile on;')+'server { listen 443; server_name dashboards.adreports.ru; }',base('sendfile on;')+'}',base('sendfile on;').replace('443 ssl','80')])assert.deepEqual(m.diagnoseAbbottNginxText(text),{reason:'parser_ambiguity'});
});
test('batch diagnostic ignores names in arguments and comments and keeps strict acceptance unchanged',async()=>{
 const m=await api();assert.equal(typeof m.validateAbbottNginxText,'function');
 const text=base('private_token "sendfile root https://private.invalid/secret"; # proxy_redirect private\nlocation / { proxy_pass http://127.0.0.1:3001; }');
 assert.deepEqual(m.diagnoseAbbottNginxText(text),['other']);assert.throws(()=>m.validateAbbottNginxText(text));
 assert.throws(()=>m.validateAbbottNginxText(base('sendfile on;')));
 assert.doesNotThrow(()=>m.validateAbbottNginxText(base('location / { proxy_pass http://127.0.0.1:3001; }')));
 assert.doesNotMatch(JSON.stringify(m.diagnoseAbbottNginxText(text)),/private|secret|https/);
});
test('fixed reader only opens stable nofollow config, clears bounded buffers and refuses drift',async()=>{
 const m=await import('./abbott-nginx-readonly.mjs').catch(()=>({}));assert.equal(typeof m.readAbbottNginxNames,'function');
 const file='/etc/nginx/conf.d/dashboard-next.conf',content=Buffer.from(base('sendfile on;')),buffers=[],opened=[];let closed=0;
 const stat=p=>({dev:1,ino:2,uid:0,gid:0,nlink:1,mode:p===file?0o100644:0o40755,size:p===file?content.length:0,mtimeMs:1,ctimeMs:1,isFile:()=>p===file,isDirectory:()=>p!==file,isSymbolicLink:()=>false});
 const io={constants:fs.constants,lstatSync:stat,realpathSync:p=>p,openSync(p,flags){assert.equal(p,file);assert.equal(flags,fs.constants.O_RDONLY|fs.constants.O_NOFOLLOW);opened.push(p);return 3;},fstatSync:()=>stat(file),readSync(fd,b,o,l,p){buffers.push(b);return content.copy(b,o,p,p+l);},closeSync(){closed++;}};
 assert.deepEqual(m.readAbbottNginxNames({io,hostname:()=> 'ybjqbzojln',getuid:()=>0}),{rejection:'selected_sendfile'});assert.equal(closed,1);assert.equal(opened.length,1);assert.ok(buffers.every(b=>b.every(v=>v===0)));assert.deepEqual(m.readAbbottNginxIncludes({io,hostname:()=> 'ybjqbzojln',getuid:()=>0}),{paths:[]});assert.ok(opened.every(p=>p===file));assert.ok(buffers.every(b=>b.every(v=>v===0)));
 for(const mode of ['owner','symlink','mode','size','drift','host']){let calls=0;const mutated={...io,lstatSync(p){const s=stat(p);if(p===file){if(mode==='owner')s.uid=1;if(mode==='symlink')s.isSymbolicLink=()=>true;if(mode==='mode')s.mode=0o100666;if(mode==='size')s.size=1048577;if(mode==='drift'&&++calls>1)s.ino++;}return s;}};assert.deepEqual(m.readAbbottNginxNames({io:mutated,hostname:()=>mode==='host'?'private-token':'ybjqbzojln',getuid:()=>0}),{reason:mode==='host'?'remote_authority':'metadata'});}
 const invalidUtf8={...io,readSync(fd,b,o,l,p){const n=io.readSync(fd,b,o,l,p);if(p===0)b[0]=255;return n;}};assert.deepEqual(m.readAbbottNginxNames({io:invalidUtf8,hostname:()=> 'ybjqbzojln',getuid:()=>0}),{reason:'utf8'});
 assert.deepEqual(m.readAbbottNginxNames({io:{...io,closeSync(){throw Error('private-secret');}},hostname:()=> 'ybjqbzojln',getuid:()=>0}),{reason:'cleanup'});
});
test('differential strict deployment acceptance stays identical to reviewed b273294 parser',async()=>{
 const m=await api(),source=execFileSync('/usr/bin/git',['show','b27329424965540b8b6338d9dff682078db5d55f:scripts/runtime-release-remote.mjs'],{cwd:new URL('..',import.meta.url),env:{PATH:'/usr/bin:/bin'},encoding:'utf8',stdio:['ignore','pipe','pipe']}),start=source.indexOf('  function nginxSanity(text){'),end=source.indexOf('  function listenerTable()',start);assert.ok(start>0&&end>start);
 const originalNotes=[],original=vm.runInNewContext(source.slice(start,end)+'\nnginxSanity',{path,nginxReason:code=>originalNotes.push(code),fail(){throw Error('REFUSED');}}),accept=(fn,text)=>{try{fn(text);return true;}catch{return false;}};
 const bodies=['location / { proxy_pass http://127.0.0.1:3001; }','sendfile on;','include /private;','location ~ /x { return 404; }','if ($x) { return 404; }','server { listen 443 ssl; }','location / { add_header Location /x; }','location / { proxy_pass http://$private; }','set $x private;'];
 for(const id of ['18','018','0x12','0b10010','1.8e1','+18','abbott','AbBoTt','19','%31%38',' 18 ','18/../19'])for(const directive of ['location = /dashboard/ID { return 404; }','location /api/dashboard/ID { return 404; }','location = /status { proxy_pass http://127.0.0.1:3001/dashboard/ID; }'])bodies.push(directive.replace('ID',id));
 let comparisons=0;for(const body of bodies)for(const variant of [base(body),base(body).replace('443 ssl','443'),base(body)+'server { listen 443; server_name dashboards.adreports.ru; }',base(body)+'# private-token\n',base(body)+'}',base(body).replace('alias.example dashboards.adreports.ru','dashboards.adreports.ru alias.example')]){const actualNotes=[];originalNotes.length=0;assert.equal(accept(text=>m.validateAbbottNginxText(text,code=>actualNotes.push(code)),variant),accept(original,variant));assert.deepEqual(actualNotes,originalNotes);comparisons++;}assert.equal(comparisons,270);for(const name of ['upstream','map','geo','split_clients','log_format','proxy_cache_path','limit_req_zone','limit_conn_zone','private_token']){const text=name+' private_value { hidden value; }'+base('sendfile on;'),actualNotes=[];originalNotes.length=0;assert.equal(accept(text=>m.validateAbbottNginxText(text,code=>actualNotes.push(code)),text),accept(original,text));assert.deepEqual(actualNotes,originalNotes);}
 const declarations=[zone,zone.replace('10r/s','30r/m'),zone.replace('10m','65536'),zone+'limit_req_zone $server_name zone=perhost:10m rate=1r/s;'];let safeDeltas=0;for(const declaration of declarations)for(const body of ['', 'limit_req zone=perip;', 'location / { limit_req zone=perip burst=1 nodelay; }','location / { limit_req zone=perip burst=5 delay=1; }']){const text=declaration+base(body);assert.equal(accept(original,text),false);assert.equal(accept(m.validateAbbottNginxText,text),true);safeDeltas++;}assert.equal(safeDeltas,16);
 const inactiveBodies=['limit_req zone=missing;','limit_req zone=$private burst=-1;','limit_req_zone $binary_remote_addr zone=inactive:10m rate=1r/s;','limit_req_zone key zone=inactive:1k rate=bad;','limit_req zone=missing { return 404; }','limit_req_zone key { hidden value; }','if ($host) { limit_req zone=missing; }','location /nested { limit_req zone=missing; }'];let inactiveCases=0;for(const body of inactiveBodies)for(const text of [base('').replace('return 301',body+' return 301'),base('').replace('return 301','if ($host) { '+body+' } return 301'),base('').replace('return 301','location /inactive { '+body+' } return 301'),base('')+'server { listen 80; server_name unrelated.example; '+body+' }',base('')+'server { listen 443 ssl; server_name unrelated.example; '+body+' }',base('')+'server { listen 443 ssl; server_name unrelated.example; location / { '+body+' } }']){const actualNotes=[];originalNotes.length=0;assert.equal(accept(text=>m.validateAbbottNginxText(text,code=>actualNotes.push(code)),text),accept(original,text));assert.deepEqual(actualNotes,originalNotes);inactiveCases++;}assert.equal(inactiveCases,48);
});

test('any unsupported block name is enum mapped without inspecting contents',async()=>{const m=await api();for(const [directive,expected] of [['map',['map']],['sendfile',['sendfile']],['private_block',['other']]])for(const location of [false,true]){const block=directive+' "private-token" { root /private; secret_child "https://secret.invalid/token"; }',body=location?'location / { '+block+' }':block;const result=m.diagnoseAbbottNginxText(base(body));assert.deepEqual(result,expected);assert.doesNotMatch(JSON.stringify(result),/private|secret|https|root/);assert.throws(()=>m.validateAbbottNginxText(base(body)));}});
test('later structural ambiguity discards arbitrary block inventory and authority blocks remain refused',async()=>{const m=await api();for(const tail of ['location ~ /x { return 404; }','location / { server { listen 443 ssl; } }','location / { location /nested { return 404; } }','location / { proxy_pass http://127.0.0.1:3004; }','}']){const text=base('private_block { secret value; } sendfile { hidden value; } '+tail);assert.deepEqual(m.diagnoseAbbottNginxText(text),{reason:'parser_ambiguity'});}assert.deepEqual(m.diagnoseAbbottNginxText(base('server { listen 443 ssl; }')),{reason:'parser_ambiguity'});assert.deepEqual(m.diagnoseAbbottNginxText(base('sendfile on;').replace('return 301','private_block { hidden value; } return 301')),{reason:'parser_ambiguity'});});

test('explicit zero delay is invalid even though omitted delay defaults to zero',async()=>{const m=await api();assert.throws(()=>m.validateAbbottNginxText(zone+base('limit_req zone=perip delay=0;')));assert.doesNotThrow(()=>m.validateAbbottNginxText(zone+base('limit_req zone=perip;')));});
test('fixed fragments reject escaped or concatenated lexical nodes before splice',async()=>{const m=await api();for(const content of ['location "/dashboard/\\t18" { return 404; }','location "/api/dashboard/\\r18" { return 404; }','location "/dashboard/\\n18" { return 404; }','location /sa"fe" { return 404; }','location /safe { proxy_pass http://127.0.0.1:300\\1; }','location /safe { add_header X-Tag "sec\\ret"; }']){const fragments=goodFragments();fragments.set(fixedIncludes[0],content);let reason;assert.throws(()=>m.validateAbbottNginxText(fixedMain(),v=>reason=v,()=>fragments));assert.equal(reason,'include_route');}const fragments=goodFragments();fragments.set(fixedIncludes[0],'location "/safe" { proxy_pass "http://127.0.0.1:3001"; }');assert.doesNotThrow(()=>m.validateAbbottNginxText(fixedMain(),()=>{},()=>fragments));});
test('fixed include acceptance delta is only attested pair with inline-equivalent safe fragments',async()=>{const m=await api(),source=execFileSync('/usr/bin/git',['show','53c6b656ee5ac8e1d8a0e03c664277831074973c:scripts/runtime-release-remote.mjs'],{cwd:new URL('..',import.meta.url),env:{PATH:'/usr/bin:/bin'},encoding:'utf8',stdio:['ignore','pipe','pipe']}),old=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64')),accept=(fn,text)=>{try{fn(text);return true;}catch{return false;}};
 const corpus=['','location / { proxy_pass http://127.0.0.1:3001; }','location = /safe { proxy_pass http://127.0.0.1:3003; }','limit_req zone=perip;','include /other;','location ~ /x { return 404; }','if ($host) { return 404; }','server { listen 443 ssl; }','set $x private;','location /dashboard/018 { return 404; }','location /safe { proxy_pass http://127.0.0.1:3004; }','root /private;'];let unchanged=0;
 for(const body of corpus)for(const text of [base(body),zone+base(body),base('').replace('return 301',body+' return 301'),base('')+'server { listen 80; server_name other.example; '+body+' }',base(body)+'}']){let reads=0;assert.equal(accept(t=>m.validateAbbottNginxText(t,()=>{},()=>{reads++;return goodFragments();}),text),accept(old.validateAbbottNginxText,text));assert.equal(reads,0);unchanged++;}assert.equal(unchanged,60);
 let additions=0;for(const body of corpus){const fragments=goodFragments();fragments.set(fixedIncludes[0],body);const text=zone+fixedMain(),inline=zone+base([...fragments.values()].join('\n'));assert.equal(accept(t=>m.validateAbbottNginxText(t,()=>{},()=>fragments),text),accept(old.validateAbbottNginxText,inline));assert.equal(accept(old.validateAbbottNginxText,text),false);if(accept(old.validateAbbottNginxText,inline))additions++;}assert.equal(additions,4);
});
test('main containing escaped numeric alias refuses before reading the exact include pair',async()=>{const m=await api();for(const literal of ['/dashboard/\\t18','/api/dashboard/\\r18','/dashboard/\\n18']){let reads=0;const snippets=new Map([[fixedIncludes[0],'proxy_pass http://127.0.0.1:3001;'],[fixedIncludes[1],'add_header X-Safe true;']]),text=base('location "'+literal+'" { '+fixedIncludes.map(p=>'include '+p+';').join('')+' }');assert.throws(()=>m.validateAbbottNginxText(text,()=>{},()=>{reads++;return snippets;}));assert.equal(reads,0);}});
test('selected main routing lexical ambiguity refuses with and without includes',async()=>{const m=await api();const bad=['location "/dashboard/\\t18" { return 404; }','location "/api/dashboard/\\r18" { return 404; }','location "/dashboard/\\n18" { return 404; }','location "/safe\\_path" { return 404; }','location /sa"fe" { return 404; }','loca\\tion /safe { return 404; }','location = /safe { proxy_pass "http://127.0.0.1:3001/dashboard/\\t18"; }','location = /safe { proxy_pass "http://127.0.0.1:3001/api/dashboard/\\r18"; }','location /safe { proxy_pass http://127.0.0.1:300\\1; }','location /safe { proxy_pass http://127.0.0.1:3001/sa"fe"; }','location /safe { ret\\urn 404; }','location /safe { add_header Locati\\on /safe; }'];for(const body of bad)for(const include of [false,true]){let reads=0;const text=base(body+(include?fixedIncludes.map(p=>'include '+p+';').join(''):''));assert.throws(()=>m.validateAbbottNginxText(text,()=>{},include?()=>{reads++;return goodFragments();}:null));assert.equal(reads,0);}for(const body of ['location "/safe" { proxy_pass "http://127.0.0.1:3001"; }',"location '/safe' { return '404'; }",'location /safe { add_header X-Tag "safe value"; }'])assert.doesNotThrow(()=>m.validateAbbottNginxText(base(body)));});
test('routing escape matrix fails closed in selected main and fragments without leaking inputs',async()=>{const m=await api();for(const escaped of ['\\t','\\r','\\n','\\v','\\f','\\0','\\x09','\\u0009','\\\\','\\/','\\_'])for(const template of ['location "/dashboard/ESC18" { return 404; }','location = /safe { proxy_pass "http://127.0.0.1:3001/api/dashboard/ESC18"; }','location /safe { add_header X-Tag "ESCsecret-value"; }']){const body=template.replace('ESC',escaped);for(const fragment of [false,true]){let reads=0;const notes=[],map=goodFragments();map.set(fixedIncludes[0],body);assert.throws(()=>m.validateAbbottNginxText(fragment?fixedMain():base(body),r=>notes.push(r),fragment?()=>{reads++;return map;}:null),{message:'ABBOTT_DEPLOY_PREFLIGHT_REFUSED'});assert.equal(reads,fragment?1:0);assert.doesNotMatch(JSON.stringify(notes),/secret|dashboard|http|\\/);}}for(const c of ['\t','\r','\n','\x7f']){const map=goodFragments();map.set(fixedIncludes[0],'location /safe { add_header X-Tag "safe'+c+'secret"; }');assert.throws(()=>m.validateAbbottNginxText(fixedMain(),()=>{},()=>map));}});
test('lexical differential records only intended selected routing refusals and preserves inactive syntax',async()=>{const m=await api(),source=execFileSync('/usr/bin/git',['show','77a17d01743db79ad3aed4edc4a4079e83d7432e:scripts/runtime-release-remote.mjs'],{cwd:new URL('..',import.meta.url),env:{PATH:'/usr/bin:/bin'},encoding:'utf8',stdio:['ignore','pipe','pipe']}),old=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64')),accept=(fn,text)=>{try{fn(text);return true;}catch{return false;}},ambiguous=['location "/dashboard/\\t18" { return 404; }','location "/api/dashboard/\\r18" { return 404; }','location "/dashboard/\\n18" { return 404; }','location "/safe\\_path" { return 404; }','location /sa"fe" { return 404; }','location /safe { proxy_pass http://127.0.0.1:300\\1; }','location /safe { ret\\urn 404; }','location /safe { add_header X-Tag "sec\\ret"; }'];let narrowed=0,unchanged=0;for(const body of ambiguous){assert.equal(accept(old.validateAbbottNginxText,base(body)),true);assert.equal(accept(m.validateAbbottNginxText,base(body)),false);narrowed++;for(const text of [base('').replace('return 301',body+' return 301'),base('')+'server { listen 80; server_name other.example; '+body+' }',base('')+'server { listen 443 ssl; server_name other.example; '+body+' }']){assert.equal(accept(m.validateAbbottNginxText,text),accept(old.validateAbbottNginxText,text));unchanged++;}}for(const body of ['location "/safe" { proxy_pass "http://127.0.0.1:3001"; }',"location '/safe' { return '404'; }",'location /safe { add_header X-Tag "safe value"; }']){assert.equal(accept(old.validateAbbottNginxText,base(body)),true);assert.equal(accept(m.validateAbbottNginxText,base(body)),true);unchanged++;}assert.equal(narrowed,8);assert.equal(unchanged,27);});
const includeReasons=['include_existing_abbott_route','include_existing_3004','include_variable_routing','include_regex_location','include_unsupported_location','include_unsupported_proxy_pass','include_unsupported_return','include_unsupported_add_header','include_unsupported_other','include_authority'];
const includeReasonCases=[['location /dashboard/abbott { return 404; }','include_existing_abbott_route'],['location /dashboard/018 { return 404; }','include_existing_abbott_route'],['location /safe { proxy_pass http://127.0.0.1:3004; }','include_existing_3004'],['location /safe { proxy_pass http://$private; }','include_variable_routing'],['location ~ /safe { return 404; }','include_regex_location'],['location /safe extra { return 404; }','include_unsupported_location'],['location /safe { proxy_pass http://127.0.0.1:3005; }','include_unsupported_proxy_pass'],['location /safe { return 302 /private; }','include_unsupported_return'],['location /safe { add_header Location /private; }','include_unsupported_add_header'],['location /safe { root /private; }','include_unsupported_other'],['private_secret "https://private.invalid/token";','include_unsupported_other'],['server_name private;','include_authority'],['listen 443 ssl;','include_authority'],['server { return 404; }','include_authority'],['include /private;','include_authority'],['location "/safe\\_path" { return 404; }','include_route'],['location /safe {','include_syntax']];
test('fragment rejection retains only finite include-prefixed inner reasons',async()=>{const m=await api();for(const [content,expected]of includeReasonCases)for(const file of fixedIncludes){const snippets=goodFragments(),notes=[];snippets.set(file,content);assert.throws(()=>m.validateAbbottNginxText(fixedMain(),v=>notes.push(v),()=>snippets),{message:'ABBOTT_DEPLOY_PREFLIGHT_REFUSED'});assert.equal(notes.at(-1),expected);assert.doesNotMatch(JSON.stringify(notes),/private|http|\/etc/);}});
test('include reason refinement has zero acceptance or phase-sequence drift',async()=>{const m=await api(),source=execFileSync('/usr/bin/git',['show','257dc2615a8c785750e1eae59557cdae02bdf5f4:scripts/runtime-release-remote.mjs'],{cwd:new URL('..',import.meta.url),env:{PATH:'/usr/bin:/bin'},encoding:'utf8',stdio:['ignore','pipe','pipe']}),old=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64')),run=(fn,text,map)=>{const notes=[];let accepted=true;try{fn(text,r=>notes.push(includeReasons.includes(r)?'include_route':r),()=>map);}catch{accepted=false;}return{accepted,notes};};let comparisons=0;for(const content of [...includeReasonCases.map(([s])=>s),'location /safe { proxy_pass http://127.0.0.1:3001; }','add_header X-Safe true;',''])for(const file of fixedIncludes)for(const text of [fixedMain(),base([...fixedIncludes].reverse().map(p=>'include '+p+';').join('')),base('location /safe { '+fixedIncludes.map(p=>'include '+p+';').join('')+' }')]){const snippets=goodFragments();snippets.set(file,content);assert.deepEqual(run(m.validateAbbottNginxText,text,snippets),run(old.validateAbbottNginxText,text,snippets));comparisons++;}assert.equal(comparisons,120);});
