import test from'node:test';import assert from'node:assert/strict';import{EventEmitter}from'node:events';import{PassThrough}from'node:stream';import{spawn}from'node:child_process';import{createHash}from'node:crypto';
const api=()=>import('./abbott-recovery-transport.mjs').catch(()=>({}));
function fixture(){const child=new EventEmitter();Object.assign(child,{pid:90001,stdin:new PassThrough(),stdout:new PassThrough(),stderr:new PassThrough()});const calls=[],timers=[];let live=true;
  const platform={spawn(binary,args,options){calls.push({binary,args,options});return child;},identity:()=>live?'owned-start':null,kill(pid,signal){calls.push({pid,signal});if(signal==='SIGKILL'){live=false;child.emit('close',null,'SIGKILL');}},setTimeout(fn){timers.push(fn);return fn;},clearTimeout(){}};
  return{child,calls,timers,platform,close(){live=false;child.emit('close',0,null);},replace(){platform.identity=()=> 'other-start';}};
}
test('fixed recovery transport retains control stdin, sends abort, accepts only exact ack and verifies SSH exit',async()=>{const m=await api();assert.equal(typeof m.runRecoveryTransport,'function');const f=fixture(),abort=new AbortController(),input=[];f.child.stdin.on('data',b=>input.push(b.toString()));const result=m.runRecoveryTransport(Buffer.from('export async function run(){}'),{signal:abort.signal,platform:f.platform});abort.abort();f.child.stdout.write('ABBOTT_RECOVERY_ACK REVIEW_REQUIRED\n');f.close();assert.deepEqual(await result,{status:'ABBOTT_RECOVERY_REVIEW_REQUIRED',remoteAcknowledged:true,sshExitVerified:true,pid:90001,start:'owned-start'});assert.match(input.join(''),/^ABBOTT_RECOVERY_SOURCE \d+ [a-f0-9]{64}\n/);assert.match(input.join(''),/RUN\nABORT\n$/);assert.equal(f.child.stdin.writableEnded,false);assert.equal(f.calls[0].binary,'/usr/bin/ssh');assert.ok(f.calls[0].args.includes('ProxyCommand=none'));assert.ok(f.calls[0].args.includes('IdentityAgent=none'));assert.ok(f.calls[0].args.includes('/Users/nafanya/.ssh/beget_ed25519'));});
test('forged oversized secret stderr or late stdout never become acknowledged output',async()=>{const m=await api();for(const mode of['forged','oversized','stderr','late']){const f=fixture(),result=m.runRecoveryTransport(Buffer.from('fixture'),{platform:f.platform});if(mode==='forged')f.child.stdout.write('private token=secret');if(mode==='oversized')f.child.stdout.write('secret'.repeat(300));if(mode==='stderr')f.child.stderr.write('private headers body token');if(mode==='late'){f.child.stdout.write('ABBOTT_RECOVERY_ACK RESTORED\n');f.child.stdout.write('secret');}f.close();const r=await result;assert.equal(r.remoteAcknowledged,false);assert.equal(r.status,'ABBOTT_RECOVERY_UNACKNOWLEDGED');assert.doesNotMatch(JSON.stringify(r),/secret|headers|token/);}});
test('hung SSH receives bounded identity-checked TERM/KILL; missing ack is never cleanup success',async()=>{const m=await api(),f=fixture(),result=m.runRecoveryTransport(Buffer.from('fixture'),{platform:f.platform});f.timers[0]();f.timers[1]();const r=await result;assert.equal(r.status,'ABBOTT_RECOVERY_UNACKNOWLEDGED');assert.equal(r.sshExitVerified,true);assert.deepEqual(f.calls.filter(c=>c.signal),[{pid:90001,signal:'SIGTERM'},{pid:90001,signal:'SIGKILL'}]);});
test('PID replacement refuses termination and cannot claim verified cleanup',async()=>{const m=await api(),f=fixture(),result=m.runRecoveryTransport(Buffer.from('fixture'),{platform:f.platform});f.replace();f.timers[0]();const r=await result;assert.equal(r.sshExitVerified,false);assert.equal(r.remoteAcknowledged,false);assert.equal(f.calls.filter(c=>c.signal).length,0);});
test('pre-aborted request never spawns SSH or serializes source',async()=>{const m=await api(),f=fixture(),abort=new AbortController();abort.abort();const r=await m.runRecoveryTransport(Buffer.from('fixture'),{signal:abort.signal,platform:f.platform});assert.equal(r.status,'ABBOTT_RECOVERY_REFUSED');assert.equal(f.calls.length,0);});
test('valid ack cannot override failing SSH exit or signal',async()=>{const m=await api();for(const [code,signal]of[[1,null],[null,'SIGTERM']]){const f=fixture(),result=m.runRecoveryTransport(Buffer.from('fixture'),{platform:f.platform});f.child.stdout.write('ABBOTT_RECOVERY_ACK RESTORED\n');f.platform.identity=()=>null;f.child.emit('close',code,signal);const r=await result;assert.equal(r.status,'ABBOTT_RECOVERY_UNACKNOWLEDGED');assert.equal(r.remoteAcknowledged,false);}});
async function loader(mode){const {RECOVERY_LOADER}=await api();const child=spawn(process.execPath,['--input-type=module','-e',RECOVERY_LOADER],{env:{},stdio:['pipe','pipe','pipe','pipe']});const source=Buffer.from(mode==='success'?"export async function run(){return 'ABBOTT_RECOVERY_RESTORED'}":"import fs from'node:fs';export async function run(signal){const stopped=new Promise(resolve=>signal.aborted?resolve():signal.addEventListener('abort',resolve,{once:true}));fs.writeSync(3,'ready');await stopped;throw Error('ABBOTT_RECOVERY_REVIEW_REQUIRED')}");const chunks=[],errors=[];child.stdout.on('data',b=>chunks.push(b));child.stderr.on('data',b=>errors.push(b));child.stdin.on('error',()=>{});child.stdio[3].once('data',()=>{if(mode==='abort')child.stdin.write('ABORT\n');if(mode==='eof')child.stdin.end();});let expired=false;const timer=setTimeout(()=>{expired=true;child.kill('SIGKILL');},3000);const closed=new Promise(resolve=>child.on('close',resolve));
  if(mode==='oversized')child.stdin.end('ABBOTT_RECOVERY_SOURCE 1048577 '+'a'.repeat(64)+'\n');
  else if(mode==='truncated')child.stdin.end('ABBOTT_RECOVERY_SOURCE 100 '+'a'.repeat(64)+'\nshort');
  else{child.stdin.write(`ABBOTT_RECOVERY_SOURCE ${source.length} ${createHash('sha256').update(source).digest('hex')}\n`);child.stdin.write(source);if(mode==='pre_abort')child.stdin.write('ABORT\n');else child.stdin.write('RUN\n');}
  await closed;clearTimeout(timer);source.fill(0);assert.equal(expired,false,'owned loader must acknowledge and exit within deadline');assert.equal(Buffer.concat(errors).length,0);let gone=false;try{process.kill(child.pid,0);}catch(e){gone=e.code==='ESRCH';}assert.ok(gone);return Buffer.concat(chunks).toString();
}
test('actual loader accepts strict source frame; EOF/abort acknowledge only after terminal cleanup',async()=>{assert.equal(await loader('success'),'ABBOTT_RECOVERY_ACK RESTORED\n');for(const mode of['abort','eof'])assert.equal(await loader(mode),'ABBOTT_RECOVERY_ACK REVIEW_REQUIRED\n');for(const mode of['pre_abort','oversized','truncated'])assert.equal(await loader(mode),'ABBOTT_RECOVERY_ACK REFUSED\n');});
