import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import vm from'node:vm';import{isDeepStrictEqual}from'node:util';import{createHash,randomUUID}from'node:crypto';
import{RECOVERY_PINS as P}from'./abbott-interrupted-recovery.mjs';
const APP='/var/www/dashboard-abbott',CONTROL='/var/www/.dashboard-abbott-control',BACKUP=`/var/www/dashboard-abbott-backups/${P.old}`,PARK=`/var/www/dashboard-abbott-releases/${P.candidate}-interrupted-recovery`,LOCK='/var/www/.dashboard-abbott-deploy.lock',JOURNAL=`${CONTROL}/interrupted-recovery-${P.candidate}.json`;
function fixture(){
  const nodes=new Map(),fds=new Map(),writes=[],events=[];let ino=1,fd=1,failAt=null,health=true,source=true,hostname=P.hostname;
  const missing=()=>Object.assign(Error('fixture private'),{code:'ENOENT'});
  const put=(p,text='',mode=0o644,gid=0,dir=false)=>nodes.set(p,{text:Buffer.from(text),mode,uid:0,gid,dir,ino:ino++,dev:1,nlink:1,mtimeMs:1,ctimeMs:1});
  const dirs=['/var','/var/www',APP,APP+'/apps',APP+'/apps/abbott',BACKUP,BACKUP+'/apps',BACKUP+'/apps/abbott','/var/www/dashboard-abbott-releases','/var/www/dashboard-abbott-backups',CONTROL,CONTROL+'/'+P.old,CONTROL+'/'+P.candidate];
  for(const p of dirs)put(p,'',p.startsWith(CONTROL)?0o700:p.endsWith('-releases')||p.endsWith('-backups')?0o711:0o755,0,true);
  const old={id:P.old,previousId:null,scope:'abbott',sourceSha:P.oldSha,manifestDigest:P.oldHash},candidate={id:P.candidate,previousId:P.old,scope:'abbott',sourceSha:P.candidateSha,manifestDigest:P.candidateHash};
  for(const r of[old,candidate])put(`${CONTROL}/${r.id}/record.json`,JSON.stringify(r),0o600);
  put(CONTROL+'/current.json',JSON.stringify(old),0o600);
  for(const[p,r]of[[APP,candidate],[BACKUP,old]]){put(p+'/.release-source-sha',r.sourceSha+'\n');put(p+'/.env',"SAFE='fixture'\n"+(r===candidate?"PUPPETEER_EXECUTABLE_PATH='/var/lib/dashboard-abbott/browser-cache-chrome/chrome/linux-146.0.7680.76/chrome-linux64/chrome'\n":''),0o640,P.gid);put(p+'/apps/abbott/server.js',r.sourceSha);}
  put('/etc/nginx/conf.d/dashboard-next.conf','fixed-nginx');put('/proc/sys/kernel/random/boot_id',P.boot);put('/root/.pm2/pm2.pid',String(P.daemon));
  put('/var/www/dashboard/.release-source-sha','8f389a28df1c4b741ec33b7538f0354b74f5a40e');put('/var/www/dashboard-zaruku/.release-source-sha','af1948c8b9a0f70d8696afb9c8abc254408a5daa');
  put('/etc/passwd','dashboard-abbott:x:982:984::/nonexistent:/usr/sbin/nologin\n');
  const proc=(pid,start,cwd,uid,gid)=>{put('/proc/'+pid,'',0o755,0,true);put(`/proc/${pid}/stat`,`${pid} (node) ${['S',...Array(18).fill('0'),start].join(' ')}`);put(`/proc/${pid}/status`,`Uid:\t${uid}\t${uid}\t${uid}\t${uid}\nGid:\t${gid}\t${gid}\t${gid}\t${gid}\n`);put(`/proc/${pid}/cwd`,cwd);};
  for(const[name,id,pid,start,cwd,uid,gid]of[['dashboard-next',1,3722244,'122353749','/var/www/dashboard',0,0],['dashboard-zaruku',2,791065,'131477500','/var/www/dashboard-zaruku/apps/zaruku',984,991],['dashboard-medroche',4,1870897,'139126198','/var/www/dashboard-medroche-releases/13d68b0b2c820ba5d223f254bc4eba6d0cf24418/standalone/apps/site-seo',983,983]]){put(`/root/.pm2/pids/${name}-${id}.pid`,String(pid));proc(pid,start,cwd,uid,gid);}
  proc(P.pid,P.start,APP+'/apps/abbott',P.uid,P.gid);put(`/proc/${P.pid}/fd`,'',0o755,0,true);put(`/proc/${P.pid}/fd/18`,'socket:[999]');put('/proc/net/tcp','header\n0: 0100007F:0BBC 00000000:0000 0A 0 0 0 0 0 999\n');put('/proc/net/tcp6','header\n');
  const maybe=(name)=>{events.push(name);if(failAt===name){failAt=null;throw Error('secret://redact');}};
  const stat=p=>{const n=nodes.get(p);if(!n)throw missing();return{...n,size:n.text.length,isDirectory:()=>n.dir,isFile:()=>!n.dir,isSymbolicLink:()=>Boolean(n.link)};};
  const io={constants:fs.constants,lstatSync(p,opts){if(!nodes.has(p)&&opts?.throwIfNoEntry===false)return;return stat(p);},statSync:stat,existsSync:p=>nodes.has(p),realpathSync(p){if(p.endsWith('/cwd'))return nodes.get(p).text.toString();if(p==='/var/www/dashboard-medroche')return'/var/www/dashboard-medroche-releases/13d68b0b2c820ba5d223f254bc4eba6d0cf24418/standalone';return nodes.get(p)?.link??p;},readFileSync(p,encoding){if(typeof p==='number')p=fds.get(p);const n=nodes.get(p);if(!n)throw missing();return encoding?n.text.toString():Buffer.from(n.text);},openSync(p,flags,mode){if(flags&fs.constants.O_CREAT){if(nodes.has(p))throw Error('exists');put(p,'',mode);writes.push('create:'+p);}else if(!nodes.has(p))throw missing();fds.set(fd,p);return fd++;},fstatSync:n=>stat(fds.get(n)),closeSync:n=>fds.delete(n),fchmodSync(n,mode){nodes.get(fds.get(n)).mode=mode;},fsyncSync(){},readlinkSync:p=>nodes.get(p).text.toString(),readdirSync:p=>[...nodes.keys()].filter(x=>x.startsWith(p+'/')&&!x.slice(p.length+1).includes('/')).map(x=>x.slice(p.length+1)),mkdirSync(p,{mode}){if(nodes.has(p))throw Error('exists');put(p,'',mode,0,true);writes.push('mkdir:'+p);},chmodSync(p,mode){nodes.get(p).mode=mode;},writeFileSync(p,b,opts){if(typeof p==='number')p=fds.get(p);if(opts?.flag==='wx'&&nodes.has(p))throw Error('exists');if(!nodes.has(p))put(p,'',opts?.mode??0o600);nodes.get(p).text=Buffer.from(b);writes.push('write:'+p);},renameSync(a,b){maybe(a===APP?'rename:candidate':a===BACKUP?'rename:backup':'rename:other');if(nodes.has(b)&&b!==JOURNAL)throw Error('exists');const values=[...nodes].filter(([p])=>p===a||p.startsWith(a+'/'));if(!values.length)throw missing();for(const[p]of values)nodes.delete(p);for(const[p,n]of values)nodes.set(b+p.slice(a.length),n);writes.push('rename:'+a);},unlinkSync(p){nodes.delete(p);writes.push('unlink:'+p);},rmdirSync(p){if(io.readdirSync(p).length)throw Error('not empty');nodes.delete(p);writes.push('rmdir:'+p);}};
  let reg={pid:P.pid,status:'online',registration:{pmId:P.pmId,releaseId:P.old,sourceSha:P.oldSha}},snapshotStart=P.start;
  const platform={account:()=>({uid:P.uid,gid:P.gid}),registration:()=>structuredClone(reg),async stop(id){assert.equal(id,P.pmId);maybe('stop');for(const p of[...nodes.keys()])if(p==='/proc/'+reg.pid||p.startsWith('/proc/'+reg.pid+'/'))nodes.delete(p);reg.pid=0;reg.status='stopped';},async assertNoListener(){maybe('listener:stopped');if(reg.pid)throw Error('listener');},async start(control){assert.equal(control,CONTROL+'/'+P.old);maybe('restart');reg.pid=800000;reg.status='online';snapshotStart='99999';proc(reg.pid,snapshotStart,APP+'/apps/abbott',P.uid,P.gid);},snapshot(){return{pid:reg.pid,startTime:snapshotStart,sourceSha:P.oldSha};},async health(){maybe('health:restored');if(!health)throw Error('health');}};
  const tree=(p,r)=>{maybe('attest:'+p);if(io.readFileSync(p+'/.release-source-sha','utf8').trim()!==r.sourceSha||io.readFileSync(p+'/apps/abbott/server.js','utf8')!==r.sourceSha)throw Error('manifest');};
  const context={fs:io,os:{hostname:()=>hostname},createHash:()=>({update(b){this.b=b;return this;},digest(){return Buffer.from(this.b).toString()==='fixed-nginx'?P.nginx:createHash('sha256').update(this.b).digest('hex');}}),randomUUID,isDeepStrictEqual,Buffer,AbortSignal,process:{getuid:()=>0,geteuid:()=>0},verifyAbbottBootstrapSource:()=>{if(!source)throw Error('source');},createRuntimeInstaller:()=>({interruptedRecoveryTools:()=>({readRecord:id=>JSON.parse(io.readFileSync(CONTROL+'/'+id+'/record.json')),attestTree:tree,platform}),inspectActiveRuntime:()=>{tree(APP,old);return old;}}),fetch:async(url,opts)=>{assert.equal(url,'http://127.0.0.1:3004/api/health');assert.equal(opts.redirect,'error');return new Response(health?'{"ok":true,"scope":"abbott","database":"connected"}':'private',{status:health?200:503});},Response};
  vm.createContext(context);const code=fs.readFileSync(new URL('./abbott-interrupted-recovery.mjs',import.meta.url),'utf8').replace(/^import .*;\n/gm,'').replaceAll('export const ','const ').replaceAll('export function ','function ').replaceAll('export async function ','async function ');vm.runInContext(code+'\nthis.run=runRecoverySteps;this.make=createRecoveryAdapter;',context);
  return{nodes,writes,events,platform,io,reg,run:signal=>context.run(context.make([],signal)),fail:name=>{failAt=name;},health:v=>{health=v;},source:v=>{source=v;},hostname:v=>{hostname=v;}};
}
test('real adapter restores backup inode, preserves candidate and verifies old runtime before unlock',async()=>{const f=fixture(),oldIno=f.nodes.get(BACKUP).ino,candidateIno=f.nodes.get(APP).ino;assert.equal(await f.run(),'ABBOTT_RECOVERY_RESTORED');assert.equal(f.nodes.get(APP).ino,oldIno);assert.equal(f.nodes.get(PARK).ino,candidateIno);assert.ok(!f.nodes.has(BACKUP));assert.ok(!f.nodes.has(LOCK));assert.equal(JSON.parse(f.nodes.get(JOURNAL).text).state,'restored');});
test('real adapter rejects host/source/tree/metadata/pointer/process/listener drift before writes',async()=>{
  const changes=[f=>f.hostname('wrong'),f=>f.source(false),f=>f.health(false),f=>f.nodes.get('/proc/sys/kernel/random/boot_id').text=Buffer.from('wrong'),f=>f.reg.pid++,f=>f.reg.registration.pmId++,f=>f.reg.registration.releaseId=P.candidate,f=>f.nodes.get(`/proc/${P.pid}/stat`).text=Buffer.from('bad'),f=>f.nodes.get(`/proc/${P.pid}/status`).text=Buffer.from('Uid: 0 0 0 0\n'),f=>f.nodes.get('/etc/nginx/conf.d/dashboard-next.conf').text=Buffer.from('changed'),f=>f.nodes.get(APP).link='/outside',f=>f.nodes.get(BACKUP).uid=2,f=>f.nodes.get(CONTROL+'/current.json').text=Buffer.from('{}'),f=>f.nodes.get(APP+'/.env').mode=0o644,f=>f.nodes.get(BACKUP+'/apps/abbott/server.js').text=Buffer.from('changed'),f=>f.nodes.get(APP+'/apps/abbott/server.js').text=Buffer.from('changed'),f=>f.nodes.get('/proc/net/tcp').text=Buffer.from('header\n0: 00000000:0BBC 00000000:0000 0A 0 0 0 0 0 999\n'),f=>f.nodes.set(LOCK,{...f.nodes.get(APP)}),f=>f.nodes.set(JOURNAL,{...f.nodes.get(CONTROL+'/current.json')}),f=>f.nodes.get(`/root/.pm2/pids/dashboard-next-1.pid`).text=Buffer.from('1')];
  for(const change of changes){const f=fixture();change(f);await assert.rejects(f.run(),/^Error: ABBOTT_RECOVERY_REFUSED$/);assert.deepEqual(f.writes,[]);assert.ok(!f.events.includes('stop'));}
});
for(const point of ['stop','listener:stopped','rename:candidate','rename:backup','restart','health:restored'])test('real adapter compensates '+point+' without restarting candidate',async()=>{const f=fixture();f.fail(point);await assert.rejects(f.run(),/^Error: ABBOTT_RECOVERY_REVIEW_REQUIRED$/);assert.equal(f.reg.pid,0);assert.equal(f.io.readFileSync(APP+'/.release-source-sha','utf8').trim(),P.candidateSha);assert.equal(f.io.readFileSync(BACKUP+'/.release-source-sha','utf8').trim(),P.oldSha);assert.ok(f.nodes.has(LOCK));assert.equal(JSON.parse(f.nodes.get(JOURNAL).text).state,'review_required');});
test('real adapter rejects candidate env, UID/GID, record hashes and symlink drift with zero writes',async()=>{
  for(const change of[
    f=>{f.nodes.get(APP+'/.env').text=Buffer.from("PUPPETEER_EXECUTABLE_PATH='/private'\n");},
    f=>{f.nodes.get(APP+'/.env').gid=0;},
    f=>{f.nodes.get(`/proc/${P.pid}/status`).text=Buffer.from('Uid: 982 982 982 982\nGid: 0 0 0 0\n');},
    f=>{const n=f.nodes.get(CONTROL+'/'+P.candidate+'/record.json'),r=JSON.parse(n.text);r.manifestDigest='a'.repeat(64);n.text=Buffer.from(JSON.stringify(r));},
    f=>{const n=f.nodes.get(CONTROL+'/'+P.old+'/record.json'),r=JSON.parse(n.text);r.sourceSha=P.candidateSha;n.text=Buffer.from(JSON.stringify(r));},
    f=>{f.nodes.get(CONTROL).link='/outside';},
    f=>{f.nodes.get(BACKUP).link='/outside';},
    f=>{f.nodes.get('/etc/nginx/conf.d/dashboard-next.conf').nlink=2;},
  ]){const f=fixture();change(f);await assert.rejects(f.run(),/^Error: ABBOTT_RECOVERY_REFUSED$/);assert.deepEqual(f.writes,[]);}
});
test('start error after spawning and post-start identity failure both stop only captured old runtime',async()=>{
  for(const point of['start_return','identity']){const f=fixture();if(point==='start_return'){const start=f.platform.start;f.platform.start=async c=>{await start(c);throw Error('private');};}else f.platform.snapshot=()=>({pid:f.reg.pid,startTime:'99999',sourceSha:P.candidateSha});
    await assert.rejects(f.run(),/^Error: ABBOTT_RECOVERY_REVIEW_REQUIRED$/);assert.equal(f.reg.pid,0);assert.ok(f.nodes.has(LOCK));assert.equal(f.io.readFileSync(APP+'/.release-source-sha','utf8').trim(),P.candidateSha);assert.equal(f.io.readFileSync(BACKUP+'/.release-source-sha','utf8').trim(),P.oldSha);
  }
});
test('actual rename cancellation compensates both layouts and retains lock',async()=>{
  for(const point of['stop','first','second','restart']){const f=fixture(),abort=new AbortController();if(point==='stop'||point==='restart'){const method=point==='stop'?'stop':'start',original=f.platform[method];f.platform[method]=async arg=>{await original(arg);abort.abort();};}else{const rename=f.io.renameSync;f.io.renameSync=(a,b)=>{rename(a,b);if(point==='first'&&a===APP&&b===PARK||point==='second'&&a===BACKUP&&b===APP)abort.abort();};}
    await assert.rejects(f.run(abort.signal),/^Error: ABBOTT_RECOVERY_REVIEW_REQUIRED$/);assert.equal(f.reg.pid,0);assert.equal(f.io.readFileSync(APP+'/.release-source-sha','utf8').trim(),P.candidateSha);assert.equal(f.io.readFileSync(BACKUP+'/.release-source-sha','utf8').trim(),P.oldSha);assert.ok(f.nodes.has(LOCK));
  }
});
test('compensation failure preserves both trees in their verified slots, stopped process and root-only journal',async()=>{
  const f=fixture();f.fail('health:restored');const rename=f.io.renameSync;f.io.renameSync=(a,b)=>{if(a===APP&&b===BACKUP)throw Error('private');rename(a,b);};
  await assert.rejects(f.run(),/^Error: ABBOTT_RECOVERY_REVIEW_REQUIRED$/);assert.equal(f.reg.pid,0);assert.equal(f.io.readFileSync(APP+'/.release-source-sha','utf8').trim(),P.oldSha);assert.equal(f.io.readFileSync(PARK+'/.release-source-sha','utf8').trim(),P.candidateSha);assert.equal(f.nodes.get(LOCK).mode,0o700);assert.equal(f.nodes.get(JOURNAL).mode,0o600);assert.equal(JSON.parse(f.nodes.get(JOURNAL).text).state,'review_required');
});
test('control file replacement between metadata proof and descriptor open refuses before writes',async()=>{
  const f=fixture(),open=f.io.openSync;let swapped=false;f.io.openSync=(p,...args)=>{if(p===CONTROL+'/current.json'&&!swapped){swapped=true;f.nodes.get(p).ino+=10000;}return open(p,...args);};
  await assert.rejects(f.run(),/^Error: ABBOTT_RECOVERY_REFUSED$/);assert.deepEqual(f.writes,[]);
});
