import test from'node:test';import assert from'node:assert/strict';
const api=()=>import('./abbott-recovery-diagnostics.mjs').catch(()=>({}));
test('SSH standard-warning categories require anchored exact families, not generic warning prefixes',async()=>{const m=await api();for(const text of['Warning: private token\n','private Pseudo-terminal will not be allocated because stdin is not a terminal.\n',"Warning: Permanently added private (ED25519) to the list of known hosts.\n",'(node:private) ExperimentalWarning: secret\n','bash: warning: setlocale: private token\n'])assert.equal(m.classifyStartupStderr(Buffer.from(text)),'unknown');});
test('bounded startup stderr classifier returns only closed categories despite secret injection',async()=>{const m=await api();assert.equal(typeof m.classifyStartupStderr,'function');const samples={sudo_hostname:'sudo: unable to resolve host private: Name or service not known\n',node_syntax:'[eval1]:1\nprivate\nSyntaxError: private token\n',node_warning:'(node:123) ExperimentalWarning: private token /path\n',permission:'Permission denied (publickey).\n',missing_binary:'/usr/bin/env: /private/node: No such file or directory\n',ssh_known_host:"Warning: Permanently added 'private token' (ED25519) to the list of known hosts.\n",ssh_tty:'Pseudo-terminal will not be allocated because stdin is not a terminal.\n',locale_warning:'bash: warning: setlocale: LC_ALL: cannot change locale (private)'};for(const[expected,text]of Object.entries(samples)){const buffer=Buffer.from(text);assert.equal(m.classifyStartupStderr(buffer),expected);assert.equal(buffer.toString(),text);}for(const value of[Buffer.from('private token'),Buffer.from('Warning: private\0'),Buffer.alloc(8193,65),Buffer.from([0xff]),{stderr:'secret'},Buffer.from(samples.node_warning+samples.node_syntax)])assert.equal(m.classifyStartupStderr(value),'unknown');});
test('recovery diagnostics render only closed status/stage/reason pairs',async()=>{
 const m=await api();assert.equal(typeof m.formatRecoveryDiagnostic,'function');
 for(const [stage,reasons]of Object.entries(m.RECOVERY_REASONS))for(const reason of reasons){const line=m.formatRecoveryDiagnostic({status:'ABBOTT_RECOVERY_UNACKNOWLEDGED',diagnostic:{stage,reason},pid:123,start:'private',stderr:'private'});assert.equal(line,`ABBOTT_RECOVERY_UNACKNOWLEDGED stage=${stage} reason=${reason}\n`);}
 for(const input of[null,{}, {status:'private',diagnostic:{stage:'private',reason:'secret'}},{status:'ABBOTT_RECOVERY_REFUSED',diagnostic:{stage:'source_write',reason:'nonzero'}}]){const line=m.formatRecoveryDiagnostic(input);assert.doesNotMatch(line,/private|secret|123/);assert.match(line,/stage=unknown reason=unknown\n$/);}
});
test('acknowledgements reject forged status-stage pairs and secret-bearing extra fields',async()=>{const m=await api();assert.deepEqual(m.parseRecoveryAck('ABBOTT_RECOVERY_ACK REFUSED remote_preflight refused\n'),{status:'ABBOTT_RECOVERY_REFUSED',diagnostic:{stage:'remote_preflight',reason:'refused'}});for(const text of['ABBOTT_RECOVERY_ACK RESTORED remote_preflight refused\n','ABBOTT_RECOVERY_ACK REFUSED remote_startup secret\n','ABBOTT_RECOVERY_ACK RESTORED complete none\nprivate','ABBOTT_RECOVERY_ACK REFUSED private token\n','ABBOTT_RECOVERY_ACK RESTORED\n'])assert.equal(m.parseRecoveryAck(text),null);});
