import test from'node:test';import assert from'node:assert/strict';import{EventEmitter}from'node:events';import{PassThrough}from'node:stream';import{spawn,execFileSync}from'node:child_process';
const api=()=>import('./probe-abbott-startup-stage.mjs').catch(()=>({}));
const transport=()=>import('./abbott-recovery-transport.mjs');
function fixture(){const child=new EventEmitter();Object.assign(child,{pid:90001,exitCode:null,signalCode:null,stdin:new PassThrough(),stdout:new PassThrough(),stderr:new PassThrough()});let live=true;const calls=[],timers=[];return{child,calls,timers,platform:{spawn(...args){calls.push(args);return child;},identity:()=>live?'owned-start':null,kill(_pid,signal){if(signal==='SIGKILL'){live=false;child.signalCode=signal;child.emit('close',null,signal);}},setTimeout(fn){timers.push(fn);return fn;},clearTimeout(){}},close(code=0,signal=null){live=false;child.exitCode=code;child.signalCode=signal;child.emit('close',code,signal);}};}
const outputs={ssh:'',node:'ABBOTT_STARTUP_NODE_OK\n',loader:'ABBOTT_RECOVERY_READY\nABBOTT_RECOVERY_ACK REFUSED ack_framing malformed\n'};
test('verified nonzero or signal exit outranks secret stderr for every startup stage',async()=>{
 const m=await transport(),wrapper=await api();
 for(const stage of['ssh','node','loader'])for(const signal of[null,'SIGTERM'])for(const warning of['private token https://private.invalid/?token=private\n','Pseudo-terminal will not be allocated because stdin is not a terminal.\n']){
  const f=fixture(),evidence={record(){},finish:()=>({identityCaptured:true,exitObserved:true,exitVerified:true})};
  const result=wrapper.runStartupStage(stage,{evidence,transport:(name,options)=>m.runRecoveryStartupStage(name,{...options,platform:f.platform})});
  f.child.stdout.write(outputs[stage]);f.child.stderr.write(warning);
  f.close(signal?null:255,signal);
  const line=await result;assert.equal(line,`ABBOTT_STARTUP_STAGE stage=${stage} result=exit_nonzero category=none\n`);assert.doesNotMatch(line,/private|token|255|SIGTERM|terminal/);
 }
});
test('unverified exit outranks nonzero and secret stderr',async()=>{
 const m=await transport(),f=fixture();const result=m.runRecoveryStartupStage('ssh',{platform:f.platform});
 f.child.stderr.write('private token');f.platform.identity=()=> 'replacement';f.close(255);
 assert.deepEqual((await result).startup,{stage:'ssh',result:'cleanup_unverified',category:'none'});
});
test('deadline clean exit reports timeout, signal exit reports nonzero, and failed evidence cannot remain clean',async()=>{const m=await transport();for(const forced of[false,true]){const f=fixture(),identity=f.platform.identity;let first=true;f.platform.identity=()=>{if(first){first=false;throw Error('private');}return identity();};const result=m.runRecoveryStartupStage('ssh',{platform:f.platform});f.timers[0]();if(forced)f.timers[1]();else f.close();assert.equal((await result).startup.result,forced?'exit_nonzero':'timeout');}const g=fixture();const evidenceFail=m.runRecoveryStartupStage('ssh',{platform:g.platform,onEvidence:r=>{if(r.exit)throw Error('private');}});g.close();assert.equal((await evidenceFail).startup.result,'cleanup_unverified');});
test('forged matrix summaries cannot expose values or claim clean, and invalid stage never spawns',async()=>{const m=await api(),t=await transport();for(const startup of[{stage:'private',result:'clean',category:'none'},{stage:'ssh',result:'private',category:'none'},{stage:'ssh',result:'stderr_known_category',category:'private'}]){const evidence={record(){},finish:()=>({identityCaptured:true,exitObserved:true,exitVerified:true})};const line=await m.runStartupStage('ssh',{evidence,transport:async()=>({status:'ABBOTT_RECOVERY_RESTORED',diagnostic:{stage:'complete',reason:'none'},remoteAcknowledged:true,sshExitVerified:true,startup})});assert.equal(line,'ABBOTT_STARTUP_STAGE stage=ssh result=unexpected_output category=none\n');}const f=fixture();await t.runRecoveryStartupStage('private',{platform:f.platform});assert.equal(f.calls.length,0);});
test('loader-only stage refuses missing or forged terminal output and sends no source',async()=>{const m=await transport();for(const output of['ABBOTT_RECOVERY_READY\n','ABBOTT_RECOVERY_READY\nABBOTT_RECOVERY_ACK RESTORED complete none\n','private']){const f=fixture(),sent=[];f.child.stdin.on('data',b=>sent.push(b));const result=m.runRecoveryStartupStage('loader',{platform:f.platform});f.child.stdout.write(output);f.close();assert.equal((await result).startup.result,'unexpected_output');assert.equal(sent.length,0);}});
test('each fixed startup stage reuses exact SSH authority, sends no source/RUN and verifies cleanup',async()=>{const m=await transport();assert.equal(typeof m.runRecoveryStartupStage,'function');let prefix;for(const stage of['ssh','node','loader']){const f=fixture(),sent=[];f.child.stdin.on('data',b=>sent.push(b));const result=m.runRecoveryStartupStage(stage,{platform:f.platform});const args=f.calls[0][1];if(prefix)assert.deepEqual(args.slice(0,-1),prefix);prefix=args.slice(0,-1);if(stage==='loader'){assert.equal(f.child.stdin.writableEnded,false);f.child.stdout.write('ABBOTT_RECOVERY_READY\n');assert.equal(f.child.stdin.writableEnded,true);f.child.stdout.write('ABBOTT_RECOVERY_ACK REFUSED ack_framing malformed\n');}else f.child.stdout.write(outputs[stage]);f.close();const r=await result;assert.deepEqual(r.startup,{stage,result:'clean',category:'none'});assert.equal(r.sshExitVerified,true);assert.equal(sent.length,0);}});
test('startup stages refuse secret stderr, forged output, nonzero, timeout and unverified cleanup with closed results',async()=>{const m=await transport();assert.equal(typeof m.runRecoveryStartupStage,'function');for(const mode of['known','unknown','forged','nonzero','timeout','unverified']){const f=fixture(),result=m.runRecoveryStartupStage('node',{platform:f.platform});if(mode==='known')f.child.stderr.write('Pseudo-terminal will not be allocated because stdin is not a terminal.\n');if(mode==='unknown')f.child.stderr.write('private token');if(mode==='forged')f.child.stdout.write('private forged sentinel');if(mode==='timeout'){f.timers[0]();f.close();}else if(mode==='unverified'){f.platform.identity=()=> 'replacement';for(const timer of f.timers.slice())timer();}else f.close(mode==='nonzero'?1:0);const r=await result;assert.equal(r.startup.result,{known:'stderr_known_category',unknown:'stderr_unknown',forged:'unexpected_output',nonzero:'exit_nonzero',timeout:'timeout',unverified:'cleanup_unverified'}[mode]);assert.doesNotMatch(JSON.stringify(r.startup),/private|token|replacement|90001|owned-start/);if(mode==='unverified')f.close();}});
test('matrix wrapper permits only separate fixed stages and never emits identity/raw fields',async()=>{const m=await api();assert.equal(typeof m.runStartupStage,'function');for(const stage of['ssh','node','loader']){let finished=false;const evidence={record(){},finish(){finished=true;return{identityCaptured:true,exitObserved:true,exitVerified:true};}};const result=await m.runStartupStage(stage,{evidence,transport:async(_,{onEvidence})=>{onEvidence({pid:123,start:'private',exit:true,exitVerified:true,stage:'complete'});return{status:'ABBOTT_RECOVERY_RESTORED',diagnostic:{stage:'complete',reason:'none'},remoteAcknowledged:true,sshExitVerified:true,startup:{stage,result:'clean',category:'none'},pid:123,stderr:'private'};}});assert.equal(result,`ABBOTT_STARTUP_STAGE stage=${stage} result=clean category=none\n`);assert.equal(finished,true);}assert.throws(()=>m.validateStartupStage(['private']),/^Error: ABBOTT_STARTUP_STAGE_REFUSED$/);assert.throws(()=>m.validateStartupStage(['ssh','node']),/^Error: ABBOTT_STARTUP_STAGE_REFUSED$/);});
test('each exact stage command tokenizes locally without stderr and leaves no child',async()=>{const m=await transport();assert.equal(typeof m.runRecoveryStartupStage,'function');for(const stage of['ssh','node','loader']){let child;const identity=pid=>{try{return execFileSync('/bin/ps',['-p',String(pid),'-o','lstart='],{encoding:'utf8',timeout:1000,stdio:['ignore','pipe','ignore']}).trim()||null;}catch{return null;}};const platform={spawn(_binary,args,options){child=spawn('/bin/sh',['-c',args.at(-1).replace('/usr/bin/node',process.execPath).replace('/bin/true','/usr/bin/true')],options);return child;},identity,kill:(pid,signal)=>process.kill(pid,signal),setTimeout,clearTimeout};const result=m.runRecoveryStartupStage(stage,{platform});const timer=setTimeout(()=>child.kill('SIGKILL'),3000);try{const r=await result;assert.deepEqual(r.startup,{stage,result:'clean',category:'none'});assert.throws(()=>process.kill(child.pid,0),e=>e.code==='ESRCH');}finally{clearTimeout(timer);}}});
