import test from'node:test';import assert from'node:assert/strict';import{EventEmitter}from'node:events';import{PassThrough}from'node:stream';import fs from'node:fs';import{createHash}from'node:crypto';import{spawn}from'node:child_process';
const api=()=>import('./read-abbott-nginx.mjs').catch(()=>({}));
const GOOD='ABBOTT_NGINX_UNSUPPORTED names=proxy_redirect,sendfile\n',OTHER='ABBOTT_NGINX_UNSUPPORTED names=other\n';
const refused=reason=>'ABBOTT_NGINX_READ_REFUSED reason='+reason+'\n';
test('refusal frames are closed and distinct from analyzed unknown names',async()=>{const m=await api();const line='ABBOTT_NGINX_READ_REFUSED reason=metadata\n';assert.equal(m.parseNginxNamesFrame(Buffer.from(line)),line);assert.equal(m.parseNginxNamesFrame(Buffer.from(OTHER)),OTHER);for(const text of ['ABBOTT_NGINX_READ_REFUSED reason=private_token\n',line+OTHER,line+'secret'])assert.equal(m.parseNginxNamesFrame(Buffer.from(text)),'ABBOTT_NGINX_READ_REFUSED reason=framing\n');});
function fixture(){const child=new EventEmitter();Object.assign(child,{pid:99999,exitCode:null,signalCode:null,stdin:new PassThrough(),stdout:new PassThrough(),stderr:new PassThrough()});let live=true;const timers=[],cleared=[],calls=[],rows=[],sent=[];child.stdin.on('data',b=>sent.push(Buffer.from(b)));
 const platform={spawn(...args){calls.push(args);return child;},identity:()=>live?'Tue Sep 15 12:00:00 2026':null,kill(pid,signal){calls.push({pid,signal});if(signal==='SIGKILL')close(null,signal);},setTimeout(fn){timers.push(fn);return fn;},clearTimeout(fn){cleared.push(fn);}};
 function close(code=0,signal=null){live=false;child.exitCode=code;child.signalCode=signal;child.emit('exit',code,signal);child.emit('close',code,signal);}
 return{child,platform,timers,cleared,calls,rows,sent,close,options:{platform,onEvidence:row=>rows.push(row)}};
}
test('only bounded canonical sorted unique enum frames parse; no args or secret stderr escape',async()=>{const m=await api();assert.equal(typeof m.parseNginxNamesFrame,'function');assert.equal(m.parseNginxNamesFrame(Buffer.from(GOOD)),GOOD);for(const text of [GOOD+GOOD,GOOD.trim(),GOOD+'private-token','ABBOTT_NGINX_UNSUPPORTED names=sendfile,proxy_redirect\n','ABBOTT_NGINX_UNSUPPORTED names=sendfile,sendfile\n','ABBOTT_NGINX_UNSUPPORTED names=private_token\n','x'.repeat(4097)])assert.equal(m.parseNginxNamesFrame(Buffer.from(text)),refused('framing'));});
test('every fixed common name including digits round-trips individually and as one batch',async()=>{const m=await api(),{abbottNginxDiagnosticNames}=await import('./runtime-release-remote.mjs'),names=abbottNginxDiagnosticNames();for(const list of [...names.map(n=>[n]),names]){const line='ABBOTT_NGINX_UNSUPPORTED names='+list.join(',')+'\n';assert.ok(Buffer.byteLength(line)<=4096);assert.equal(m.parseNginxNamesFrame(Buffer.from(line)),line);}});
test('fixed caller proves owned SSH identity before source; all stderr/nonzero/extra output refuse',async()=>{const m=await api();assert.equal(typeof m.runNginxReadTransport,'function');for(const mode of ['good','stderr','nonzero','extra']){const f=fixture(),pending=m.runNginxReadTransport(Buffer.from('source'),f.options);assert.equal(f.calls[0][0],'/usr/bin/ssh');assert.deepEqual(f.calls[0][2],{cwd:'/',env:{},stdio:['pipe','pipe','pipe']});for(const value of ['LogLevel=ERROR','HostName=5.35.85.218','User=root','StrictHostKeyChecking=yes','IdentityAgent=none','ProxyCommand=none','ControlMaster=no'])assert.ok(f.calls[0][1].includes(value));assert.ok(f.rows.some(r=>r.start));f.child.stdout.write(GOOD);if(mode==='stderr')f.child.stderr.write('private-token');if(mode==='extra')f.child.stdout.write('private-token');f.close(mode==='nonzero'?255:0);assert.deepEqual(await pending,{line:mode==='good'?GOOD:refused(mode==='extra'?'framing':'transport'),exitVerified:true});assert.doesNotMatch(JSON.stringify(f.rows),/private/);}});
test('initial proof failure, PID reuse, abort and late close retain bounded cleanup with no wrong kill',async()=>{const m=await api();assert.equal(typeof m.runNginxReadTransport,'function');for(const mode of ['proof','reuse','abort']){const f=fixture(),abort=new AbortController();if(mode==='proof')f.platform.identity=()=>{throw Error('private-token');};const pending=m.runNginxReadTransport(Buffer.from('source'),{...f.options,signal:abort.signal});if(mode==='proof')assert.equal(f.sent.length,0);if(mode==='reuse')f.platform.identity=()=> 'replacement';if(mode==='abort')abort.abort();for(const fn of [...f.timers])fn();const result=await pending;assert.equal(result.line,refused(mode==='abort'?'transport':'cleanup'));if(mode!=='abort'){assert.equal(result.exitVerified,false);assert.equal(f.calls.filter(c=>c.signal).length,0);assert.equal(f.cleared.length,0);f.platform.identity=()=>null;f.close();assert.ok(f.cleared.length);}assert.doesNotMatch(JSON.stringify(f.rows),/private/);}});
test('evidence failure cannot claim success, and all source buffers are zeroed',async()=>{const m=await api();assert.equal(typeof m.runNginxReadWithEvidence,'function');for(const verified of [false,true]){const input=Buffer.from('source'),line=await m.runNginxReadWithEvidence(input,{transport:async()=>({line:GOOD,exitVerified:true}),evidence:{record(){},finish(){return{identityCaptured:true,exitObserved:true,exitVerified:verified};}}});assert.equal(line,verified?GOOD:refused('cleanup'));assert.ok(input.every(b=>b===0));}});
async function inert(script,input,args=[]){const child=spawn(process.execPath,args.length?args:['--input-type=module','-e',script],{cwd:'/',env:{},stdio:['pipe','pipe','pipe']});const chunks=[],errors=[];child.stdout.on('data',b=>chunks.push(b));child.stderr.on('data',b=>errors.push(b));child.stdin.on('error',()=>{});const timer=setTimeout(()=>child.kill('SIGKILL'),3000);const closed=new Promise(resolve=>child.on('close',(status,signal)=>resolve({status,signal})));child.stdin.end(input);const result=await closed;clearTimeout(timer);assert.equal(result.signal,null);assert.equal(Buffer.concat(errors).length,0);assert.throws(()=>process.kill(child.pid,0),{code:'ESRCH'});const output=Buffer.concat(chunks).toString();for(const b of [...chunks,...errors])b.fill(0);return{...result,output};}
test('source frame hashes are fixed and exact; caller cannot send extra or modified modules',async()=>{const m=await api(),sources=Object.fromEntries([['analysis','runtime-release-remote.mjs'],['reader','abbott-nginx-readonly.mjs']].map(([key,file])=>[key,fs.readFileSync(new URL('./'+file,import.meta.url))]));for(const[key,b]of Object.entries(sources))assert.equal(createHash('sha256').update(b).digest('hex'),m.NGINX_SOURCE_HASHES[key]);const frame=m.buildNginxReadInput(sources);assert.ok(frame.length<262144);frame.fill(0);for(const key of Object.keys(sources))assert.throws(()=>m.buildNginxReadInput({...sources,[key]:Buffer.from('private-token')}));assert.throws(()=>m.buildNginxReadInput({...sources,extra:Buffer.alloc(1)}));});
test('real inert loader uses canonical newlines and emits only bounded sorted names',async()=>{const m=await api(),sources={analysis:Buffer.from('export const abbottNginxDiagnosticNames=()=>["other","proxy_redirect","sendfile"];'),reader:Buffer.from('import "./runtime-release-remote.mjs";export const readAbbottNginxNames=()=>["proxy_redirect","sendfile"];'.replace('"./runtime-release-remote.mjs"',"'./runtime-release-remote.mjs'"))};let script='delete process.env.__CF_USER_TEXT_ENCODING;'+m.NGINX_READ_LOADER.replace('process.getuid()!==0','false');for(const[key,b]of Object.entries(sources))script=script.replace(m.NGINX_SOURCE_HASHES[key],createHash('sha256').update(b).digest('hex'));const frame=JSON.stringify(Object.fromEntries(Object.entries(sources).map(([key,b])=>[key,b.toString('base64')])));assert.equal((await inert(script,frame)).output,GOOD);for(const input of ['private-token',frame+'\n',frame.replace('{','{"reader":"c2VjcmV0",'),'x'.repeat(262145)])assert.equal((await inert(script,input)).output,refused('source_frame'));});
test('CLI rejects caller arguments before SSH, returns no raw errors and reaps',async()=>{const file=new URL('./read-abbott-nginx.mjs',import.meta.url).pathname,r=await inert('',null,[file,'private-token']);assert.equal(r.status,1);assert.equal(r.output,refused('local_authority'));});
test('caller retains INT TERM HUP ownership through final cleanup and reader has no host commands',()=>{const caller=fs.readFileSync(new URL('./read-abbott-nginx.mjs',import.meta.url),'utf8'),reader=fs.readFileSync(new URL('./abbott-nginx-readonly.mjs',import.meta.url),'utf8');assert.equal((caller.match(/\['SIGINT','SIGTERM','SIGHUP'\]/g)??[]).length,3);assert.doesNotMatch(reader,/child_process|execFile|spawn|fetch\(|https?:|writeFile|mkdir|unlink|rename|process\.env|readFileSync/);});

test('successful other and explicit reader refusals retain verified cleanup, never conflate',async()=>{const m=await api();for(const line of [OTHER,refused('metadata'),refused('parser_ambiguity')]){const f=fixture(),input=Buffer.from('source'),pending=m.runNginxReadWithEvidence(input,{transport:(b,opts)=>m.runNginxReadTransport(b,{...opts,platform:f.platform}),evidence:{record(){},finish(){return{identityCaptured:true,exitObserved:true,exitVerified:true};}}});f.child.stdout.write(line);f.close();assert.equal(await pending,line);assert.ok(input.every(b=>b===0));}});
test('verified cancellation is aborted, while unverified cancellation remains cleanup',async()=>{const m=await api();for(const verified of [true,false]){const signal=new AbortController(),input=Buffer.from('source');const line=await m.runNginxReadWithEvidence(input,{signal:signal.signal,transport:async()=>{signal.abort();return{line:refused('aborted'),exitVerified:verified};},evidence:{record(){},finish(){return{identityCaptured:true,exitObserved:true,exitVerified:verified};}}});assert.equal(line,refused(verified?'aborted':'cleanup'));assert.ok(input.every(b=>b===0));}});

test('every refusal reason is closed; forged error fields cannot become reason text',async()=>{const m=await api();for(const reason of m.NGINX_READ_REASONS){const line=refused(reason);assert.equal(m.parseNginxNamesFrame(Buffer.from(line)),line);for(const suffix of [' private-token','?token=private','\r','\\0'])assert.equal(m.parseNginxNamesFrame(Buffer.from(refused(reason+suffix))),refused('framing'));}});
test('real loader distinguishes authority, import, reader failures and successful unknown',async()=>{const m=await api();for(const [body,expected] of [
 ['return ["other"];',OTHER],
 ['return {reason:"metadata"};',refused('metadata')],
 ['return {reason:"parser_ambiguity"};',refused('parser_ambiguity')],
 ['return {reason:"private_secret",message:"private-token"};',refused('reader')],
 ['throw Error("private-token");',refused('reader')],
 ['return {reason:"metadata",value:"private-token"};',refused('reader')],
 ]){const sources={analysis:Buffer.from('export const abbottNginxDiagnosticNames=()=>["other"];'),reader:Buffer.from("import './runtime-release-remote.mjs';export function readAbbottNginxNames(){"+body+"}")};let script='delete process.env.__CF_USER_TEXT_ENCODING;'+m.NGINX_READ_LOADER.replace('process.getuid()!==0','false');for(const[k,b]of Object.entries(sources))script=script.replace(m.NGINX_SOURCE_HASHES[k],createHash('sha256').update(b).digest('hex'));const frame=JSON.stringify(Object.fromEntries(Object.entries(sources).map(([k,b])=>[k,b.toString('base64')])));assert.equal((await inert(script,frame)).output,expected);assert.equal((await inert(script.replace("reason='remote_import';","reason='remote_import';throw Error('private-token');"),frame)).output,refused('remote_import'));assert.equal((await inert(script.replace('if(done||false||','if(done||true||'),frame)).output,refused('remote_authority'));}});
