#!/bin/bash
set -euo pipefail

VPS="${VPS:-beget}"
REMOTE_ENV_PATH="${REMOTE_ENV_PATH:-/var/www/www-root/data/.production.env}"
TARGET_FILE="${1:-.env.production}"
DEFAULT_BASE_URL="${DEFAULT_BASE_URL:-https://dashboards.adreports.ru}"

REMOTE_ENV_CONTENT="$(ssh "$VPS" "cat '$REMOTE_ENV_PATH'")"

MYSQL_PORT_VALUE="3306"
MYSQL_USER_VALUE=""
MYSQL_PASSWORD_VALUE=""
MYSQL_DB_VALUE="report_bd"
MYSQL_DB_STAT_VALUE=""
ADMIN_EMAIL_VALUE=""
ADMIN_PASSWORD_VALUE=""
AUTH_SECRET_VALUE=""
AI_SUMMARY_API_KEY_VALUE=""
AI_SUMMARY_MODEL_VALUE="gemini-2.5-flash"
AI_SUMMARY_BASE_URL_VALUE="https://generativelanguage.googleapis.com/v1beta/openai"
AI_SUMMARY_TIMEOUT_MS_VALUE="1800"
AI_SUMMARY_CACHE_TTL_MS_VALUE="300000"
NEXT_PUBLIC_BASE_URL_VALUE=""

while IFS= read -r raw_line; do
  line="${raw_line%$'\r'}"
  if [[ -z "$line" || "$line" == \#* || "$line" != *=* ]]; then
    continue
  fi

  key="${line%%=*}"
  value="${line#*=}"

  if [[ "$value" == '"'*'"' ]]; then
    value="${value:1:${#value}-2}"
  elif [[ "$value" == "'"*"'" ]]; then
    value="${value:1:${#value}-2}"
  fi

  case "$key" in
    MYSQL_PORT) MYSQL_PORT_VALUE="$value" ;;
    MYSQL_USER) MYSQL_USER_VALUE="$value" ;;
    MYSQL_PASSWORD) MYSQL_PASSWORD_VALUE="$value" ;;
    MYSQL_DB) MYSQL_DB_VALUE="$value" ;;
    MYSQL_DB_STAT) MYSQL_DB_STAT_VALUE="$value" ;;
    DASHBOARD_ADMIN_EMAIL) ADMIN_EMAIL_VALUE="$value" ;;
    DASHBOARD_ADMIN_PASSWORD) ADMIN_PASSWORD_VALUE="$value" ;;
    DASHBOARD_AUTH_SECRET) AUTH_SECRET_VALUE="$value" ;;
    NEXT_PUBLIC_BASE_URL|DASHBOARD_PUBLIC_BASE_URL|DASHBOARD_BASE_URL) NEXT_PUBLIC_BASE_URL_VALUE="$value" ;;
    AI_SUMMARY_API_KEY) AI_SUMMARY_API_KEY_VALUE="$value" ;;
    AI_SUMMARY_MODEL) AI_SUMMARY_MODEL_VALUE="$value" ;;
    AI_SUMMARY_BASE_URL) AI_SUMMARY_BASE_URL_VALUE="$value" ;;
    AI_SUMMARY_TIMEOUT_MS) AI_SUMMARY_TIMEOUT_MS_VALUE="$value" ;;
    AI_SUMMARY_CACHE_TTL_MS) AI_SUMMARY_CACHE_TTL_MS_VALUE="$value" ;;
  esac
done <<< "$REMOTE_ENV_CONTENT"

if [[ -n "$MYSQL_DB_STAT_VALUE" ]]; then
  MYSQL_DB_VALUE="$MYSQL_DB_STAT_VALUE"
fi

if [[ -z "$NEXT_PUBLIC_BASE_URL_VALUE" ]]; then
  NEXT_PUBLIC_BASE_URL_VALUE="$DEFAULT_BASE_URL"
fi

cat > "$TARGET_FILE" <<ENV
DB_HOST=localhost
DB_PORT=${MYSQL_PORT_VALUE}
DB_USER=${MYSQL_USER_VALUE}
DB_PASSWORD=${MYSQL_PASSWORD_VALUE}
DB_NAME=${MYSQL_DB_VALUE}
NODE_ENV=production
PORT=3001
NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL_VALUE}
DASHBOARD_ADMIN_EMAIL=${ADMIN_EMAIL_VALUE}
DASHBOARD_ADMIN_PASSWORD=${ADMIN_PASSWORD_VALUE}
DASHBOARD_AUTH_SECRET=${AUTH_SECRET_VALUE}
AI_SUMMARY_API_KEY=${AI_SUMMARY_API_KEY_VALUE}
AI_SUMMARY_MODEL=${AI_SUMMARY_MODEL_VALUE}
AI_SUMMARY_BASE_URL=${AI_SUMMARY_BASE_URL_VALUE}
AI_SUMMARY_TIMEOUT_MS=${AI_SUMMARY_TIMEOUT_MS_VALUE}
AI_SUMMARY_CACHE_TTL_MS=${AI_SUMMARY_CACHE_TTL_MS_VALUE}
ENV

echo "Wrote $TARGET_FILE"
