#!/bin/bash
set -euo pipefail

VPS="${VPS:-beget}"
REMOTE_ENV_PATH="${REMOTE_ENV_PATH:-/var/www/www-root/data/.production.env}"
TARGET_FILE="${1:-.env.production}"
DEFAULT_BASE_URL="${DEFAULT_BASE_URL:-https://dashboards.adreports.ru}"

REMOTE_ENV_CONTENT="$(ssh "$VPS" "cat '$REMOTE_ENV_PATH'")"
SOURCE_ENV_FILE="$(mktemp)"

cleanup() {
  rm -f "$SOURCE_ENV_FILE"
}
trap cleanup EXIT
chmod 600 "$SOURCE_ENV_FILE"
printf '%s\n' "$REMOTE_ENV_CONTENT" > "$SOURCE_ENV_FILE"

find_missing_dotenv_keys() {
  local env_file="$1"
  shift
  local node_bin=""

  if ! node_bin="$(command -v node)"; then
    printf '%s ' "$@"
    return 1
  fi

  "$node_bin" - "$env_file" "$@" <<'JS'
const fs = require("node:fs");
const { parseEnv } = require("node:util");

const [envFile, ...requiredKeys] = process.argv.slice(2);
let parsed;
try {
  if (typeof parseEnv !== "function") throw new Error("dotenv parser unavailable");
  parsed = parseEnv(fs.readFileSync(envFile, "utf8"));
} catch {
  process.stdout.write(requiredKeys.join(" "));
  process.exit(1);
}

const missingKeys = requiredKeys.filter((key) =>
  typeof parsed[key] !== "string" || parsed[key].trim().length === 0
);
if (missingKeys.length > 0) {
  process.stdout.write(missingKeys.join(" "));
  process.exit(1);
}
JS
}

source_required_keys=(
  MYSQL_USER
  MYSQL_PASSWORD
  DASHBOARD_ADMIN_EMAIL
  DASHBOARD_ADMIN_PASSWORD
  DASHBOARD_AUTH_SECRET
  ABBOTT_DASHBOARD_PASSWORD
  ABBOTT_DASHBOARD_EMBED_KEY
  METRIKA_TOKEN
  ABBOTT_PRIVATE_DB_HOST
  ABBOTT_PRIVATE_DB_PORT
  ABBOTT_PRIVATE_DB_USER
  ABBOTT_PRIVATE_DB_PASSWORD
  ABBOTT_PRIVATE_DB_NAME
)

missing_source_keys=""
if ! missing_source_keys="$(find_missing_dotenv_keys "$SOURCE_ENV_FILE" "${source_required_keys[@]}")"; then
  printf 'Missing required production env keys in %s: %s\n' "$REMOTE_ENV_PATH" "$missing_source_keys" >&2
  exit 1
fi

MYSQL_PORT_VALUE="3306"
MYSQL_USER_VALUE=""
MYSQL_PASSWORD_VALUE=""
MYSQL_DB_VALUE="report_bd"
MYSQL_DB_STAT_VALUE=""
ADMIN_EMAIL_VALUE=""
ADMIN_PASSWORD_VALUE=""
AUTH_SECRET_VALUE=""
METRIKA_TOKEN_VALUE=""
ABBOTT_DASHBOARD_PASSWORD_VALUE=""
ABBOTT_DASHBOARD_EMBED_KEY_VALUE=""
ABBOTT_PRIVATE_DB_HOST_VALUE=""
ABBOTT_PRIVATE_DB_PORT_VALUE=""
ABBOTT_PRIVATE_DB_USER_VALUE=""
ABBOTT_PRIVATE_DB_PASSWORD_VALUE=""
ABBOTT_PRIVATE_DB_NAME_VALUE=""
NEXT_PUBLIC_BASE_URL_VALUE=""
AI_SUMMARY_API_KEY_VALUE=""
AI_SUMMARY_MODEL_VALUE="gemini-flash-latest"
AI_SUMMARY_COMPLEX_MODEL_VALUE="gemini-2.5-pro"
AI_SUMMARY_FALLBACK_MODELS_VALUE="gemini-2.5-flash,gemini-2.5-flash-lite"
AI_SUMMARY_COMPLEXITY_THRESHOLD_VALUE="2400"
AI_SUMMARY_BASE_URL_VALUE="https://generativelanguage.googleapis.com/v1beta/openai"
AI_SUMMARY_TEMPERATURE_VALUE=""
AI_SUMMARY_TIMEOUT_MS_VALUE="18000"
AI_SUMMARY_CACHE_TTL_MS_VALUE="300000"
AI_SUMMARY_MAX_TOKENS_VALUE="220"
GOOGLE_ADS_DEVELOPER_TOKEN_VALUE=""
GOOGLE_ADS_CLIENT_ID_VALUE=""
GOOGLE_ADS_CLIENT_SECRET_VALUE=""
GOOGLE_ADS_REFRESH_TOKEN_VALUE=""
GOOGLE_ADS_LOGIN_CUSTOMER_ID_VALUE=""
GOOGLE_ADS_CUSTOMER_IDS_VALUE=""
YANDEX_WEBMASTER_ENABLED_VALUE="false"
YANDEX_WEBMASTER_CLIENT_ID_VALUE=""
YANDEX_WEBMASTER_CLIENT_SECRET_VALUE=""
YANDEX_WEBMASTER_REDIRECT_URI_VALUE="https://oauth.yandex.ru/verification_code"
YANDEX_WEBMASTER_OAUTH_TOKEN_VALUE=""
YANDEX_WEBMASTER_REFRESH_TOKEN_VALUE=""
YANDEX_WEBMASTER_HOST_ID_VALUE=""
YANDEX_WEBMASTER_DEFAULT_DATE_RANGE_DAYS_VALUE="7"
YANDEX_WEBMASTER_DAILY_LAG_DAYS_VALUE="3"
YANDEX_WEBMASTER_DEVICE_TYPE_VALUE="ALL"
YANDEX_WEBMASTER_TOKEN_STATE_PATH_VALUE="/var/www/www-root/data/.yandex-webmaster-token-state.json"
YANDEX_WEBMASTER_PYTHON_BIN_VALUE="/var/www/dashboard/.gads-venv/bin/python"
PYTHONWARNINGS_VALUE="ignore"

while IFS= read -r raw_line; do
  line="${raw_line%$'\r'}"
  if [[ -z "$line" || "$line" == \#* || "$line" != *=* ]]; then
    continue
  fi

  key="${line%%=*}"
  value="${line#*=}"

  case "$key" in
    MYSQL_PORT) MYSQL_PORT_VALUE="$value" ;;
    MYSQL_USER) MYSQL_USER_VALUE="$value" ;;
    MYSQL_PASSWORD) MYSQL_PASSWORD_VALUE="$value" ;;
    MYSQL_DB) MYSQL_DB_VALUE="$value" ;;
    MYSQL_DB_STAT) MYSQL_DB_STAT_VALUE="$value" ;;
    DASHBOARD_ADMIN_EMAIL) ADMIN_EMAIL_VALUE="$value" ;;
    DASHBOARD_ADMIN_PASSWORD) ADMIN_PASSWORD_VALUE="$value" ;;
    DASHBOARD_AUTH_SECRET) AUTH_SECRET_VALUE="$value" ;;
    METRIKA_TOKEN) METRIKA_TOKEN_VALUE="$value" ;;
    ABBOTT_DASHBOARD_PASSWORD) ABBOTT_DASHBOARD_PASSWORD_VALUE="$value" ;;
    ABBOTT_DASHBOARD_EMBED_KEY) ABBOTT_DASHBOARD_EMBED_KEY_VALUE="$value" ;;
    ABBOTT_PRIVATE_DB_HOST) ABBOTT_PRIVATE_DB_HOST_VALUE="$value" ;;
    ABBOTT_PRIVATE_DB_PORT) ABBOTT_PRIVATE_DB_PORT_VALUE="$value" ;;
    ABBOTT_PRIVATE_DB_USER) ABBOTT_PRIVATE_DB_USER_VALUE="$value" ;;
    ABBOTT_PRIVATE_DB_PASSWORD) ABBOTT_PRIVATE_DB_PASSWORD_VALUE="$value" ;;
    ABBOTT_PRIVATE_DB_NAME) ABBOTT_PRIVATE_DB_NAME_VALUE="$value" ;;
    NEXT_PUBLIC_BASE_URL|DASHBOARD_PUBLIC_BASE_URL|DASHBOARD_BASE_URL) NEXT_PUBLIC_BASE_URL_VALUE="$value" ;;
    AI_SUMMARY_API_KEY) AI_SUMMARY_API_KEY_VALUE="$value" ;;
    AI_SUMMARY_MODEL) AI_SUMMARY_MODEL_VALUE="$value" ;;
    AI_SUMMARY_COMPLEX_MODEL) AI_SUMMARY_COMPLEX_MODEL_VALUE="$value" ;;
    AI_SUMMARY_FALLBACK_MODELS) AI_SUMMARY_FALLBACK_MODELS_VALUE="$value" ;;
    AI_SUMMARY_COMPLEXITY_THRESHOLD) AI_SUMMARY_COMPLEXITY_THRESHOLD_VALUE="$value" ;;
    AI_SUMMARY_BASE_URL) AI_SUMMARY_BASE_URL_VALUE="$value" ;;
    AI_SUMMARY_TEMPERATURE) AI_SUMMARY_TEMPERATURE_VALUE="$value" ;;
    AI_SUMMARY_TIMEOUT_MS) AI_SUMMARY_TIMEOUT_MS_VALUE="$value" ;;
    AI_SUMMARY_CACHE_TTL_MS) AI_SUMMARY_CACHE_TTL_MS_VALUE="$value" ;;
    AI_SUMMARY_MAX_TOKENS) AI_SUMMARY_MAX_TOKENS_VALUE="$value" ;;
    GOOGLE_ADS_DEVELOPER_TOKEN) GOOGLE_ADS_DEVELOPER_TOKEN_VALUE="$value" ;;
    GOOGLE_ADS_CLIENT_ID) GOOGLE_ADS_CLIENT_ID_VALUE="$value" ;;
    GOOGLE_ADS_CLIENT_SECRET) GOOGLE_ADS_CLIENT_SECRET_VALUE="$value" ;;
    GOOGLE_ADS_REFRESH_TOKEN) GOOGLE_ADS_REFRESH_TOKEN_VALUE="$value" ;;
    GOOGLE_ADS_LOGIN_CUSTOMER_ID) GOOGLE_ADS_LOGIN_CUSTOMER_ID_VALUE="$value" ;;
    GOOGLE_ADS_CUSTOMER_IDS) GOOGLE_ADS_CUSTOMER_IDS_VALUE="$value" ;;
    YANDEX_WEBMASTER_ENABLED) YANDEX_WEBMASTER_ENABLED_VALUE="$value" ;;
    YANDEX_WEBMASTER_CLIENT_ID) YANDEX_WEBMASTER_CLIENT_ID_VALUE="$value" ;;
    YANDEX_WEBMASTER_CLIENT_SECRET) YANDEX_WEBMASTER_CLIENT_SECRET_VALUE="$value" ;;
    YANDEX_WEBMASTER_REDIRECT_URI) YANDEX_WEBMASTER_REDIRECT_URI_VALUE="$value" ;;
    YANDEX_WEBMASTER_OAUTH_TOKEN) YANDEX_WEBMASTER_OAUTH_TOKEN_VALUE="$value" ;;
    YANDEX_WEBMASTER_REFRESH_TOKEN) YANDEX_WEBMASTER_REFRESH_TOKEN_VALUE="$value" ;;
    YANDEX_WEBMASTER_HOST_ID) YANDEX_WEBMASTER_HOST_ID_VALUE="$value" ;;
    YANDEX_WEBMASTER_DEFAULT_DATE_RANGE_DAYS) YANDEX_WEBMASTER_DEFAULT_DATE_RANGE_DAYS_VALUE="$value" ;;
    YANDEX_WEBMASTER_DAILY_LAG_DAYS) YANDEX_WEBMASTER_DAILY_LAG_DAYS_VALUE="$value" ;;
    YANDEX_WEBMASTER_DEVICE_TYPE) YANDEX_WEBMASTER_DEVICE_TYPE_VALUE="$value" ;;
    YANDEX_WEBMASTER_TOKEN_STATE_PATH) YANDEX_WEBMASTER_TOKEN_STATE_PATH_VALUE="$value" ;;
    YANDEX_WEBMASTER_PYTHON_BIN) YANDEX_WEBMASTER_PYTHON_BIN_VALUE="$value" ;;
    PYTHONWARNINGS) PYTHONWARNINGS_VALUE="$value" ;;
  esac
done <<< "$REMOTE_ENV_CONTENT"

if [[ -n "$MYSQL_DB_STAT_VALUE" ]]; then
  MYSQL_DB_VALUE="$MYSQL_DB_STAT_VALUE"
fi

if [[ -z "$NEXT_PUBLIC_BASE_URL_VALUE" ]]; then
  NEXT_PUBLIC_BASE_URL_VALUE="$DEFAULT_BASE_URL"
fi

missing_keys=()

require_value() {
  local key_name="$1"
  local key_value="$2"
  local semantic_value="$key_value"

  semantic_value="${semantic_value#"${semantic_value%%[![:space:]]*}"}"
  semantic_value="${semantic_value%"${semantic_value##*[![:space:]]}"}"
  if [[ "$semantic_value" == '"'*'"' || "$semantic_value" == "'"*"'" ]]; then
    semantic_value="${semantic_value:1:${#semantic_value}-2}"
  else
    semantic_value="${semantic_value%%#*}"
  fi

  if [[ ! "$semantic_value" =~ [^[:space:]] ]]; then
    missing_keys+=("$key_name")
  fi
}

require_value "MYSQL_USER" "$MYSQL_USER_VALUE"
require_value "MYSQL_PASSWORD" "$MYSQL_PASSWORD_VALUE"
require_value "DASHBOARD_ADMIN_EMAIL" "$ADMIN_EMAIL_VALUE"
require_value "DASHBOARD_ADMIN_PASSWORD" "$ADMIN_PASSWORD_VALUE"
require_value "DASHBOARD_AUTH_SECRET" "$AUTH_SECRET_VALUE"
require_value "ABBOTT_DASHBOARD_PASSWORD" "$ABBOTT_DASHBOARD_PASSWORD_VALUE"
require_value "ABBOTT_DASHBOARD_EMBED_KEY" "$ABBOTT_DASHBOARD_EMBED_KEY_VALUE"
require_value "METRIKA_TOKEN" "$METRIKA_TOKEN_VALUE"
require_value "ABBOTT_PRIVATE_DB_HOST" "$ABBOTT_PRIVATE_DB_HOST_VALUE"
require_value "ABBOTT_PRIVATE_DB_PORT" "$ABBOTT_PRIVATE_DB_PORT_VALUE"
require_value "ABBOTT_PRIVATE_DB_USER" "$ABBOTT_PRIVATE_DB_USER_VALUE"
require_value "ABBOTT_PRIVATE_DB_PASSWORD" "$ABBOTT_PRIVATE_DB_PASSWORD_VALUE"
require_value "ABBOTT_PRIVATE_DB_NAME" "$ABBOTT_PRIVATE_DB_NAME_VALUE"

if (( ${#missing_keys[@]} > 0 )); then
  printf 'Missing required production env keys in %s: %s\n' "$REMOTE_ENV_PATH" "${missing_keys[*]}" >&2
  exit 1
fi

cat > "$TARGET_FILE" <<ENV
DB_HOST=localhost
DB_PORT=${MYSQL_PORT_VALUE}
DB_USER=${MYSQL_USER_VALUE}
DB_PASSWORD=${MYSQL_PASSWORD_VALUE}
DB_NAME=${MYSQL_DB_VALUE}
MYSQL_HOST=localhost
MYSQL_PORT=${MYSQL_PORT_VALUE}
MYSQL_USER=${MYSQL_USER_VALUE}
MYSQL_PASSWORD=${MYSQL_PASSWORD_VALUE}
MYSQL_DB=${MYSQL_DB_VALUE}
NODE_ENV=production
PORT=3001
NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL_VALUE}
DASHBOARD_ADMIN_EMAIL=${ADMIN_EMAIL_VALUE}
DASHBOARD_ADMIN_PASSWORD=${ADMIN_PASSWORD_VALUE}
DASHBOARD_AUTH_SECRET=${AUTH_SECRET_VALUE}
ABBOTT_DASHBOARD_PASSWORD=${ABBOTT_DASHBOARD_PASSWORD_VALUE}
ABBOTT_DASHBOARD_EMBED_KEY=${ABBOTT_DASHBOARD_EMBED_KEY_VALUE}
METRIKA_TOKEN=${METRIKA_TOKEN_VALUE}
ABBOTT_PRIVATE_DB_HOST=${ABBOTT_PRIVATE_DB_HOST_VALUE}
ABBOTT_PRIVATE_DB_PORT=${ABBOTT_PRIVATE_DB_PORT_VALUE}
ABBOTT_PRIVATE_DB_USER=${ABBOTT_PRIVATE_DB_USER_VALUE}
ABBOTT_PRIVATE_DB_PASSWORD=${ABBOTT_PRIVATE_DB_PASSWORD_VALUE}
ABBOTT_PRIVATE_DB_NAME=${ABBOTT_PRIVATE_DB_NAME_VALUE}
AI_SUMMARY_API_KEY=${AI_SUMMARY_API_KEY_VALUE}
AI_SUMMARY_MODEL=${AI_SUMMARY_MODEL_VALUE}
AI_SUMMARY_COMPLEX_MODEL=${AI_SUMMARY_COMPLEX_MODEL_VALUE}
AI_SUMMARY_FALLBACK_MODELS=${AI_SUMMARY_FALLBACK_MODELS_VALUE}
AI_SUMMARY_COMPLEXITY_THRESHOLD=${AI_SUMMARY_COMPLEXITY_THRESHOLD_VALUE}
AI_SUMMARY_BASE_URL=${AI_SUMMARY_BASE_URL_VALUE}
AI_SUMMARY_TEMPERATURE=${AI_SUMMARY_TEMPERATURE_VALUE}
AI_SUMMARY_TIMEOUT_MS=${AI_SUMMARY_TIMEOUT_MS_VALUE}
AI_SUMMARY_CACHE_TTL_MS=${AI_SUMMARY_CACHE_TTL_MS_VALUE}
AI_SUMMARY_MAX_TOKENS=${AI_SUMMARY_MAX_TOKENS_VALUE}
GOOGLE_ADS_COLLECTOR_SCRIPT_PATH=/var/www/dashboard/fetch_google_ads_canonical.py
GOOGLE_ADS_PYTHON_BIN=/var/www/dashboard/.gads-venv/bin/python
GOOGLE_ADS_DEVELOPER_TOKEN=${GOOGLE_ADS_DEVELOPER_TOKEN_VALUE}
GOOGLE_ADS_CLIENT_ID=${GOOGLE_ADS_CLIENT_ID_VALUE}
GOOGLE_ADS_CLIENT_SECRET=${GOOGLE_ADS_CLIENT_SECRET_VALUE}
GOOGLE_ADS_REFRESH_TOKEN=${GOOGLE_ADS_REFRESH_TOKEN_VALUE}
GOOGLE_ADS_LOGIN_CUSTOMER_ID=${GOOGLE_ADS_LOGIN_CUSTOMER_ID_VALUE}
GOOGLE_ADS_CUSTOMER_IDS=${GOOGLE_ADS_CUSTOMER_IDS_VALUE}
YANDEX_DIRECT_COLLECTOR_SCRIPT_PATH=/var/www/dashboard/fetch_yandex_direct_canonical_api.py
YANDEX_DIRECT_PYTHON_BIN=/var/www/dashboard/.gads-venv/bin/python
YANDEX_WEBMASTER_ENABLED=${YANDEX_WEBMASTER_ENABLED_VALUE}
YANDEX_WEBMASTER_CLIENT_ID=${YANDEX_WEBMASTER_CLIENT_ID_VALUE}
YANDEX_WEBMASTER_CLIENT_SECRET=${YANDEX_WEBMASTER_CLIENT_SECRET_VALUE}
YANDEX_WEBMASTER_REDIRECT_URI=${YANDEX_WEBMASTER_REDIRECT_URI_VALUE}
YANDEX_WEBMASTER_OAUTH_TOKEN=${YANDEX_WEBMASTER_OAUTH_TOKEN_VALUE}
YANDEX_WEBMASTER_REFRESH_TOKEN=${YANDEX_WEBMASTER_REFRESH_TOKEN_VALUE}
YANDEX_WEBMASTER_HOST_ID=${YANDEX_WEBMASTER_HOST_ID_VALUE}
YANDEX_WEBMASTER_DEFAULT_DATE_RANGE_DAYS=${YANDEX_WEBMASTER_DEFAULT_DATE_RANGE_DAYS_VALUE}
YANDEX_WEBMASTER_DAILY_LAG_DAYS=${YANDEX_WEBMASTER_DAILY_LAG_DAYS_VALUE}
YANDEX_WEBMASTER_DEVICE_TYPE=${YANDEX_WEBMASTER_DEVICE_TYPE_VALUE}
YANDEX_WEBMASTER_TOKEN_STATE_PATH=${YANDEX_WEBMASTER_TOKEN_STATE_PATH_VALUE}
YANDEX_WEBMASTER_PYTHON_BIN=${YANDEX_WEBMASTER_PYTHON_BIN_VALUE}
PYTHONWARNINGS=${PYTHONWARNINGS_VALUE}
ENV

echo "Wrote $TARGET_FILE"
